terramate-io/terramate

- .github/workflows/ci.yml
- Makefile
- test/sandbox/git.go
- test/sandbox/git_test.go
- test/sandbox/sandbox.go
Add check automation for license info + add automation to add the license stuff
> chore: add license check + license automation

- git/git.go
- git/git_test.go
> fix: remote origin check fails with references with "/"

- hcl/printer.go
only append empty line between blocks.
> fix: Remove empty line at EOF

- docs/config.md
- docs/globals.md
- docs/locals-generation.md
Basic initial spec to how someone can leverage Terramate metadata + global definitions on Terraform code in a stack. The idea is to debate/evolve on top of this, so not final or complete, just the first idea that came from me and @i4ki talking about this.
> spec: add locals terraform generation

- cmd/terramate/cli/cli.go
- optimize code (remove re-implementation of library functions)
- add console/text/JSON format for color/no-color/JSON output
- add log level support in kong
- make setup fail-safe and always default to console / trace level on invalid settings
> chore: optimize logging set up - add failsafe defaults

- hack/mod-check
Improving the change detection to only look for go.mod changes, not overall changes on the entire project.
> chore: improve go mod tidyness check

- docs/backend-config.md
- docs/code-generation-config.md
- docs/config.md
Initial spec for a way to control the filenames on code generation.
> docs: add terramate.config.generate spec

- docs/terraform-generation.md
Started with the basics so we can discuss basic syntax/behavior/constraints. Still need to add definitions on overriding/hierarchical behavior, for now there is only a single example defining things on root and generating code for all stacks.
> docs: initial spec for terraform code generation

- cmd/terramate/e2etests/general_test.go
Forgot to enable the test back when I added the check back =P
> test: enable git check test again

- generate/genhcl/genhcl.go
- generate/genhcl/genhcl_test.go
- hcl/hcl.go
Now generate_hcl blocks can be defined on multiple files. 
Example:
```sh
#!/bin/bash
set -o nounset
set -o errexit
terramate {
config {
}
}
EOM
mkdir -p stacks/stack-{1,2}
terramate stacks init stacks/stack-{1,2}
cat > stacks/globals.tm.hcl <<- EOM
globals {
tf_version = "1.1.3"
gh_owner = "the-awesome-mineiros"
gh_provider_version = "4.19.1"
}
EOM
cat > stacks/provider.tm.hcl <<- EOM
generate_hcl "provider.tf" {
content {
provider "github" {
owner = global.gh_owner
}
terraform {
required_providers {
github = {
source  = "integrations/github"
version = global.gh_provider_version
}
}
}
terraform {
required_version = global.tf_version
}
}
}
EOM
cat > stacks/main.tm.hcl <<- EOM
generate_hcl "main.tf" {
content {
module …
```
> feat: add multiple config files support to generate_hcl

- exported_locals.go
- exported_locals_test.go
- hcl/hcl.go
Now export_as_locals blocks can be loaded from multiple files.
> feat: add multiple config files support to export_as_locals 

- docs/project-config.md
Just a small docs/spec for the required_version behavior.
> docs: add terramate.required_version

- cmd/terramate/cli/cli.go
- cmd/terramate/e2etests/run_test.go
Allows to disable outdated code generation check.
> feat: add --disable-check-gen-code

- generate/genhcl/genhcl_test.go
Still missing stuff, but want to keep PRs small/incremental.
> tests: add interpolation errs

- hcl/eval/partial_fuzz_test.go
Got some from hcl fuzz and added for examples so maybe we get some interesting fuzzied variants of for loops :-)
> tests: add seed corpus

- generate/generate.go
Small refactoring on the outdated code detection, hopefully it is more clear now.
> refactor: improve outdated detection code

- README.md
> Update logo to version with copy

- docs/codegen/generate-file.md
- docs/codegen/overview.md
Initial spec for the new generate_file block.
> docs: add genfile initial docs/spec

- cmd/terramate/cli/cli.go
- cmd/terramate/cli/project.go
- cmd/terramate/cli/project_test.go
- cmd/terramate/e2etests/general_test.go
The check for local default is updated is not working properly, this PR fixes that.
> fix: check local default is updated

- README.md
> docs: Add back missing introduction sentence

- cmd/terramate/cli/cli.go
> fix: terramate fmt help

- docs/codegen/overview.md
Removing unnecessary dots on bullet list
> chore: remove unnecessary dots on list

- README.md
> chore: fix project setup steps

- generate/generate_file_test.go
- generate/generate_hcl_test.go
- generate/genfile/genfile.go
- generate/genhcl/genhcl.go
- run/env.go
- stack/eval.go
- stack/globals.go
Add new `terramate.root` metadata.
> feat: add terramate.root

- generate/generate_file_test.go
- generate/generate_hcl_test.go
- stack/eval.go
Using terramate.root.path.absolute instead of just terramate.root :-)
> fix: use terramate.root.path.absolute

- go.mod
- go.sum
- hcl/hcl.go
- hcl/hcl_cfg_run_test.go
- test/hcl.go
Add new configs to run block:
```
check_gen_code = true
```
When the attribute is not defined in the run block it defaults to true.
> feat: add terramate.config.run.check_gen_code config

- cmd/terramate/e2etests/list_git_test.go
Added test to check that new Terraform 1.13 feature, variables with object definitions with optionals, doesn't break parsing and detecting changes across modules.
Added a test doing change detection on a module when the code also has variables with the new optionals being used.
> test: parsing variables with optionals (tf 1.13)

- README.md
Star history is cool :-).
Added the badge.
> chore: add star history chart badge

- docs/codegen/generate-hcl.md
- generate/genhcl/genhcl.go
- generate/genhcl/genhcl_dynamic_test.go
Makes tm_dynamic.for_each optional.
Depends on #619
> feat: generate_hcl: make tm_dynamic for_each optional

- globals/globals.go
When we added the globals extensions feature the acessor for globals don't have a nice string representation. The acessor being used in the error messages produced a criptic message.
Using this example:
```sh
#!/bin/bash
set -o nounset
set -o errexit
terramate {
config {
}
}
EOM
terramate create stack-1
cat > globals.tm.hcl <<- EOM
globals {
a = global.undefined
}
EOM
cat > main.tm.hcl <<- EOM
generate_hcl "file.hcl" {
content {
a = global.a
}
}
EOM
```
We are getting an error:
```
Created stack stack-1
Code generation report
Failures:
- /stack-1
error: /tmp/tmp.JzfAbZ1B3X/globals.tm.hcl:2,15-25: loading globals: global eval: global.{[a
] %!!(MISSING)s(int=1)}: eval expression: This object does not have …
```
> fix: global evaluation error messages

- README.md
Some basic docs on our versioning scheme.
> chore: add some docs on versioning

- docs/stack.md
Document the stack block better, should avoid confusion as what happened at #692
> chore: improve stack docs

- tf/terraform.go
- tf/terraform_test.go
Terraform provides different was to define modules, as it happens with override described in #697. Instead of assuming and validating what is valid Terraform code we just look for information we need and discard any module blocks that we don't recognize but that could be valid Terraform (we don't assume anymore that we know how to validate Terraform code, Terraform is the one that knows this, we just look for information that is interesting to change detection and that is it).
Closes #697
> fix: allow terraform code with any kind of module definition

- mapexpr/map.go
- stack/globals_test.go
The `Variables()` method of the `hcl.Expression` interface was not implemented, then the `tm_try()` inside `map` blocks referencing outer variables (`terramate`, `globals`, etc) was not correctly handled.
The `Variables()` method of the `MapExpr` is implemented by accumulating the `Variables()` of each of its attributes and subblock but ignoring local scoped variables (ie the iterator namespace).
> fix: properly postpone evaluation of expressions with unknowns

- docs/config-overview.md
- docs/map.md
- docs/sharing-data.md
Add documentation for the `map` block.
Preview: https://github.com/mineiros-io/terramate/blob/i4k-map-docs/docs/map.md
> chore: document the map block

- .github/workflows/tweet.yml
> ci: move tweet action to newer action

- README.md
Adds a dominant get involved section for users to understand how they can get in touch with us.
> Add get involved section to docs

- README.md
Currently, the link is broken.
> Fix SemVer link in README.md

- README.md
- docs/getting-started.md
Cleaning up the main entry README.md so folks don't get lost when they see Terramate for the first time
> Restructure the entry README.md

- CODE_OF_CONDUCT.md
- README.md
Previously we highlighted technical features. We are changing this now to use-cases for our users to understand the value of Terramate. In general, this PR aims toward providing the audience with a better idea of what Terramate is and how what problems it can sovle.
> Add more information to README.md

- .github/workflows/release.yml
- .goreleaser.yaml
We don't use slack anymore since we moved to Discord.
> Remove slack from releases since we moved to discord

- docs/installation.md
> docs: reviewed installation guide

- docs/stacks/index.md
> docs: reviewed stacks configuration

- docs/orchestration/index.md
> docs: reviewed orchestration

- docs/about-stacks.md
> docs: reviewed About Stacks

- docs/configuration/project-config.md
> docs: edited sub-headings and sentences structures

- docs/change-detection/index.md
Rephrased grammar in Change Detection documentation.
> Rephrased grammar in Change Detection documentation

- docs/guides/generate-provider/generate_backend.tm.hcl
- docs/guides/generate-provider/generate_providers.tm.hcl
- docs/guides/generate-provider/stacks/aws/_global/terraform-state-bucket/_terramate_generated_providers.tf
- docs/guides/generate-provider/stacks/aws/_terramate_generated_providers.tf
- docs/guides/generate-provider/stacks/aws/config.tm.hcl
- docs/guides/generate-provider/stacks/aws/us-east-1/vpc/main/_terramate_generated_providers.tf
- chore: simplify config
- chore: add alias support to guide code
> chore: add alias support to guide code

- docs/getting-started/index.md
We had several requests from the community to explain the difference on how to use Terramate with and without Git integration.
The suggested change should make the differences more clear and elaborates on it in the getting started guide.
> Explain how to use Terramate with and without Git integration

- docs/about-stacks.md
- docs/change-detection/index.md
- docs/cmdline.md
- docs/code-generation/generate-file.md
- docs/code-generation/generate-hcl.md
- docs/code-generation/index.md
- docs/configuration/index.md
- docs/configuration/project-config.md
- docs/configuration/project-setup.md
- docs/configuration/upgrade-check.md
- docs/data-sharing/index.md
- docs/functions/index.md
- docs/getting-started/index.md
- docs/installation.md
- docs/map.md
- docs/orchestration/index.md
- docs/package.json
- docs/pnpm-lock.yaml
- docs/tag-filter.md
Currently all page titles follow the schema `pagetopic - | Terramate | Terramate`
This change removes the duplicate Terramate from all page titles.
> Remove duplicate terramate title from docs

- docs/cmdline/install-completions.md
This PR updates the description of the `install-autocompletion` docs to something more tangible.
> Update installation instructions for autocompletions

- docs/data-sharing/index.md
Thanks @kkmlr for reporting the issue.
> docs: fix the documentation of stack metadata

- cloud/types.go
- cmd/terramate/cli/cloud.go
Sends the deployment commit message as title and description.
> chore: send deployment commit title and description

- docs/configuration/project-setup.md
Change the title and add an explanation of how to import existing Terraform infrastructure.
> docs: change title and improve project setup page

- cloud/types.go
- cmd/terramate/cli/cloud.go
The new metadata object (not all fields due to local run) is shown below.
Note that `git_head_commit_sha` is the only field that comes from the local `git` (atm).
```
{
"git_head_commit_sha": "72839014a2912c8a8445ae696e89efb5ace4b37d",
"github_commit_author_avatar_url": "https://avatars.githubusercontent.com/u/251478?v=4",
"github_commit_author_git_date": "2023-09-22T08:15:44Z",
"github_commit_author_git_email": "t.nateldemoura@gmail.com",
"github_commit_author_git_name": "Tiago Natel",
"github_commit_author_login": "i4ki",
"github_commit_committer_avatar_url": "https://avatars.githubusercontent.com/u/251478?v=4",
"github_commit_committer_git_date": "2023-09-22T08:15:44Z",
"github_commit_committer_git_email": "t.nateldemoura@gmail.com",
"github_commit_committer_git_name": "Tiago Natel", …
```
> chore(tmc): refactor metadata field names.

- stack/manager.go
> chore(change-detection): reuse global git wrapper.

- git/git.go
- git/git_test.go
- stack/manager.go
The safe.directory option was not used for git commands involved in the change detection, resulting in errors in case this flag was needed to detect the git repository.
Fixes #1159
* A method was added to set global arguments for the Git wrapper.
* The git config value for safe.directory is taken from the current environment, and in case a git command runs in an isolated environment, the value is forwarded via global arguments "-c safe.directory".
* Testing this with an e2etest is tricky, because it requires a setup with multiple users. Postponed for later.
> fix: git safe.directory is now considered when using --changed flag

- .github/pull_request_template.md
- CONTRIBUTING.md
Improves the contribution workflow:
- Template comments were added (not rendered by default) with additional information for each section.
- Now both "Reasons for This Change" and "Description of Changes" are covered by the first section "What this PR does / why we need it".
- A new section "Special notes for your reviewer" is added which must be filled with whatever information the OP believes are point of attention to the reviewer.
- A separate place for the linked issues.
The contribution doc was updated with the workflow:
- Each PR must introduce a single change
- signed and squashed commits
- conventional commits
- PR must be draft when not ready
The PR template is based on [Kubernetes PR Template](https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md?p …
> chore: update contribution doc and PR template

- stack/manager.go
It removes unnecessary debug messages that don't carry any useful information.
Other `log.Debug()` messages that carry information like _skipped files or directories_, _detected triggers_, etc, were kept in place.
```
yes but only fewer debug messages are seen when the log level is higher than or equal `debug`.
```
> chore: remove unnecessary debug messages

- docs/.vitepress/config.ts
Updates the default page tile and description for the documentation page.
> Update default page title and description for docs

- docs/cli/cmdline/list.md
- docs/cli/cmdline/trigger.md
document trigger and list cloud functionality
```
no
```
> docs(cloud): document trigger and list cloud functionality

- docs/cli/cmdline/clone.md
- docs/cli/cmdline/cloud-drift-show.md
- docs/cli/cmdline/cloud-info.md
- docs/cli/cmdline/cloud-login.md
- docs/cli/cmdline/create.md
Documents `cloud drift show`
```
no
```
> docs(cloud): add cloud drift show

- docs/cli/cmdline/run.md
Cloud options for run command were not documented
```
no
```
> docs(cloud): explain cloud options for run command

- cloud/cloud.go
- cloud/cloud_test.go
- cloud/testserver/stacks.go
- cloud/types.go
- cmd/terramate/cli/cli.go
- cmd/terramate/cli/cloud.go
- cmd/terramate/e2etests/cloud/list_cloud_test.go
- cmd/terramate/e2etests/cloud/run_cloud_drift_test.go
- test/cloud/client.go
Uses pagination when requesting resources from `v1/stacks/...` endpoints.
```
no
```
> chore(tmc): add pagination support to /v1/stacks.

- cmd/terramate/cli/cli.go
- cmd/terramate/cli/cloud.go
- cmd/terramate/e2etests/cloud/run_cloud_uimode_test.go
Depends on https://github.com/terramate-io/terramate/pull/1317
Depends on https://github.com/terramate-io/terramate/pull/1323
Use `printer` package to improve output of `terramate list`
```
The output of terramate list uses the `printer` package and hence is slightly
different than before.
```
> chore: Improve output of terramate list

- cmd/terramate/cli/cli.go
Depends on https://github.com/terramate-io/terramate/pull/1317
Depends on https://github.com/terramate-io/terramate/pull/1323
Use `printer` package to improve output of `terramate create`
```
The output of terramate create now uses the `printer` package and hence is
slightly different than before.
```
> chore: Improve output of terramate create

- .golangci.yml
- cmd/terramate/cli/cloud_credential_google.go
- cmd/terramate/cli/project.go
* Add two new linters:
* bodyclose
* exportloopref
* Addressed linter warnings
no
> chore: add linters bodyclose and exportloopref

- docs/.vitepress/config.ts
- chore: Remove strategies group
- chore: improve order of sections
> chore: improve docs hierarchy

- docs/cli/projects/configuration.md
Documents the code gen safeguard in the project configuration page
> Add code gen safeguard to project config docs

- docs/cli/code-generation/variables/map.md
> Fix code block in maps docs

- docs/.vitepress/config.ts
> Fix Docs Sitemap

- docs/cli/cmdline/script/run.md
This is a rewording of the `script run` docs to be more clear about command labels.
```
no
```
> chore(scripts): tweak script run docs

- config/config.go
Fixes a performance regression in the config loader.
```
no
```
> fix: performance regression in config loader

- cmd/terramate/cli/cloud.go
Before, if the same user did multiple reviews, the synced reviewer list would contain duplicates. This PR changes it so that each reviewer is only included once.
```
no
```
> fix(cloud): synced reviewers should be unique

- docs/cli/getting-started/index.md
New quickstart guide for the Terramate CLI documentation that incorporates features of Terramate v0.4.4.
> Add new Getting Started Guide

- docs/cli/orchestration/safeguards.md
- docs/cli/projects/configuration.md
* Add deprecation notices to the old style safeguards (checks).
> docs: add deprecation notices to old style safeguards

- cmd/terramate/e2etests/core/run_script_test.go
This PR adds a regression test for #1452 similar to the one provided by @cwe1ss. The issue itself was fixed in #1444 already.
```
no
```
> chore: add regression test for script command order

- CHANGELOG.md
Rebase #1463 and adjusts the new changelog entries.
no
Closes #1463 
```
no
```
> chore: improve change log.

- docs/cli/orchestration/scripts.md
Correcting an error in the code snippet shown in Docs.
Yes, it changes a code snippet in Docs.
Before:
```
terraform run terraform apply -auto-approve
```
After:
```
terramate run terraform apply -auto-approve
```
> docs: correcting code-snippet

- CHANGELOG.md
- cmd/terramate/cli/cli.go
- cmd/tgdeps/main.go
- docs/cli/change-detection/integrations/terragrunt.md
- docs/cli/cmdline/create.md
- stack/manager.go
- stack/manager_test.go
- tg/tg_module.go
- tg/tg_module_test.go
Add change detection support for Terragrunt modules/stacks.
none
```
yes
```
> feat: Terragrunt change detection

- cmd/terramate/cli/cloud_sync_terraform_plan.go
This PR increases the timeout of an internal invocation of `terraform show` from 5s to 5m to prevent timeouts. In case a timeout should still happen, the error message says so.
```
no
```
> chore: increase terraform show timeout

- CHANGELOG.md
- cmd/terramate/cli/cloud.go
- cmd/terramate/cli/cloud_sync_deployment.go
- cmd/terramate/cli/cloud_sync_drift.go
- cmd/terramate/cli/run.go
- cmd/terramate/cli/script_run.go
- cmd/terramate/e2etests/cloud/run_cloud_drift_test.go
Apply the #1546 to the v0.5.x versions.
none
```
yes
```
> fix: inconsistency in stack.id case sensitivity in cloud features.

- docs/.vitepress/config.ts
Fixes the path for og images used in the documentation website
> Fix absolute path for og images

- docs/.vitepress/config.ts
Fixing the `og` and `twitter` meta tags.
> Fix og and twitter meta tags

- CHANGELOG.md
- Improve breaking change note in the changelog.
- Add missing sections
none
```
no
```
> chore: improve changelog

- CHANGELOG.md
- cmd/terramate/cli/cli.go
- cmd/terramate/cli/script_run.go
- cmd/terramate/e2etests/core/run_script_test.go
- docs/cli/cmdline/script/script-run.md
Add flag `--reverse` to `script run`
```
Yes, a new flag `--reverse` is added to `script run`.
```
> feat: add --reverse to script run

- docs/.vitepress/config.ts
- docs/cli/on-boarding/opentofu.md
- docs/cli/on-boarding/terraform.md
- docs/cli/on-boarding/terragrunt.md
- docs/cloud/deployments/synchronization-from-cli.md
- docs/cloud/drifts/synchronization-from-cli.md
- docs/cloud/on-boarding/index.md
- docs: fix out file option in plan actions
- docs: Add cloud onboarding
> docs: Add cloud onboarding

- CHANGELOG.md
- cmd/terramate/cli/cli.go
- cmd/terramate/cli/cloud_credential.go
- cmd/terramate/cli/cloud_credential_github.go
- cmd/terramate/cli/cloud_credential_github_oidc.go
- cmd/terramate/cli/cloud_credential_google.go
- cmd/terramate/cli/github/client.go
- cmd/terramate/e2etests/cloud/run_cloud_uimode_test.go
- cmd/terramate/e2etests/internal/runner/runner.go
Add support for `github` login with `terramate cloud login --github`.
none
```
yes
```
> feat: add GitHub Social login.

- CHANGELOG.md
- generate/generate_hcl_test.go
- go.mod
- go.sum
Add support for parsing and generating code using HCL namespaced functions.
Eg.:
```
generate_hcl "example.hcl" {
content {
result = foo::something()
}
}
```
For details, check: https://github.com/hashicorp/hcl/releases/tag/v2.20.0
none
```
yes, add a new feature.
```
> feat: add support for namespaced functions.

- cmd/terramate/cli/cli.go
- cmd/terramate/cli/clitest/messages.go
- cmd/terramate/cli/cloud.go
- cmd/terramate/cli/cloud_credential_github.go
- cmd/terramate/cli/cloud_credential_google.go
- cmd/terramate/cli/project.go
- cmd/terramate/cli/run.go
- cmd/terramate/cli/script_info.go
- cmd/terramate/cli/script_run.go
- cmd/terramate/e2etests/cloud/run_cloud_uimode_test.go
- errors/detailed.go
- errors/detailed_test.go
- errors/verbosity/verbosity.go
- printer/printer.go
This PR adds a new error type `DetailedError` and refactors some code to make use of it.
Fixes #
* For convenience, formatting has been added directly to the cli.fatal(), ... etc. functions rather than requiring `Sprintf`.
* Replacing the error messages with the new DetailedError-style is still far from complete and should be changed over time.
```
no
```
> refactor: improve cloud errors

- CHANGELOG.md
- cmd/terramate/cli/cloud.go
See https://github.com/terramate-io/terramate/pull/1692
```
no
```
> fix: backport fix from #1692 to 0.6.x

- CHANGELOG.md
- cmd/terramate/cli/cloud.go
This fixes a potential crash when trying to obtain the pull request metadata associated with a Github repository.
```
no
```
> fix: mishandled error leading to nil dereference in metadata

- cmd/terramate/e2etests/core/list_git_test.go
There was no test for the case of changed symlinks.
The test added just checks if symlinks don't break the existing functionality.
none
```
no
```
> chore: add symlink test to change detection.

- CHANGELOG.md
- cmd/terramate/cli/cli.go
- cmd/terramate/cli/cloud.go
- cmd/terramate/cli/run.go
- cmd/terramate/cli/script_run.go
- config/config.go
- e2etests/cloud/cloud_status_test.go
- e2etests/cloud/run_cloud_deployment_test.go
- e2etests/cloud/run_cloud_drift_test.go
- e2etests/cloud/run_cloud_sync_preview_test.go
- hcl/hcl.go
This PR moves the `targets` config block as a sub-block of `cloud`, because targets are a cloud option.
- Targets is only released as RC, so I just changed the existing changelog entry.
```
no, the feature is not released yet
```
> refactor: rename config.targets to config.cloud.targets

- CHANGELOG.md
The changelog was messed by an automatic rebase from main. 
none
```
no
```
> chore: fix CHANGELOG.

- cmd/terramate/cli/cloud_sync_terraform_plan.go
- e2etests/cloud/run_cloud_drift_test.go
- e2etests/cloud/testdata/cloud-sync-drift-plan-file/sanitized.plan.json
- e2etests/cmd/helper/main.go
- go.mod
- go.sum
Use Terramate `tfjson` library for synchronised plan JSON.
none
Still testing with `tfjson` v1.0.0-rc1
```
no
```
> feat(cloud): use enhanced library for plan sanitization.

- config/config.go
- config/sharing_backend.go
- generate/generate.go
- generate/generate_sharing_test.go
- generate/genfile/genfile.go
- generate/genfile/genfile_test.go
- generate/genhcl/genhcl.go
- generate/genhcl/genhcl_test.go
- generate/genhcl/partial_eval_test.go
- generate/sharing/sharing_backend.go
- hcl/info/range.go
Generate the "sharing" related blocks (outputs and variables).
none
Depends on #1805 
```
yes
```
> feat: generate sharing blocks.

- CHANGELOG.md
- cmd/terramate/cli/cli.go
- cmd/terramate/cli/run.go
- config/sharing_backend.go
- e2etests/cloud/generate-e2e-testserver.tm
- e2etests/cmd/helper/main.go
- e2etests/core/run_sharing_test.go
- hcl/eval/eval.go
- stack/manager.go
- stack/manager_test.go
Implement the orchestration phase of the "sharing outputs" experiment.
none
```
yes, complete the sharing feature.
```
> feat: connect stack output to stack inputs.

- stdlib/funcs_bench_test.go
For better information to assess the changes in #1845 this PR adds more benchmarks using `tm_try()`.
none
```
no
```
> chore: improve tm_try benchmarks.

- cloud/testserver/cloudstore/store.go
Fix race condition detected in tests detected in CI.
This read https://github.com/terramate-io/terramate/blob/main/cloud/testserver/stacks.go#L297
races against orgs upserted at https://github.com/terramate-io/terramate/blob/main/cloud/testserver/cloudstore/store.go#L307
none
This only affects our test infrastructure.
```
no
```
> test: fix race condition in testserver.

- e2etests/cloud/interop/interoperability_test.go
When interop tests run on `push` event, the `GITHUB_EVENT_FILE` needs to be mocked or else previews cannot be created.
Internal CIs.
```
no
```
> test: fix interop test when running on CI push event.

- benchmarks/changed/_test_mock.tf
- benchmarks/changed/changed_bench_test.go
- benchmarks/changed/doc.go
- benchmarks/changed/stack.tm.hcl
- test/sandbox/git.go
Just add change detection benchmark.
Subsequent PRs will use this.
none
```
no
```
> chore: add change detection benchmark.

- git/git.go
- git/git_test.go
- stack/manager.go
Optimize repo checks (uncommitted and untracked).
none
```
no
```
> chore: optimize check for dirty files.

- stack/manager.go
Small improvement from @snakster comment in #1897 review.
none
```
no
```
> chore: memoize changedFiles in a separate function.

- CHANGELOG.md
- cmd/terramate/cli/cli.go
- Cherry-pick @bgrams #1850 PR changes. This is needed because our CI change detection doesn't work across forks (for security reasons).
- Add CHANGELOG entry
none 
The tests are in #1910 
```
yes, add a new feature.
```
> feat: add env vars for common cli and run flags

- e2etests/cloud/run_script_cloud_deployment_test.go
- e2etests/core/run_sharing_test.go
- e2etests/core/run_test.go
- ls/ls_test.go
- makefiles/windows.mk
Fix more Windows tests.
none
```
no
```
> tests: fix more Windows tests.

- .github/workflows/ci-sync-deployment.yml
> chore: improve CI to deploy also backporting branches.

- .github/workflows/ci-sync-deployment.yml
- .github/workflows/ci-sync-preview.yml
> ci: fix change detection in backport branches.

- CHANGELOG.md
- config/config.go
- e2etests/core/fmt_test.go
- fs/fs.go
- fs/fs_bench_test.go
- hcl/fmt/fmt.go
- hcl/hcl.go
Fix `*.tmgen` files not been formatted in recursive mode.
none
```
```
> fix: formating of tmgen files.

- cmd/terramate/cli/cli_help.txt
Upgrading the helptext to match new messaging
> Upgrade CLI help text

- cmd/terramate/cli/cli.go
- cmd/terramate/cli/cloud.go
- cmd/terramate/cli/cloud_credential_google.go
- cmd/terramate/cli/telemetry/record.go
- cmd/terramate/cli/telemetry/record_test.go
- cmd/terramate/cli/telemetry/telemetry.go
- cmd/terramate/cli/telemetry/telemetry_test.go
This PR extends the collected telemetry data in the following way:
* Detect additional common CI/CD platforms beyond Gitlab and Github
* Detect the CI/CD repo/project owner
* Send more TMC-related data if available (org and user id)
```
yes, the telemetry documentation has to be updated with the newly collected data
```
> chore: extend telemetry data

- ci/_test_mock.tf
- ci/ci.go
- ci/ci_test.go
- ci/doc.go
- ci/stack.tm.hcl
- cmd/terramate/cli/cli.go
- cmd/terramate/cli/project.go
- cmd/terramate/cli/telemetry/record.go
- cmd/terramate/cli/telemetry/record_test.go
- cmd/terramate/cli/telemetry/telemetry.go
- cmd/terramate/cli/telemetry/telemetry_test.go
Refactor needed in upcoming Bitbucket CI/CD support.
none
```
no
```
> refactor: move CI detection to separate package to be reused.

- cloud/types.go
- cmd/terramate/cli/cloud.go
Sync the actor id of CI run.
none
```
no
```
> chore: sync actor id for github and gitlab.

- cmd/terramate/cli/cloud.go
My BB token expired and the error message was not helpful...
none
```
no
```
> chore: improve bitbucket error message.

- cloud/cloud.go
- cloud/cloud_test.go
The cloud SDK at the moment only supports `application/json` payloads but other products makes use of `text/plain` content type.
none
- not used in the CLI.
```
no
```
> chore: refactor cloud SDK to use text/plain for bytes payload.

- cloud/cloud.go
- cloud/testserver/cloudstore/store.go
- cloud/testserver/cloudstore/store_test.go
- cloud/testserver/router.go
- cloud/testserver/store.go
- cloud/types.go
Improve the cloud sdk package adding client methods for CRUD operations in the `/v1/store` endpoint and testserver handlers for e2e tests.
none
This is needed for implementation and tests of the provider.
```
no
```
> chore: implement /v1/store sdk methods and testserver handlers.

- cloud/cloud.go
- cloud/testserver/cloudstore/store.go
- cloud/testserver/router.go
- cloud/testserver/store.go
Add SDK client method for lookup of store outputs.
none
```
no
```
> chore: add SDK client method for lookup of store outputs.

- .github/workflows/benchmark.yml
- .github/workflows/ci-experimental.yml
- .github/workflows/ci-sync-deployment.yml
- .github/workflows/ci-sync-preview.yml
- .tmtriggers/cloud/changed-a9fe0083-ed01-4ee7-b407-b367413071d1.tm.hcl
Use same Go from go.mod in tests.
none
```
no
```
> chore: install Go from go.mod in GHA workflows

- config/assert.go
- config/eval.go
- config/script.go
- config/sharing_backend.go
Small change needed for components feature.
none
```
no
```
> change: export config evaluators.

- config/config.go
Small issue introduced by #2109.
Subparsers are not initialized using the root hcl options, which leads to some files not recognizing specific blocks.
none
```
no
```
> fix(config): sub-parsers not using root hcl options.

- .github/workflows/interop-tests.yml
Make the interop tests run when .tm and .tm.hcl files change.
none
```
no
```
> chore(gha): make interop tests run on TM files change.

- e2etests/core/change_detection_test.go
Add test to ensure that Terramate detects changes in a hidden directoty of a stack.
none
```
no
```
> chore: add test for changes in hidden dir of a stack.

- tg/tg_module_bench_test.go
- tg/tg_module_test.go
Add benchmark to Terragrunt module discovery.
none
```
no
```
> test: add benchmark for Terragrunt module discovery.

- cloudsync/metadata.go
Modify Gitlab MR resolution logic for cloud metadata sync to identify the head commit using the `CI_MERGE_REQUEST_SOURCE_BRANCH_SHA` variable when it is available in the environment. Motivation is outlined in the linked issue.
Fixes #2158
Unable to find existing unit tests but I've verified this using a custom build.
Yes, allows a Gitlab user to inform internal MR resolution logic for cloud metadata syncing using environment variables.
> feat: support cloud preview from gitlab merged results pipelines

- cloud/api/resources/resources.go
- cloudsync/metadata.go
This PR synchronises the server host for Gitlab CI/CD and the server URL for GitHub actions to
Terramate Cloud to give better support to self hosted platforms.
```
no
```
> feat: Sync CI/CD server to TMC for GitHub and Gitlab platforms

- go.mod
- go.sum
To fix CVE-2025-58058
```
no
```
> chore: Upgrade github.com/ulikunitz/xz to v0.5.15
