generate.go
Now the error looks like this:
```
2021/12/13 19:26:59 failed to generate code: stack "/tmp/lala/stack": parsing config: HCL syntax error: /tmp/lala/stack/terramate.tm.hcl:3,3-7: Argument or block definition required; An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the argument value.
```
It has stack info/less internal info.
=> chore: improve error message on code generation

README.md
When installing things from @main it seems that Go proxy introduces some caching/staleness, we were not able to get the latest code until we disabled it (me and @mariux ). It didn't seem to be a caching issue, I cleaned the cache with `go clean` and also deleted all local versions of the packages, it was still downloading an old version of the package from the proxy server.
=> docs: add install improvements

metadata_test.go, stack/loader.go
This causes some issues as discussed here: https://mineirosio.slack.com/archives/C02GFAAAKPT/p1640026231072900
Also is breaking global config testing since we can have a terramate HCL file with just globals inside (no terramate block) and that should work.
=> fix: dont fail stack list if terramate block is absent

cmd/terramate/cli/cli_list_test.go, config/config.go, generate.go, hcl/hcl.go, hcl/hcl_test.go, stack/loader.go
Now terramate{} is no longer required on stacks for them to be detected as stacks, only "stack{}".
=> feat: make terramate blocks optional on stacks

globals_test.go, test/hclwrite/hclwrite.go
The idea is to have something that can help avoid all the HCL raw strings we have today. It would need some tests for the builder + support to nested blocks (and probably a lot of improvements, it is quite hacky right now), seems doable but here I focused only on extracting what is used today on the globals test. Not sure this is a good idea, so OK if we decide to just drop this.
=> refactor: extract test.hclwrite

generate/generate.go, metadata.go
On generation we are listing stacks twice unnecessarily (we can just use the metadata).
=> chore: remove duplicated stack listing

cmd/terramate/cli/cli.go, cmd/terramate/cli/stacks_globals_test.go, generate/generate.go, globals.go, hcl/formatter.go, hcl/formatter_test.go
Implement the command:
```
terramate stacks globals
```
That will list all globals defined per stack. A quick example:
```sh
#!/bin/bash
set -o errexit
set -o nounset
terramate {
config {
}
}
EOM
mkdir -p stacks/stack-1
mkdir -p stacks/stack-2
terramate init stacks/stack-1
terramate init stacks/stack-2
echo "terramate list"
echo
terramate list
echo
cat > stacks/terramate.tm.hcl <<- EOM
globals {
testing = "test value"
object = {
name = "hello"
data = "world"
}
}
EOM
echo "terramate stacks globals"
terramate stacks globals
echo
```
=> feat: terramate stacks globals

export_as_locals.go, export_as_locals_test.go, globals.go, globals_test.go, hcl/hcl.go, test/sandbox/sandbox.go
Includes the core logic but no code generation, which will be done in a different PR. It is very similar to globals, but evaluation is simpler, so there is no attempt to extract duplication here yet, maybe in a future PR.
The spec: https://github.com/mineiros-io/terramate/blob/main/docs/locals-generation.md
=> feat: add load of export_as_locals

cmd/terramate/cli/cli_list_test.go
Missing fix on tests for "stacks init" instead of just "init"
=> fix: tests broken missing stacks on init

cmd/terramate/cli/stacks_globals_test.go, globals_test.go, test/hclwrite/hclwrite.go, test/hclwrite/hclwrite_test.go
This should make it possible to avoid the raw multiline strings for HCL stuff on testing, to make it look even nicer we can have something like:
```go
terramate := func(builders ...hclwrite.BlockBuilder) *hclwrite.Block {
return hclwrite.BuildBlock("terramate", builders...)
}
```
And then code building terramate blocks would look like:
```go
terramate(
str("required_version", "etc")
)
```
Not sure if this makes sense and I was kinda rushing to get something that would work, so review with care =P.
=> testing: add subblocks/hcl to hclwrite

globals.go, hcl/eval/eval.go
- detect unknown namespaces
- detect unknown variables in global namespace
- fix evaluation order
- detect global variables that could not be evaluated (cycles)
- set new context in each loop execution
=> fix: evaluate only globals already known

globals_test.go, go.mod, go.sum, test/hclwrite/hclwrite.go, test/hclwrite/hclwrite_test.go
Adding some tests to cover the fix for try() usage, it was failing before but after I merged the fix it started to work, so it seems to cover the fix reasonably well.
=> test: add some tests on globals eval with try()

cmd/terramate/cli/cli_order_test.go, cmd/terramate/cli/cli_run_test.go, cmd/terramate/cli/cli_stacks_init_test.go, cmd/terramate/cli/cli_stacks_list_test.go, cmd/terramate/cli/cli_test.go, cmd/terramate/cli/generate_test.go, cmd/terramate/cli/stacks_globals_test.go
Already working on isolating them better :-).
=> tests: skip cli tests for now

cmd/terramate/cli/loglevel_test.go, dag/dag_test.go, generate/generate_test.go, git/git_test.go, hcl/hcl_test.go, loglevel_test.go
For now it is disabled, someone can change it to debug if required but usually just the error message is enough to help (at least for me). The default is tracing, so there is so much output when a test fails that it is hard to check the error message itself.
=> tests: remove logging on tests output

cmd/terramate/cli/cli_run_test.go, cmd/terramate/cli/cli_runner_test.go, cmd/terramate/cli/cli_test.go
this should fix all tests in #139 @kassianh
=> fix: ignore stdout/stderr in tests when not set

cmd/terramate/cli/cli.go, cmd/terramate/cli/cli_run_test.go, cmd/terramate/cli/cli_runner_test.go, cmd/terramate/cli/cli_test.go, config/config.go, dag/dag.go, exported_locals.go, generate/generate.go, git/git.go, globals.go, hcl/eval/eval.go, hcl/formatter.go, hcl/hcl.go, hcl/printer.go, init.go, list.go, manager.go, metadata.go, order.go, project/project.go, run.go, stack/loader.go, version.go
Logging is done for any action or decision.
- Imperative statements are used for logging actions, simple statements for decisions
- Logging is done immediately before the action occurs
- Logging is done AFTER the decision has been made
- Eg: In an if statement make log directly after entering saying what has happened
- Simple statement - non-imperative. Eg: 'Changed' flag was set
- Not all fields are required
- Format is: 
- level - trace, debug
- time - Unix or RC3339
- stack (optional) - Path of stack
- action - Name of function where the action is found. With `()` to improve readibility
- fileContext (optional) - Absolute path of file if reading a file
- configFile (optional) - Config file associated with action
- configDir (optional) - Config directory if relevant
- workingDirectory …
=> Continue adding logging

manager.go
The root cause was stacks listed twice and the incorrect one was missing the changed flag, so the run-order put them in a map, randomly overwriting the entry, so in the end stacks could have a changed flag or not, so the run-order was broken.
It's a bit hard to reproduce because it only happens when a stack detected as changed also had a module that changed, so I'm going to provide a testcase later this week.
=> fix: stacks listed twice

manager.go, stack/stack.go
This affects run-order of changed stacks due to module changes.
=> fix: explicitly mark as changed stacks that changed due to module changes

cmd/terramate/cli/cli.go, docs/metadata.md, globals_test.go, hcl/hcl.go, hcl/hcl_test.go, hcl/printer.go, metadata.go, metadata_test.go, stack/stack.go, test/sandbox/sandbox.go
Adds possibility of having a description for the stack:
```hcl
stack {
description =  "some description"
}
```
The description shows when listing stack metadata + it can be used on globals or anywhere else that terramate.path and terramate.name can be used (let me know if it doesn't make sense). The default value for the description is empty, if none is defined.
To kick the tires:
```sh
#!/bin/bash
set -o errexit
set -o nounset
terramate {
config {
}
}
EOM
mkdir -p stack
terramate stacks init stack
echo
echo "listing metadata"
echo
terramate metadata
echo
echo "adding description to stack"
cat > stack/terramate.tm.hcl <<- EOM
stack {
description = "the stack description"
}
EOM
echo
echo "listing metadata"
echo
terramate …
```
=> feat: add stack description

.github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, .goreleaser.yaml, Makefile
Im going for this workflow:
* Create PR to change version from -dev to final one, like 0.0.9
* Reviewed/merged the PR
* Run locally on main: `make release/tag` it will automatically use the VERSION file (also used by the code itself)
* Release workflow is triggered by tag creation + goreleaser does it magic
It also generates the changelog automatically. For homebrew support it is a little more involved, maybe we can do it later, but at least for now we should get darwin binaries + linux/etc.
Not married with this particular workflow/no strong opinions, so feel free to suggest alternatives :-)
=> chore: add release automation

cmd/terramate/cli/cli.go, generate/generate.go, generate/generate_check_test.go, generate/generate_hcl_test.go, generate/generate_test.go, stack/stack.go, test/sandbox/sandbox.go
Now terramate generate should work with -C / PWD, so you can generate code only for a subset of stacks. Also removed some checks that were redundant (for root/wd/etc) and minor improvements on test error messages/duplication etc.
Example script:
```sh
#!/bin/bash
set -o nounset
terramate {
config {
}
}
EOM
mkdir -p stacks/stack-{1,2,3}
terramate stacks init stacks/stack-{1,2,3}
cat > stacks/stack-1/terramate.tm.hcl <<- EOM
stack {}
export_as_locals {
path = terramate.path
}
EOM
cat > stacks/stack-2/terramate.tm.hcl <<- EOM
stack {}
export_as_locals {
path = terramate.path
}
EOM
cat > stacks/stack-3/terramate.tm.hcl <<- EOM
stack {}
export_as_locals {
path = terramate.path
}
EOM
echo "initial tree"
tree
echo "generating …
```
=> fix: terramate generate only works from project root dir

cmd/terramate/e2etests/general_test.go, cmd/terramate/e2etests/loglevel_test.go, cmd/terramate/e2etests/main_test.go, cmd/terramate/e2etests/metadata_test.go, cmd/terramate/e2etests/order_test.go, cmd/terramate/e2etests/run_test.go, cmd/terramate/e2etests/runner_test.go, cmd/terramate/e2etests/stacks_globals_test.go, cmd/terramate/e2etests/stacks_init_test.go, cmd/terramate/e2etests/stacks_list_test.go
As we are moving away from the previous cli package/cli function testing to full e2e the idea is to make this more explicit (+ we are thinking on merging code on main anyway, so the cli package may not exist soon). Not so sure about the name TBH. Maybe just "tests" and the e2e could be implicit, or just e2e and the testing part is implicit =P.
=> refactor: move e2e tests to specific package

test/sandbox/sandbox.go
Some objects on the sandbox were being handled as pointers but they seem like all the other objects, immutable/copiable. Also the method receivers are always values (because the objects are immutable). So I went with migrating to value so it is consitent/makes sense, or else it felt like we are being random about when it is pointer or value =P (I personally like immutability and guaranteeing that by copying, and the structs are quite small). But not a strong opinion, would also be OK with all pointers, but in this case it seems cool to make it explicit that no mutation is ever happening.
=> refactor: use values instead of pointers on sandbox

git/git.go
The current implementation make sit easy to inherit env from parent process, making easy for changes on environment to change
behavior (we already have problems with git hook env leaking to tests and breaking them). A design that makes sharing explicit seems more proper here.
=> chore: improve git wrapper isolation

cmd/terramate/cli/cli.go
On some CI envs we can't get the branch name easily, not sure if we really need them TBH but since we want to get this working ASAP I tried to keep the behavior the same when we have the branch name and then on CI the check won't be performed for now. With more time we can improve/review the overall git checks.
=> fix: avoid aborting when we cant get branch name

cmd/terramate/cli/cli.go
Now logging done before configuring the log library will have the same default level/format as the ones configured for the cli options. Now we get this:
```
terramate wrong
2022-02-07T18:54:57+01:00 FTL failed to parse cli args: [wrong] error="unexpected argument wrong" action=newCli()
```
Instead of JSON (which is not the default).
=> fix: use default logging before parsing cli args

generate/generate.go, generate/generate_check_test.go, generate/generate_hcl_test.go
The following snippet should work, but before this fix it doesn't:
```sh
#!/bin/bash
set -o nounset
set -o errexit
terramate {
config {
}
}
EOM
mkdir -p stacks/stack-{1,2}
terramate stacks init stacks/stack-{1,2}
cat > stacks/terramate.tm.hcl <<- EOM
generate_hcl "empty.tf" {}
EOM
terramate run -- echo hi
```
In this scenario there is no way to solve the problem, calling terramate generate won't generate any code and yet the outdated code detection keeps detecting the project as outdated. This PRs fixes this so detection properly ignores when the generated code is empty (empty block) + file does not exist on fs (it shouldn't). 
There is less testing on export_as_locals and backend config because we are converging to …
=> fix: outdated code detection wont ignore empty generate_hcl

generate/generate.go, generate/generate_conflicts_test.go, generate/generate_hcl_test.go, generate/generate_test.go, hcl/hcl.go, hcl/hcl_test.go, test/sandbox/sandbox.go
Now this:
```sh
#!/bin/bash
set -o nounset
set -o errexit
terramate {
config {
}
}
EOM
mkdir -p stacks/stack
terramate stacks init stacks/stack
cat > stacks/terramate.tm.hcl <<- EOM
terramate {
config {
generate {
locals_filename = "file.tf"
}
}
}
generate_hcl "file.tf" {
block {}
}
export_as_locals {
something = "hi"
}
EOM
```
Will fail like this:
```
2022-02-08T16:11:25+01:00 FTL generating code. error="failed to generate code: conflicting config detected: two configurations produce same file \"file.tf\""
```
Instead of overwriting each other. The error message can be improved on the future with information about the origin of the config.
=> fix: terramate generate: different code gen strategies with same config filename overwrite each other

generate/generate.go, generate/generate_check_test.go
Right now when a config is removed, the file left there is not detected as outdated, since we only check if code matches with what is defined on the current configs. Now we list all generated code and check if any of the generated code existing on the filesystem has no config matching with it, making it outdated too.
=> fix: outdated detection: detect stale files from previous configurations

docs/config.md
We wont rely on a single `terramate.tm.hcl` anymore. Also removed some redundant info on the config docs.
=> docs: update docs on configuration allowing multiple files

docs/hcl-generation.md, generate/generate_check_test.go, generate/generate_conflicts_test.go, generate/generate_hcl_test.go, generate/generate_hclwrite_utils_test.go, generate/genhcl/genhcl.go, generate/genhcl/genhcl_test.go
This PRs changes the behavior of code generation using `generate_hcl`. Instead of generating code by doing:
```hcl
generate_hcl {
terraform {
}
}
```
All generated HCL must be inside the `content` block, like this:
```hcl
generate_hcl {
content {
terraform {
}
}
}
```
A full example:
```sh
#!/bin/bash
set -o nounset
set -o errexit
terramate {
config {
}
}
EOM
mkdir -p stacks/stack-{1,2}
terramate stacks init stacks/stack-{1,2}
cat > stacks/terramate.tm.hcl <<- EOM
globals {
tf_version = "1.1.3"
gh_owner = "the-awesome-mineiros"
gh_provider_version = "4.19.1"
}
generate_hcl "provider.tf" {
content {
provider "github" {
owner = global.gh_owner
}
terraform {
required_providers {
github = {
source  = "integrations/github" …
```
=> feat: add content block on generate_hcl 

globals.go, globals_test.go, hcl/hcl.go
This PR allows globals to be defined on multiple files. We still lack suppor to export_as_locals and generate_hcl.
Example:
```sh
#!/bin/bash
set -o errexit
set -o nounset
terramate {
config {
}
}
EOM
mkdir -p stacks/stack-1
mkdir -p stacks/stack-2
terramate stacks init stacks/stack-1
terramate stacks init stacks/stack-2
echo "terramate list"
echo
terramate stacks list
echo
cat > stacks/globals1.tm.hcl <<- EOM
globals {
testing = "test value"
}
EOM
cat > stacks/globals2.tm <<- EOM
globals {
object = {
name = "hello"
data = "world"
}
}
EOM
echo "terramate stacks globals"
terramate stacks globals
```
=> feat: add multiple config files support to globals

cmd/terramate/cli/cli.go, hcl/hcl.go, hcl/hcl_test.go
It doesn't make much sense and conflicts with the `config.git.default_remote` and `config.git.default_branch` options.
=> refactor: removes base_ref git option

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/run_test.go, stack/stack.go
Since we use the Stringer the easiest way is to change the stack string representation. Changed to an explicit name on `plan run-order` to avoid changing behavior there (it depended on the string representation of stacks).
=> chore: improve outputs in logs to show stack path not name

generate/generate_hcl_test.go, generate/generate_hclwrite_utils_test.go, generate/generate_locals_test.go, generate/genhcl/genhcl_test.go, globals_test.go, test/hclwrite/hclwrite.go, test/hclwrite/hclwrite_test.go
Here we:
* Simplify some things on the implementation
* Enforce that the document is generated the same way it was built (no implicit/automatic ordering)
* Allow creation of hcl document with only attributes on root (no blocks)
* Added missing test for genhcl (attributes on root)
=> chore: improve test hclwrite

exported_locals_test.go, generate/generate_locals_test.go, globals_test.go, hcl/eval/eval.go
Both globals and export_as_locals now only evaluated functions when prefixed with tm_.
=> feat: add tm_ prefix on funcs for globals/export_as_locals

.github/workflows/ci.yml
When merging a branch onto another branch the make test/ci may fail and the way it is done today it cancels running tests on other platforms. So it seemed good to extract this check on its own job, decoupled from the usual build/tests that are more isolated (it is also misleading, it seems like basic building/testing is broken, but it is not, and the CI testing thing is more brittle).
Example: https://github.com/mineiros-io/terramate/pull/246
=> chore: extract GH integration test on its own job

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/version_check_test.go
Now we have terramate --version  on top of terramate version, both should work. Code is a little odd because kong parsing fails if there is no subcommand (unless for --help...which I suppose it is handled internally by kong).
=> chore: add support to --version

globals_test.go
These help us map some funny behavior on the string interpolation on hcl eval, which then helps on more advanced features like partial eval.
=> tests: add new globals tests

globals_test.go
Confirming that bools behave like numbers, will fix the tests on the partial eval work.
=> tests: check bool interpolation behavior

generate/genhcl/genhcl.go, generate/genhcl/genhcl_test.go
Since we are testing the partial eval logic through genhcl I had to chain errors from eval there (could review which layer of errors to use on tests later, right now just did the smallest change)
=> tests: add some tests related to for + fix err chaining on genhcl

generate/genhcl/genhcl_test.go
Since we were discussing if something like:
```hcl
a = b
```
would work, at least on the parsing level it is.
=> test: add simple attr test

generate/genhcl/genhcl.go, globals.go, hcl/hcl.go
For now only added origin info like genhcl + improved the error logging. The report from code generation itself still is quite vague, but at least the error log entries should help.
before we had:
```
2022-03-21T16:12:12+01:00 INF project root config has no required_version, skipping version check action=cli.checkVersion() root=/home/katz/workspace/terramate-blueprint-iac-github
2022-03-21T16:12:12+01:00 WRN unresolved global action=eval() name=user_map stack=/stacks/organization/members
2022-03-21T16:12:12+01:00 WRN unresolved global action=eval() name=_members_team stack=/stacks/organization/teams/departments
2022-03-21T16:12:12+01:00 WRN unresolved global action=eval() name=_members_all stack=/stacks/organization/teams/departments
2022-03-21T16:12:12+01:00 WRN …
```
=> chore: improve error message on global evals

Makefile
So it works properly with Go 1.18
=> chore: update golang ci lint

run/order.go
Before the error was missing which stack had the wrong configuration:
```
$ terramate run --dry-run -- ls
2022-03-29T22:50:24+01:00 FTL failed to plan execution error="parsing config files: reading dir to load config files: open /home/i4k/src/mineiros/tm-example/stack-A: no such file or directory"
```
Now:
```
$ terramate run --dry-run -- ls
2022-03-29T22:57:23+01:00 FTL failed to plan execution error="failed to load the \"before\" stacks of the stack \"/stack-c\": parsing config files: reading dir to load config files: open /home/i4k/src/mineiros/tm-example/stack-A: no such file or directory"
```
The error message is still not ideal, any help is appreciated.
=> fix: improve error message of run order

cmd/terramate/cli/cli.go
Currently it allows `terramate list --why` but then it shows an empty reason...
```
apps/a - 
apps/b - 
apps/c - 
apps/d - 
```
=> fix: disallow the use of --why without --changed

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/run_test.go, run/order.go
When running:
```
terramate -C <dir>
```
Stacks that are outside the subdir tree/-C `dir` are being selected on `terramate run`.
The idea of the PR is to ensure stacks returned by the DAG building process exists on the selected stacks passed to the order function, so it is responsibility of the run.Sort function caller to pass a properly filtered set of stacks, which is what is done today already unless I missed something.
=> fix: after/before selecting stacks outside cwd/-C

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/run_test.go, stack/stack.go
Adds the option `--reverse` to `terramate run`. So running:
```
terramate run --reverse
```
Will give the reversed order of whatever ordering defined for the given stack list
=> feat: add --reverse on run

errors/error.go, errors/error_test.go
So we can focus on implementing just the Is method specific for each error type, no need to rollout our own Is implementation/recursion/unwrapping logic. Will make it easier for us to add the error list type.
=> refactor: use Go's unwrap/Is protocol

errors/error.go, errors/error_test.go, errors/list.go, errors/list_test.go
Add new errors.List type + constructor errors.L. Should be enough to represent errors list without giving up using the error interface. Usage will be:
```go
errs := errors.L()
errs.Append(something.Do())
return errs.AsError()
```
It will automatically ignore nil error (sucesses) and if no errors are present errs.AsError() returns nil. Using errors.Is will also work by matching with all errors inside the list, any match is enough for success.
To inspect all errors contained on the LSP server there is a method List.Errors that returns all errors that are of the type Error or have an Error wrapped inside them, so we can use it like this:
```go
for _, err := range errs.Errors() {
// err type is errors.Error, so we can just acccess information there
}
```
Not in love with any of the names I …
=> chore: add errors.List

errors/error.go, errors/error_test.go, errors/list.go, errors/list_test.go
So it is easier to build error list from operations that produce a diagnostic from HCL (which is also a list) or even our own list. It seems that the most desireable behavior is flattening, but I could be wong.
=> chore: flatten diagnostics + error list when appending on an error list

cmd/terramate/cli/cli.go, generate/generate.go, generate/genhcl/genhcl.go, stack/globals.go, stack/globals_test.go, test/sandbox/sandbox.go
We already had issues with cyclic dependencies multiple times because globals are on the main terramate pkg. I think it makes sense for it to be on the stack, so we have stack.Metadata + stack.Globals, seems to map the domain well. We can improve things more on the future, I focused only on moving it to the package.
=> refactor: move globals to stack pkg

cmd/terramate/cli/project.go, cmd/terramate/e2etests/general_test.go
The git check for the outdated default branch wasn't properly working but tests were passing because the Manager did them correctly.
Fixed the git.IsDefaultBranch() and project.defaultBaseRef.
=> fix: git check for outdated main

generate/genfile/genfile_test.go, generate/genhcl/genhcl_test.go, hcl/hcl.go
Currently code generation will read dotfiles, but those should be ignored.
=> fix: code generation does't ignore dotfiles

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/general_test.go, cmd/terramate/e2etests/run_test.go
This PR also fixes `terramate run` so it always checks if the local default branch is updated with remote (even without --changed). Given that `terramate run` always checks if the remote is updated, for scenarios where that is not wanted we introduce `--disable-check-git-remote`. So in a scenario where `terramate run` is failing on the git check running `terramate run --disable-check-git-remote` will work.
=> feat: add disable-check-git-remote

test/errors/errors.go
Currently when we call `errors.AssertIsErrors(err, nil)` if the err is not nil it will pass, which is wrong since passing nil/empty target error list indicates that you want no errors at all (just as passing nil on errors.Is() also fails unless err is also nil).
=> fix: errors.AssertIsErrors should check if no err is wanted

README.md
Adds instructions on how to install Terramate via Homebrew to the README.
=> Add homebrew installation to readme

generate/genhcl/genhcl.go, hcl/eval/eval.go, hcl/hcl.go, stack/eval.go, stack/globals.go
Thinking on ways to isolate further the evaluation context so we can easily change the metadata definition in a single place and be confident that there will be no inconsistencies (like some part of the code manipulating the lower level eval ctx directly). The idea is to do it all through the stack.EvalCtx everywhere, since evaluation so far is always done regarding a stack anyway. The only one using more low level hcl eval contexts will be the stack.EvalCtx itself.
Also worked on isolating as much as possible decisions like "what is the name of the namespaces". Im not entirely sure this is a good idea, prone to just dropping it if it is stupid or if we have a better idea :-).
=> refactor: isolate evaluation context better

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/exp_metadata_test.go, docs/sharing-data.md, generate/genfile/genfile_test.go, generate/genhcl/genhcl_test.go, hcl/eval/eval.go, stack/eval.go, stack/globals_test.go
Moving stack metadata to "terramate.stack". The old metadata is being kept for now to avoid breaking anything. New metadata:
* terramate.name -> terramate.stack.name
* terramate.description -> terramate.stack.description
* terramate.path -> terramate.stack.path.absolute
New metadata will be added on a future PR.
=> feat: move stack metadata related to terramate.stack

generate/genfile/genfile.go, generate/genhcl/genhcl.go, stack/eval.go, stack/globals.go
The stack eval creation doesn't need to return an error anymore, it is a leftover from a previous refactor I did, sorry I missed this.
=> refactor: remove error on stack eval ctx creation

docs/orchestration.md
Initial spec for the `export_env` feature. We could use different names, maybe `run_env` or `exec_env` would be more explicit ? Go crazy on name suggestions =P
=> chore: add initial spec for terramate.config.run.env

hcl/hcl.go, hcl/hcl_test.go
The invalid config below:
```
stack {
wants = 
}
```
generates an error when calling the hashicorp parse.ParseHCL() function but it populate its `parse.Files()` with an invalid data structure for the file's body... for the case above, it creates an attribute with name "wants" and value of type cty.DynamicValue that's not even nullable (attrVar.IsNull() returns `false`)...
So we cannot have syntax error + schema errors because they do not provide partial correct nodes.
The fix was making terramate check the schema only for the files successfully parsed (valid HCL).
I got this issue while experimenting with the VSCode extension. The Language Server crashed with log below:
```
attribute=wants stack=
2022-06-14T13:09:43+01:00 TRC Iterate over values. action=assignSet()
panic: can't use …
```
=> fix: avoid checking the schema in case of syntax errors

generate/genfile/genfile.go, generate/genhcl/genhcl.go
If the stack is in the filesystem / then the generation loops indefinitely.
Got this while testing terramate in the browser using an in-memory file system.
Do not recurse if `filepath.Dir(path)` yields the same `path`.
=> fix: infinite loop in generate if the stack is in /

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/exp_globals_test.go, cmd/terramate/e2etests/list_git_test.go, cmd/terramate/e2etests/list_nongit_test.go, cmd/terramate/e2etests/list_test.go, cmd/terramate/e2etests/run_test.go, test/hcl.go, test/sandbox/sandbox.go
The checks for git were running for non-git environments.
A guard was added to checkGit() and the tests were reused for git/nongit envs so we catch those related issues.
Closes #402
=> fix: checkGit() called for non-git repos

.github/workflows/ci.yml, .github/workflows/release.yml, .goreleaser.yaml, Makefile, cmd/terramate/e2etests/main_test.go
Not all targets targets support static binaries (like macos), but for linux now we have a static build, both on make + release + e2e testing.
To check the release binaries you can run:
```
make release/dry-run
```
And check inside the dist dir:
```
file dist/terramate_*/terramate
dist/terramate_darwin_amd64/terramate: Mach-O 64-bit x86_64 executable
dist/terramate_darwin_arm64/terramate: Mach-O 64-bit arm64 executable, flags:<|DYLDLINK|PIE>
dist/terramate_linux_386/terramate:    ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, Go BuildID=Z0uQDQNinOYf7RfT23LA/6FMEyC8F2_39TyAJx8rp/Hzi3ovxvism8APu_csVO/V_GfsOkddGoQSay72BYt, not stripped
dist/terramate_linux_amd64/terramate:  ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go …
```
=> chore: build terramate statically whenever possible

cmd/terramate/cli/cli.go, run/exec.go
Currently Terramate will exit as soon as it gets an interruption signal, not waiting for the child process to exit. This PR introduces waiting for the child process to finish before exiting Terramate + It will force kill the child process after receiving 3 interruption signals.
Closes #412
=> fix: handle interruption signals when on run

generate/genfile/genfile.go, generate/genhcl/genhcl.go, hcl/hcl.go, run/env.go, run/env_test.go, stack/eval.go, stack/globals.go, stack/stack.go, test/sandbox/sandbox.go
This will be used on the next PR to implement the run with env feature. When we are iterating the ordered stacks this function will be used to load the stack env so we can pass it to the created command.
=> chore: add run.Env that loads a stack run environment

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/cmd/test/test.go, cmd/terramate/e2etests/exp_globals_test.go, cmd/terramate/e2etests/hclwrite_utils.go, cmd/terramate/e2etests/list_git_test.go, cmd/terramate/e2etests/main_test.go, cmd/terramate/e2etests/run_test.go, cmd/terramate/e2etests/runner_test.go, cmd/terramate/e2etests/version_check_test.go, run/env.go, run/env_test.go, run/exec.go
Introduces support to manipulating the environment variables when running commands with `terramate run` as specified [here](https://github.com/mineiros-io/terramate/blob/main/docs/project-config.md#terramateconfigrunenv). 
It also introduces a `terramate experimental run-env` that should help debugging env definitions for stacks (only shows env manipulated directly, not like `env`).
Example:
```sh
#!/bin/bash
set -o errexit
set -o nounset
workdir=$(mktemp -d)
echo "workdir: ${workdir}"
cat >terramate.tm <<EOL
terramate {
config {
run {
env {
NEW_ENV_VAR="test"
HOME="newhome"
}
}
}
}
EOL
mkdir stack
terramate experimental init-stack stack
echo
terramate experimental run-env
echo
terramate run -- env
```
=> feat: add env support on terramate run

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/create_test.go, stack/create.go, stack/create_test.go, test/stack.go
Introduces the `terramate create` command on the CLI. Example:
```sh
#!/bin/bash
set -o errexit
set -o nounset
workdir=$(mktemp -d)
cd "${workdir}" || exit
terramate {
config {
}
}
EOM
terramate create stack 
cat stack/stack.tm.hcl
echo
mkdir common
touch common/file1.tm.hcl
touch common/file2.tm.hcl
mkdir stacks
cd stacks
terramate create stack-1 \
--name "stack name" \
--description "stack description" \
--id "stack-id" \
--import "/common/file1.tm.hcl" \
--import "/common/file2.tm.hcl"
cat stack-1/stack.tm.hcl
echo
cd ..
echo "final structure"
tree
```
=> feat: add terramate create <path>

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/create_test.go, stack/create.go, stack/create_test.go
This will make it easier to use the new stack.Create function on tests instead of the old Init one, since for a lot of scenarios the default definitions are unexpected. Since these particular defaults seems to be CLI specific I moved them there.
=> refactor: move stack create default handling to cli pkg

cmd/terramate/cli/cli.go, cmd/terramate/cli/project.go, cmd/terramate/e2etests/run_test.go, hcl/hcl.go
Just as we can pass flags:
- `--disable-check-git-untracked`
- `--disable-check-git-uncommitted`
- `--disable-check-git-remote`
- `--disable-check-gen-code`
We now can have them as project configs:
```hcl
terramate {
config {
git {
check_untracked   = true
check_uncommitted = true
check_remote      = true
}
run {
check_gen_code = true
}
}
}
```
And environment variables:
- `TM_DISABLE_CHECK_GIT_UNTRACKED`
- `TM_DISABLE_CHECK_GIT_UNCOMITTED`
- `TM_DISABLE_CHECK_GIT_REMOTE`
- `TM_DISABLE_CHECK_GEN_CODE`
A env variable is considered `true` if set and not `0` nor `false`.
Precedence:
- command line
- ENV (needs to be actually set to be considered) 
- config
- built-in default
Docs will be added on a following PR.
=> feat: add git checks config through cfg and env

hcl/hcl.go, hcl/hcl_test.go, stack/globals.go, test/stack.go
As I searched for something that would help me implement the stack clone feature I found some opportunities to make things clearer, at least to me (always debatable if it is better of course).
Renamed a few methods to make things more clear. I think it makes sense that a Parse method only parses the HCL itself, without any Terramate specific schema validations, and then a ParseConfig one is a more specific version that will do schema validation and return a more high level Terramate configuration (minimal parse was confusing to me, but that is debatable).
Also make a few other fields more explicit on their names and added a test for the ParseBodies method, I think it will be quite useful on the stack clone so I just double checked it does what I need.
=> refactor: renaming and adding new test on hcl parser

stack/clone.go, stack/clone_test.go
The stack ID can be defined with expressions like `("id")` which evaluates to a valid stack ID but right now we don't handle parsing when cloning since parsing all possibilities would be quite some work, since we can't manipulate expressions properly using the HCL library and need to reimplement parsing using tokens. Here we just check that the ID is not a simple "id" and if it is not we fail explicitely, since the current behavior is to generate an invalid stack definition.
An expression not recognized by the clone will result in an error like:
```
2022-07-18T17:10:49+02:00 FTL cloning stack error="src stack ID not supported: ID must be a simple string literal" action=cli.cloneStack() dest=stacks/cloned-stack src=stacks/stack workingDir=/tmp/tmp.EARBTYTXtX
```
Ideally we should support …
=> fix: handle explicitly complex stack ID expressions

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/create_test.go
On terramate create we want any pending code generation to already be done on the created stack.
Add a code generation step after the stack creation.
=> feat: add automatic code gen on stack create

.github/workflows/ci.yml
Remove "macos-10.15" from the CI, it started to get cancelled all the time by GHA, maybe they dropped support to it or they are going through some issues with it. We could add it back if it starts working again.
=> chore: remove mac 10.15 from CI

generate/generate.go, generate/generate_file_check_test.go, generate/generate_file_test.go, generate/generate_hcl_check_test.go, generate/generate_hcl_test.go
We want both generate_hcl and generate_file to generate empty files when content is empty, instead of the current behavior of not generating any file.
Both code generation and outdated code detection are fixed to handle empty files.
=> fix: codegen should generate empty files

cmd/terramate/e2etests/run_test.go, docs/orchestration.md, run/order.go, stack/loader.go
This PR adds support for using directories in the after/before clauses of the stack block.
This allows for a more flexible mechanism for defining stack ordering because this way users can organize similar stacks inside a common directory and use this directory as a reference in the order.
=> feat: add support for directories in the stack order

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/run_test.go
Terramate was aborting with an error when `terramate.config.git.check_remote = false` was used together with change detection (--changed).
Closes #496
=> fix: disabling check_remote breaks the change detection

hcl/hcl.go, hcl/hcl_test.go
This issue was found while updating terramate-ls dependencies: https://github.com/mineiros-io/terramate-ls/pull/13
=> fix: whenever possible the parser must not stop on errors

config/config.go
=> fix: when looking for the rootdir the import errors must be ignored

cmd/terramate/e2etests/list_test.go, hcl/hcl.go, hcl/hcl_import_test.go, hcl/hcl_stack_test.go, hcl/hcl_test.go, hcl/raw_config.go
```
$ cat stack-a/terramate.tm.hcl
stack {
name = "awesome-stack-a"
}
terramate {
}
$ terramate list
2022-08-04T02:17:37+01:00 WRN  error="/home/i4k/src/mineiros/tm-example/stack-a/terramate.tm.hcl:5,1-10: `terramate` block is only allowed at the project root directory" action=checkConflicts()
stack-a
stack-b
stack-c
```
=> fix: warn in case of unexpected terramate block

cmd/terramate/e2etests/general_test.go, config/config.go
Adding a regression test for the issue reported on #515.
The code was reverted to confirm the test is catching the same error.
We reproduced the error with an e2e test:
```
--- FAIL: TestBug515 (0.19s)
general_test.go:514: stdout mismatch: got "" != want ".\n"
general_test.go:514: stderr mismatch: got "2022-08-04T15:24:51+02:00 FTL failed to lookup project root error=\"/tmp/TestBug5152882507097/001/sandbox/stacks/stack/import.tm:3,14-31: import error: failed to create sub parser: failed to stat directory \\\"/tmp/TestBug5152882507097/001/sandbox/stacks/stack/common\\\": stat /tmp/TestBug5152882507097/001/sandbox/stacks/stack/common: no such file or directory\" action=newCli() workingDir=/home/katz/workspace/terramate/cmd/terramate/e2etests\n" != want ""
general_test.go:514: wanted[0] but …
```
=> test: add regression test for issue #515

modvendor/modvendor.go
Currently when running git clone on modvendor we are not loading any of the environment variables since by default our git instances force an empty env. 
For clone, on modvendor, we add the parent process env.
=> fix: vendor download should use env vars on git clone

generate/genhcl/genhcl_hclwrite_test.go, generate/genhcl/genhcl_test.go
Just double checking that the new variable with optional descriptions work on Terramate. It parses it and partial evaluation also works on it.
Just added the test. Here is also a quick script to see it working live:
```sh
#!/bin/bash
set -o errexit
set -o nounset
workdir="$(mktemp -d)"
terramate {
config {
}
}
EOM
cat > variable.tm.hcl <<- EOM
globals {
default = 666
}
generate_hcl "variable_optional.tf" {
content {
variable "with_optional_attribute" {
type = object({
a = string
b = optional(string)
c = optional(number, global.default)
})
}
}
}
EOM
terramate create stack
echo
echo "generated code"
cat stack/variable_optional.tf
```
=> test: generate code for variable with optionals (tf 1.3)

git/git.go, git/git_test.go, modvendor/modvendor.go, modvendor/modvendor_test.go, test/sandbox/git.go
Vendoring with commit IDs is not working.
We were using git clone --branch but that only works for branches, not specific commit IDs. Now we do a clone + checkout on the cloned repo.
```sh
#!/bin/bash
set -o errexit
set -o nounset
workdir="$(mktemp -d)"
terramate {
config {
}
}
EOM
terramate experimental vendor download github.com/mineiros-io/terramate main
terramate experimental vendor download github.com/mineiros-io/terramate c6847ea138d0008de79b6a0e1790a15c3b5524ef
terramate experimental vendor download git@github.com:mineiros-io/terramate.git v0.1.19
echo "vendor:"
tree -d -L 4 vendor
echo "checking VERSION files of each vendored repo"
cat vendor/github.com/mineiros-io/terramate/main/VERSION
cat …
```
=> fix: vendor download does not work with commit IDs

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/create_test.go, stack/create.go, stack/create_test.go, test/hcl.go
Just as we can pass a list of imported stacks on `terramate create` with `--import` we want to define after/before for the created stack using `--after` and `--before`.
Added support to after/before on core logic + CLI.
```sh
#!/bin/bash
set -o errexit
set -o nounset
workdir=$(mktemp -d)
cd "${workdir}" || exit
terramate {
config {
}
}
EOM
terramate create stack 
cat stack/stack.tm.hcl
echo
mkdir common
touch common/file1.tm.hcl
touch common/file2.tm.hcl
mkdir stacks
cd stacks
terramate create stack-1 \
--name "stack name" \
--description "stack description" \
--id "stack-id" \
--after "stack-a" \
--after "stack-b" \
--before "stack-c" \
--import "/common/file1.tm.hcl" \
--import "/common/file2.tm.hcl"
echo
echo "=== created stack config ===" …
```
=> feat: create: add --after and --before

generate/genhcl/genhcl.go, generate/genhcl/genhcl_dynamic_test.go, hcl/hcl.go
Currently using tm_dynamic with duplicated labels on the labels attribute will fail but it shouldn't.
Refactored the CopyBody from hcl to genhcl since it contains a lot of logic that is genhcl specific. We still have some parsing that could be on hcl that is now done on genhcl, so it would be better to improve this further, but at least for now it simplifies the already big hcl package.
Instead of using the assignSet function that handle a cty.Value we have a function that handles a cty.Value as a list of strings.
```sh
#!/bin/bash
set -o errexit
set -o nounset
workdir="$(mktemp -d)"
terramate {
config {
}
}
EOM
cat > test.tm.hcl <<- EOM
generate_hcl "test.tf" {
content {
tm_dynamic "resource" {
for_each = ["a"]
labels = ["a", …
```
=> fix: tm_dynamic fails with  duplicated labels

fs/copy.go
Got this issue while testing the #553 feature.
```
$ terramate experimental vendor download github.com/SebastianUA/terraform v18.15.10
2022-08-26T03:56:03Z WRN deleting temp dir inside terramate project error="open /home/i4k/src/mineiros/tm-example: too many open files"
2022-08-26T03:56:03Z WRN deleting tmp clone dir error="open /tmp: too many open files"
Vendor report:
[!] github.com/SebastianUA/terraform
reason: failed to vendor "https://github.com/SebastianUA/terraform.git" with ref "v18.15.10": copying cloned module: copying src to dest dir: copying src to dest file: opening source file: open /tmp/.tmvendor2299994787/aws/modules/api_gateway/api_gateway_deployment.tf: too many open files
```
=> fix: too many open files while vendoring huge projects

cmd/terramate/e2etests/exp_vendor_test.go, modvendor/modvendor.go, modvendor/modvendor_report.go, modvendor/modvendor_test.go, tf/mod_source_parse.go, tf/mod_source_parse_test.go
Today we fail on vendoring when there are [sub directories references](https://www.terraform.io/language/modules/sources#modules-in-package-sub-directories) on the source.
Add support to parsing the subdir and use that information when patching terraform files.
```sh
#!/bin/bash
set -o errexit
set -o nounset
workdir="$(mktemp -d)"
terramate {
config {
}
}
EOM
terramate experimental vendor download github.com/mineiros-io/terramate//hcl main
terramate experimental vendor download github.com/mineiros-io/terramate//config c6847ea138d0008de79b6a0e1790a15c3b5524ef
terramate experimental vendor download git@github.com:mineiros-io/terramate.git//modvendor v0.1.19
echo "vendor:"
tree -d -L 4 vendor
echo "checking VERSION files of each …
```
=> fix: vendor: fails on subdir references

.github/workflows/ci.yml
We had some odd issues with it in the past on GHA, the runner was hanging forever. But now it seems to be OK.
=> chore: add mac 10.15 back to CI

.github/workflows/ci.yml
macos-10.15 is being deprecated. Sorry I added it back again, I wasn't able to find this before:
https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
And apparently the best way to communicate deprecation is by making things fail inside a schedule, so people can observe the behavior of "sometimes it work, sometimes it breaks" and then realize that obviously that means the runner is being deprecated.
And the workflow is just marked as cancelled...with no information on why, kudos to GHA :laughing:
=> chore: update macos runners

fs/copy.go, fs/copy_test.go
On fs.CopyDir the dir is created as soon as the filter function returns true. But when the filtered path is a dir we should not create the dir yet since it may have no files inside it. This would cause some features, like vendoring with manifest, to create empty dirs in some scenarios.
Only create directories when there is an actual file to copy to it. Also improved the tests to catch this scenario.
=> fix: fs.CopyDir creates empty dirs

generate/generate_report.go, generate/generate_report_test.go
The `nothing-to-do` message was confusing, it's now unconfusing.
=> chore: improve generation message for up to date code

generate/generate.go, generate/generate_hcl_test.go
We are currently checking for files to cleanup on generate inside dot dirs.
Filter out dot dirs when cleaning up files.
=> chore: avoid cleanup dotdirs on generate

hcl/hcl.go
Required to make terramate-ls works on Windows again.
=> fix: project paths must not use portable path library

cmd/terramate/cli/cli.go
Improve logging of warning/fatals when we have uncommited/untracked files. We have each file logged individually to avoid long lists inside a single log message using the debug level and then a simple warn/fatal with no file information.
=> chore: improve logging for git checks

cmd/terramate/cli/cli.go, generate/generate.go, run/order.go
The idea is to log less detailed information on warn messages, leaving details to other levels like debug/trace. For info/warning/fatal I think we could drop the "action" field since it is quite specific to details of the code (private function names, etc).
=> chore: improve warning messages

go.mod, go.sum
Since we are only testing on >= 1.18.
=> chore: update go on go.mod

config/config.go, config/config_test.go, docs/config-overview.md, generate/generate.go, generate/generate_list_test.go, generate/generate_test.go
So we can add root context configurations in some directory and then import it without processing the configuration twice. This is also useful to ignore vendored content (in the future we can add .tmskip on vendored dirs).
=> feat: add .tmskip

generate/assert_test.go, generate/generate_file_check_test.go, generate/generate_file_test.go, generate/generate_hcl_check_test.go, generate/generate_hcl_test.go, generate/generate_test.go, generate/genfile/genfile_test.go, generate/genhcl/genhcl_dynamic_test.go, generate/genhcl/genhcl_partial_eval_test.go, generate/genhcl/genhcl_test.go, generate/report_test.go
Make generate/genfile/genhcl tests faster. Specially genhcl is quite slow, so tried to speed things up a little.
Sequential tests here:
```
ok      github.com/mineiros-io/terramate/generate       3.735s
ok      github.com/mineiros-io/terramate/generate/genfile       1.490s
ok      github.com/mineiros-io/terramate/generate/genhcl        13.570s
```
With Parallel:
```
ok      github.com/mineiros-io/terramate/generate       1.854s
ok      github.com/mineiros-io/terramate/generate/genfile       0.911s
ok      github.com/mineiros-io/terramate/generate/genhcl        5.307s
```
=> test:generate: run tests in parallel

config/config.go, errors/errlog/errlog.go
There was a bug on how the logger context was created, now we should get a nice fatal msg with the file origin:
```
terramate list
2022-10-18T14:50:40+02:00 FTL looking up project root: HCL syntax error: loading from /tmp/test/test: A comma is required to separate each function argument from the next. file=/tmp/test/test/stack.tm:1,14-15
```
=> chore: improve logging of errors with range

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/run_test.go
Some tests could fail depending on which env vars the host has exported. We only need PATH since we use git. This should make the tests less dependent on the env.
=> chore: avoid loading entire os.Environ on tests

errors/error.go, errors/error_test.go, generate/genhcl/genhcl.go, globals/globals.go, hcl/eval/eval.go, lets/lets.go
Improve error messages on some generate errors. Also fix a bug on the errors pkg where we were ommiting the filename from the range when the origin file is .tm.hcl.
=> chore: generate: improve lets/globals eval errs logs

errors/errlog/errlog.go, errors/error.go, errors/error_test.go, project/project.go, stack/stack.go
Running `terramate run` gave me this error messages:
```
2022-10-23T15:23:58+01:00 ERR running /stack%!(EXTRA *exec.Cmd=/usr/bin/make): exit status 2
2022-10-23T15:23:58+01:00 FTL one or more commands failed
```
The reason was that #608  broke the assumption that `stack.S` implements `errors.StackMeta`.
This line was added to ensure this doesn't happen again: https://github.com/mineiros-io/terramate/pull/662/files#diff-3255e7799f07c4f38eb7328b59a25c5a9d25b9661dcf83b1ea9a817d2bde6629R107
=> fix: stack.S doesn't implement errors.StackMeta

generate/generate.go, generate/generate_file_check_test.go, generate/generate_hcl_check_test.go
Outdated code detection was not handling multiple blocks with different conditions properly. It was working before because of details on how the blocks were ordered that were changed. Made the code be not dependent on the ordering since ordering is mostly used to test deterministically and to output results nicelly.
=> fix: outdated code detection not handling condition

.tool-versions, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/create_test.go, test/sandbox/sandbox.go
Allow `terramate create --ignore-existing` which then will not fail if the stack already exists (but won't do any changes on the stack).
=> feat: add --ignore-existing on terramate create

modvendor/modvendor.go
Specially when using the new `tm_vendor` function allowing interaction on git can be quite confusing. So by default if `GIT_TERMINAL_PROMPT` is not set we disable the prompt. Not having credentials will result in an error like:
```
terramate  experimental vendor download github.com/katcipis/test v18.15.10
Vendor report:
[!] github.com/katcipis/test
reason: failed to vendor "https://github.com/katcipis/test.git" with ref "v18.15.10": failed to exec: /usr/bin/git clone https://github.com/katcipis/test.git /tmp/.tmvendor200743037 : stderr="Cloning into '/tmp/.tmvendor200743037'...\nfatal: could not read Username for 'https://github.com': terminal prompts disabled\n", stdout=""
```
=> feat: vendor: disable git prompt

cmd/terramate/cli/cli.go
When we started sending the code generation report to a -v output we would still fail the create command if the code generation had any failures, so the command will exit with -1 but no output about what happened. This fix uses the default output level when the code generation report has any errors on it, retaining the old behavior of silently working when all is well.
Example code to check outputs:
```sh
#!/bin/bash
set -o errexit
set -o nounset
project="$(mktemp -d)"
cd "${project}"
cat > terramate.tm <<- EOM
terramate {
config {
}
}
EOM
terramate create stack-1
cat > config.tm <<- EOM
generate_hcl "test.hcl" {
content {
a = global.ohno
}
}
EOM
terramate create stack-2
```
Outputs:
```
Created stack /stack-1
Created stack /stack-2
Error on /stack-2: /tmp/tmp.JS1QNiSNVB/config.tm:3,9-20: …
```
=> fix: create report codegen error properly

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/exp_generate_test.go
The output should be more grep-able now, like this:
```
/stacks/organizations/mineiros.io/project-factory/mineiros-iac-shr/iam/terramate_generated_terraform.tf origin: /modules/github.com/mineiros-io/terramate-google-landing-zone/v0.2.0/terraform/provider.tm.hcl:22,1-54,2
/stacks/organizations/mineiros.io/project-factory/mineiros-iac-shr/service-apis/terramate_generated_backend.tf origin: /modules/github.com/mineiros-io/terramate-google-landing-zone/v0.2.0/terraform/backend.tm.hcl:8,1-27,2
/stacks/organizations/mineiros.io/project-factory/mineiros-iac-shr/iam/terramate_generated_terraform.tf origin: /modules/github.com/mineiros-io/terramate-google-landing-zone/v0.2.0/terraform/provider.tm.hcl:22,1-54,2
/stacks/organizations/mineiros.io/project-factory/mineiros-iac-shr/service-apis/terramat …
```
=> chore: improve experimental generate debug output

errors/errlog/errlog.go, errors/error.go, globals/globals.go, hcl/hcl.go
Enable panics to have a consistent kind/way to be built. So far updated only panic that already had the kind embedded directly into the message.
=> chore: add internal err sentinel for panics

generate/generate.go, generate/generate_file_test.go, generate/generate_hcl_test.go, generate/outdated_detection_test.go
When the stack is on root we are creating/deleting the file. To reproduce:
```sh
#!/bin/bash
set -o errexit
set -o nounset
terramate {
config {
}
}
EOM
cat > config.tm.hcl <<- EOM
stack {
name        = "terraform-google-service-account"
description = "github.com/mineiros-io/terraform-google-service-account"
}
generate_hcl "versions.tf" {
content {
}
}
EOM
```
Outdated detection was also not working properly on this scenario.
Fix both outdated detection and generation with regression tests.
=> fix: generate_hcl: when stack on root generated files get deleted on cleanup

docs/functions.md, generate/genfile/genfile.go, generate/genhcl/genhcl.go, generate/hcl_expr_func_test.go, hcl/eval/eval.go, hcl/eval/functions.go, hcl/eval/functions_test.go, hcl/hcl_stack_test.go, stack/globals_test.go
It was not documented clearly and handled gracefully the fact that the function `tm_hcl_expression` is not available on all contexts where other tm_ functions are available.
Closes #724
=> fix: panic when using tm_hcl_expression() on invalid contexts

generate/generate.go, generate/outdated_detection_test.go
Assertions were just being checked on code generation, other logic loading code like outdated code detection and generate.Load were not executing assertions. On any generated code situation if an assertion is failing we should fail. In order to do that I moved the assertion loading/eval to where stack generated configs are loaded.
=> fix: check assertions every time stack code is loaded

globals/eval_report.go, globals/globals.go, hcl/eval/object.go, hcl/eval/object_test.go, stack/globals_test.go
The fix #738 introduced a bug in the globals conflict checks.
It can be reproduced with the configuration below:
```hcl
globals hello {
world = {
a = 1
}
}
```
```hcl
import {
source = "/modules/imported.tm"
}
globals hello world {
a = 2
}
```
When running Terramate it gives the error below:
```
global eval: terramate schema error: global.hello.world.a attribute redefined: previously defined at /
```
The reason is that when fixing #738 we switched to store the "config dir" in the eval.Object values because it was needed to solve the problem but the check for conflicting attributes (at runtime) needs the actual source file (not from where it's being imported).
The fix just stores both the configuration dir and the origin source path in the eval.Object.
=> fix: incorrect globals conflict handling

mapexpr/map.go, stack/globals_test.go
The `element.old` was set to `null` on the first iteration for a given key, but then it cannot be used with `tm_try()` in all cases.
Make the `element.old` undefined and only ever set when there were a value already set for the given key.
=> fix: make iterator.old undefined on first iteration of a given key

makefiles/unix.mk
our release tags are not signed (and then not marked as `verified` by GH):
https://github.com/mineiros-io/terramate/tags
=> chore: create signed tags

README.md
Use the GH raw URL instead of the `/blob` URL because the latter is not recognized as an image in other markdown renderers (eg.: markedjs).
=> chore: change brand URL on README.md to point directly to the raw image.

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/exp_trigger_test.go
Allow the use of relative paths when triggering stacks but fail if the provided directory resolves to a path outside the current project.
Example:
```
$ terramate experimental trigger /some/deep/stack # absolute project path works
$ terramate experimental trigger some/deep/stack # relative path works
$ cd some/deep && terramate experimental trigger stack # works
```
when providing paths with `../`, the resolved path must be inside the current project which Terramate is executing otherwise it fails.
=> fix: allow relative stacks in experimental trigger

docs/config-overview.md
It reads better on the docs website.
Changed the heading of each block schema to h2.
=> chore: fix heading levels in docs

.goreleaser.yaml, makefiles/common.mk
The `archive.replacements` option is now deprecated.
The link below explains the change required to achieve the same behavior as before:
https://goreleaser.com/deprecations/#archivesreplacements
The `make release/dry-run` produces:
```
• archives
• creating                                       archive=dist/terramate_0.2.8-next_linux_arm64.tar.gz
• creating                                       archive=dist/terramate_0.2.8-next_darwin_arm64.tar.gz
• creating                                       archive=dist/terramate_0.2.8-next_linux_i386.tar.gz
• creating                                       archive=dist/terramate_0.2.8-next_linux_x86_64.tar.gz
• creating                                       archive=dist/terramate_0.2.8-next_windows_arm64.zip
• creating …
```
=> chore: upgrade goreleaser to v1.14.0

stack/trigger/trigger.go, stack/trigger/trigger_test.go, test/errors/errors.go, test/hclwrite/hclutils/utils.go
The Terramate panics (no trigger block) or ignores errors (wrong attribute types) with malformed trigger files.
Fixed the parser and added tests.
=> fix: multiple trigger parser issues (panics, errors ignored, etc)

stack/trigger/trigger.go, stack/trigger/trigger_test.go
Introduce the fields `type` and `context` to the trigger file. They don't change any functionality but make room for future trigger features.
Added two fields to the trigger file and update tests.
=> chore: add additional fields to trigger file

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/create_test.go, cmd/terramate/e2etests/exp_clone_test.go, config/stack.go, hcl/hcl.go, hcl/hcl_stack_test.go, hcl/printer.go, stack/clone.go, stack/clone_test.go, stack/create.go, stack/create_test.go, test/sandbox/sandbox.go
We can use `stack.ID` as a plain string because the `id` cannot be empty and then we can check if the string is empty to figure out if it was set or not.
Remove the hcl.StackID type and use a string for the ID type.
=> chore: remove the hcl.StackID type.

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/list_git_test.go, cmd/terramate/e2etests/list_nongit_test.go, cmd/terramate/e2etests/list_test.go, cmd/terramate/e2etests/run_test.go, config/filter/filter.go, config/filter/filter_test.go, config/stack.go
This PR introduces the `--tags` flag for filtering stacks by tags.
The tags filter uses the syntax below:
```
EXPR    = TAGNAME [ OP EXPR]
TAGNAME = <string>
OP      = ":" | ","
```
Where `:` and `,` are used for `AND` and `OR` logical operations, respectively.
Examples:
```
--tags "app:prod"           # selects all stacks with app AND prod tag.
--tags "k8s,nomad,docker"   # selects all stacks with k8s OR nomad OR docker tag.
```
The `:` has precedence over `,` so if multiple are provided, the `:` are grouped first:
```
--tags A:B,C    # (A && B) || C
--tags A,B:C:D  # A || (B && C && D)
```
If multiple `--tags` are provided, then they are grouped in a `OR` query:
```
--tags app --tags prod            # is the same as: --tags app,prod
--tags app:prod --tags infra:prod # is the same as: …
```
=> feat: add --tags filter to multiple commands

cmd/terramate/cli/cli.go, config/config.go, generate/generate.go, globals/stack.go, stack/eval.go
The #788 introduced a subtle change that affected the performance.
Before the project metadata was instantiated by `project.NewMetadata()` which traversed the config tree to fill the `terramate.stacks.list` object, this was done once and the project.Metadata interface was passed over to each stack code generation.
With #788 the `project.Metadata` and `stack.Metadata` interfaces were removed and the runtime objects were constructed when needed, which means config tree was walked over multiple times for the root runtime values.
The root metadata never changes, so it can be safely loaded once when the project config is loaded and then reused.
Added a `runtime` field to `config.Root` struct and the method `root.Runtime()` returns a copy of the computed runtime.
So the `root.Stacks()` method …
=> chore: fix performance regression introduced by #788

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/exp_eval_test.go, errors/error.go, globals/globals.go, hcl/dynexpr/dynexpr.go, hcl/dynexpr/dynrange/dynrange.go, hcl/dynexpr/dynrange/dynrange_test.go, hcl/eval/eval.go, hcl/eval/partial.go, stdlib/funcs.go, stdlib/ternary.go, test/hcl.go
Introduces the `--global <name>=<val>` flag to the commands `get-config-value`, `eval` and `partial-eval`.
The provided list of global flags can be used to override the values from the configuration or set new ones before handling the command.
Example:
```
$ cat config.tm
globals {
config = {
name = "my project"
}
}
$ terramate experimental eval --global config={} global.config
{}
```
It's possible to set just a specific part of an existent global value, if needed.
```
$ terramate experimental eval --global 'config.name="other value"' global.config
{
name = "other value"
}
```
It also supports a syntax sugar to extend objects dynamically using a `dot notation`.
So if the object path does not exist, the object is dynamically created.
For the same configuration specified before, the command …
=> feat: add --global flag to experimental eval

cmd/terramate/cli/cli.go, manager_test.go, project/project.go, stack/create.go, stack/create_test.go, test/sandbox/sandbox.go
In the past, the `config.Stack` fields were not exposed and then a separate structure was needed to configure new stacks. This is not needed anymore and the `config.Stack` is an standalone object.
A good result of this change is that now it's impossible to call `stack.Create()` with invalid paths (relative paths, paths outside rootdir, etc).
- Remove `stack.CreateCfg` and use the `config.Stack` object directly.
- refactor tests to use the new API.
- Some tests were removed (or moved to another place) because they are impossible to occur at the `stack.Create()` time.
=> chore: remove stack.CreateCfg and simplify tests

makefiles/common.mk
When the benchmarks were added, the TokensForExpression benchmark functions were not merged then the bench/check was added to check against the #822 branch.
This PR points the checks against `main`. This fixes the wrong bench results being sent to PRs.
=> chore: bench/check against main

hcl/eval/partial_eval_bench_test.go, makefiles/common.mk, stdlib/funcs_test.go
Those benchmarks are needed to assess if #838 is a good move.
=> chore: add benchmarks for partial evaluator

docs/codegen/generate-hcl.md, generate/genhcl/dynamic_test.go, generate/genhcl/genhcl.go
Add support for both `tm_dynamic.attributes` and `tm_dynamic.content` block in the same `tm_dynamic` block, given that they don't conflict. A conflict would be having a `attributes` field also defined in the `content` block.
The result is a merge of both configuration types.
=> feat: support tm_dynamic.attributes together with tm_dynamic.content

cmd/terramate/e2etests/generate_test.go
The #838 had a test deletion meant to be temporary but it ended up being merged.
This PR just put it back.
Sorry
=> chore: add back test mistakenly deleted

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/list_git_test.go, cmd/terramate/e2etests/list_nongit_test.go, cmd/terramate/e2etests/list_test.go, cmd/terramate/e2etests/run_test.go, config/filter/filter.go, config/filter/filter_test.go
Add `--no-tags` flag which filter by stacks not having the provided list of tags.
It could be combined with `--tags` and in such case a `AND` condition is generated.
Then `--tags prod --no-tags k8s` will return all stacks which have `prod` tag and not `k8s` tag.
The internal tag filter was updated to support tag inequality but the syntax is not exposed to users.
=> feat: add --no-tags flag

generate/genhcl/partial_eval_test.go, hcl/eval/partial_eval.go, hcl/eval/partial_eval_test.go
The PR #838 introduced a change that breaks some Terraform use cases.
When using the default HCL evaluator (from hashicorp), it fails if object keys contains a path traversal (a variable reference). Example:
https://go.dev/play/p/wUb09u5E7ls
This was always the case for fully evaluated expressions (like `globals` and `lets`) but partial-evaluator never failed in such cases because it bypassed the HCL evaluator and it did evaluation at the tokens level, ignoring most of the AST structure.
The new partial-evaluator works on top of parsed AST nodes and then the node had this information, if the key was wrapped or not, and then we followed the HCL default evaluator logic for consistency's sake but this break some TF use cases as reported in #861.
Closes #861
=> fix: rollback change that enforced parenthesis on non-literal keys

cmd/terramate/cli/checkpoint_localhost.go, cmd/terramate/cli/checkpoint_mineiros.go, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/run_test.go, cmd/terramate/e2etests/runner_test.go, docs/upgrade-check.md, go.mod, go.sum, makefiles/common.mk
Introduces upgrade checks in the `terramate version` command.
It uses the same technology used by Terraform.
- backend based on: https://checkpoint.hashicorp.com/
- client based on: https://github.com/hashicorp/go-checkpoint
The check can be disabled by exporting the environment variable `CHECKPOINT_DISABLE=1`.
A completely random signature (UUID v4) is generated and stored in `~/.terramate.d/checkpoint_signature`.
The check is cached and invalidated every 48 hours.
The implementation mimicks what Terraform does, the implementation is very similar.
=> feat: add basic version upgrade check

docs/change-detection.md, docs/cmdline.md, docs/codegen/generate-hcl.md, docs/config-overview.md, docs/functions.md, docs/map.md, docs/orchestration.md, docs/sharing-data.md, docs/tag-filter.md
The code blocks must have the correct language type in order to be nicely rendered in the website.
Add the language in each markdown code block.
=> chore: add language type in the documentation code blocks.

docs/config-overview.md, docs/map.md
The documentation didn't mention that `map` could be used inside `lets` block as well
=> chore: document that map block can be used with lets

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/run_test.go
When matching stacks inside the working directory, the implementation checked for stack paths with the working directory prefix. The code was something like:
```go
if strings.HasPrefix(stackdir, wd) {
// include stack in the list
}
```
it works for most cases but not if *working directory* is also the prefix of disjoint directories, see example stacks below:
```
/test
/tests
```
if *working dir* is `/test`, then both `/test` and `/tests` is a match.
Append `/` to the directories so the matches are *workingDir* `/test/` against `/test/` and `/tests/` which only returns `/test/`.
Closes #914
=> fix: stacks incorrectly selected when having same prefix wd prefix

config/config.go
While profiling the Terramate execution I noticed a high number of file descriptors were kept open and never released.
The issue was in the `config.LoadTree()` which open a directory file descriptor for listing file entries and it was never closed. 
In the loading of configuration trees, the file descriptors are now closed in a defer.
=> fix: file descriptor leak in the configuration tree load

fs/fs_bench_test.go
Temporary benchmark to validate the change from `os.ReadDir()` to `os.Readdirnames()`.
This bench will be removed if the change improves the performance.
Added benchmark.
=> chore: add fs.ListTerramateFiles benchmark

cmd/terramate/e2etests/exp_trigger_test.go
Disable symlink test on Windows because creating a symlink is a privileged operation.
=> chore: disable symlink tests on Windows

.github/workflows/benchmark.yml
avoid running benchmarks in the main branch and if no Go file changed.
=> chore: only run CI benchmarks if Go files changed.

cmd/terramate/cli/cli.go, cmd/terramate/cli/cli_unix.go, cmd/terramate/cli/cli_windows.go, cmd/terramate/cli/cliconfig/cliconfig.go, cmd/terramate/cli/cliconfig/cliconfig_test.go, cmd/terramate/cli/login.go, cmd/terramate/e2etests/run_test.go, cmd/terramate/e2etests/safeguard_test.go, go.mod, go.sum
Implements the `terramate experimental cloud login`.
Adding `-v` provides detailed output.
- Add `user_terramate_dir` option to `.terramaterc` file (CLI config file)
- Login with Google Provider.
- Open the browser with the OAuth2 consent page.
- RedirectURI to 127.0.0.1:<randon port in range 40000-52023>
- Store token, refresh token and expiration in `$homeTerramateDir/credentials.tmrc.json`
Now it's also possible to customize where the checkpoint cache and signature are stored by setting the `homeTerramateDir`.
=> feat: terramate experimental cloud login

README.md, docs/.vitepress/config.ts, docs/getting-started/index.md
We moved the blog to blog.terramate.io
=> Change blog url to blog.terramate.io

hcl/hcl.go, hcl/hcl_test.go
I spent some time digging if we lost this test somehow when moving testcases around between packages, but we actually never had tests for a missing `content` block inside the `generate_hcl` block.
The `content` block was introduced here: https://github.com/terramate-io/terramate/pull/220/files
Then this fixes a bug that has existed since [v0.0.11](https://github.com/terramate-io/terramate/releases/tag/v0.0.11).
=> fix: crash when having generate_hcl with no content block

docs/.vitepress/config.ts
Previously the configuration of Vitepress was faulty the theme was always set to the users browser standard instead of setting it to dark mode per default.
This change moves `appearance: 'dark',` to the correct level in the configuration so that dark mode is always used as the default mode.
=> Fix config to always use darkmode as default mode instead of detecting the browsers default

.github/CODEOWNERS
Previously we didn't manage CODEOWNERS.
This PR introduces CODEOWNERS to automatically assign all PRs to @terramate-io/cli-tooling
=> Add codeowners for automatically assigning PRs

cloud/git.go, cloud/git_test.go, cmd/terramate/cli/cloud.go
Normalize the repository name for Terramate Cloud.
=> fix: normalize git repository url

.github/workflows/ci.yml, cloud/testserver/handlers.go, cloud/types.go, cmd/terramate/cli/cloud.go
The environment variable `TM_CLOUD_ORGANIZATION` can be used to select the organization where data will be sent to.
=> feat: add support for selecting the organization using env var

cmd/terramate/cli/cli.go
Adds a more explicit error message in case no Terramate project root can't be located.
=> chore: phrase error message more explicit in case Terramate can't find the project root

cmd/terramate/cli/cli.go
Makes the exception returned by Terramate CLI if no project is detected even more explicit.
=> chore: make error message in case no terramate project has been detected more explicit

docs/installation.md, hack/release/Dockerfile
Our Dockerfile is based on an outdated version of Ubuntu and missed Git as a dependency.
Updates ubuntu to current LTS `22.04` and adds Git as a dependency.
=> Update Ubuntu LTS and add Git to the Dockerfile

cmd/terramate/e2etests/run_cloud_test.go, cmd/terramate/e2etests/run_test.go, cmd/terramate/e2etests/runner_test.go
The tests are generating OIDC JWT tokens because they are detected in the e2e tests.
Disabled them in the e2e runner.
=> chore: disable OIDC integration in tests

docs/code-generation/index.md
Fixing a minor typo in the code generation documentation
=> Fix spelling in code generation docs

cloud/testserver/handlers.go, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/init_test.go, cmd/terramate/e2etests/runner_test.go, stack/create.go, tf/terraform.go, tf/terraform_test.go
Implements the command `terramate experimental init`.
For now, it requires a `--all-terraform` flag which initialize Terraform stacks.
In the future additional flags would be created to initialize Terragrunt, Kubernetes, etc.
=> feat: implement experimental init command.

docs/stacks/index.md
For some reason, the `wants` and `wanted_by` documentation have gone missing from the docs.
The PR also improves the other attributes docs, by providing some examples.
=> chore: improve stack documentation

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/exp_ensure_stack_id_test.go, stack/clone.go
This command generates a random UUID for the `stack.id` of each stack which does not define it.
=> feat:  experimental ensure-stack-id command

cmd/terramate/cli/cloud.go, cmd/terramate/cli/cloud_credential_github.go
In the case of `Github OIDC` the organization status is `trusted` and it was not handled.
=> fix: handle OIDC trusted status

docs/.vitepress/config.ts
Previously we didn't have any GDPR compliant consent on the website.
This adds the Consentmanager integration to the website for users to opt in and out for tracking such as HubSpot.
=> Add cookie manager to documentation website

docs/.vitepress/config.ts, docs/.vitepress/theme/Layout.vue
Previously we used ConsentManager - however the solution doesn't scale for multiple tags.
Moving to Google Tag Manager to programmatically manage tags.
=> Move cookie integration to google tag manager

docs/index.md
Prior to this PR the documentation landing page had the title 'Terramate | Terramate'
This PR changes the title to 'Terramate: Supercharge Terraform with Stacks and Code Generation' which is SEO and human friendly.
=> Add a descriptive page title to the documentation page

docs/.vitepress/config.ts, docs/about-stacks.md, docs/getting-started/index.md, docs/installation.md, docs/introduction.md
Currently we don't have an overview/ introduction page in the documentation. Developers don't really feel well guided through the docs.
This PR introduces a new documentation page called introduction that explains Terramate, the value prop and a quick overview. In a follow up PR we will add uses case and more references to articles and guides.
=> Add introduction page to documentation

cloud/testserver/handlers.go, cloud/types.go, cmd/terramate/cli/cloud.go
=> fix: do not send review_request if pull request URL cannot be detected

cloud/cloud.go, cmd/terramate/cli/cloud.go
When the cloud features are disabled, the `terramate experimental cloud info` gives the panic below:
```
2023-07-19T12:19:16+01:00 WRN disabling the cloud features error="resource not found: failed to check if credentials work: GET http://localhost:8080/v1/memberships"
panic: terramate internal error: cred.Info() called for unvalidated credential
goroutine 1 [running]:
github.com/terramate-io/terramate/cmd/terramate/cli.(*googleCredential).Info(0xc000004300?)
/home/i4k/src/terramate-io/terramate/cmd/terramate/cli/cloud_credential_google.go:623 +0x874
github.com/terramate-io/terramate/cmd/terramate/cli.(*cli).cloudInfo(0xc000004300)
/home/i4k/src/terramate-io/terramate/cmd/terramate/cli/cloud.go:357 +0x82
github.com/terramate-io/terramate/cmd/terramate/cli.(*cli).run(0xc000004300) …
```
=> fix: cloud info panics if cloud features are disabled

cmd/terramate/cli/cloud.go
In a coding pairing with @mariux we identified that this method name was misleading.
=> chore: refactor cli method name

docs/.vitepress/config.ts
Currently we have a dead link in the linkedin icon on the documentation page.
This PR fixes the link to point to the right location.
=> Fix link to linkedin page

cloud/types.go, cmd/terramate/cli/cloud.go, cmd/terramate/e2etests/run_cloud_test.go, config/stack.go, docs/stacks/index.md, stack/stack_test.go
**breaking change**: The handling of `stack.id` is now case-insensitive, which means that the ids `my-id`, `My-id`, `MY-id`, `MY-Id`, etc, all represent the same id.
The Terramate CLI is going to treat them as lowercase internally and in the cloud.
=> feat!: make stack.id case insensitive

docs/cmdline/version.md
Previously we didn't have any documentation for the `terramate version` command.
This PR adds a new page to the documentation explaining the `terramate version` command.
=> Add documentation for terramate version command

docs/cmdline/run.md
Previously we didn't have any explicit documentation for the `terramate run` command.
This PR adds a detailed documentation page for the `terramate run` command.
=> Add documentation for the terramate run command

.github/workflows/ci.yml
What it sounds like on the tin. This will enable us to
1. No longer run CI for PRs that only change documentation, and
2. Enable us to use the Merge Queue feature of github. This will be nice as it
will no longer require endless merging of the base branch to merge a PR.
Once merged, this will require someone to manually edit the repository, it 
does not appear that the merge queue configuration is exposed, or at least 
included in the github terraform module. See how to do so [in the documentation
here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#managing-a-merge-queue)
=> Chore: Enable merge queue, disable CI for document PRs.

docs/cmdline/generate.md
Previously we didn't have a dedicated documentation page for the `terramate generate` command.
This PR adds a minimal documentation for the `terramate generate` command.
=> Add documentation for the terramate generate command

.github/workflows/ci-experimental.yml, .github/workflows/coverage.yml
We run the full CI suite on any PR, however, documentation lives alongside code,
so we run a full suite for things that touch no code. This stops that, and
should speed up CI for documentation changes. Follow up to #1057. 
The jobs `ci-experimental` and `coverage` no longer run on pushes that only
change files in `docs/**`.
=> chore: Don't run ci-experimental and coverage on documentation PRs.

docs/cmdline/clone.md
Previously we didn't have any documentation for the clone command.
This adds a new documentation page covering the `terramate experimental clone` command.
=> Add documentation for the clone command

docs/cmdline/create.md
Currently we don't document the CLI commands at all.
This PR adds the documentation for `terramate create [path] [options]`
=> Add command line documentation for the create command

docs/cmdline/cloud-info.md
Previously we didn't have any documentation for the `cloud info` command.
This PR adds a new documentation page covering the `cloud info` command.
=> Add documenation for the terramate cloud info command

docs/cmdline/metadata.md
Previously we didn't have documentation for the experimental `metadata` command.
This PR adds a new documentation page that explains the `metadata` command.
=> Add documentation for metadata command

.github/workflows/ci-experimental.yml, .github/workflows/ci.yml, .github/workflows/coverage.yml, .tool-versions, _testdata/example-stack/stack.tm.hcl, docs/stack.tm.hcl, makefiles/common.mk, stack.tm.hcl
GHA filters made the required CI run be skipped and thus the requirement was not met anymore blocking our docs PRs.
Now we use `terramate` Change Detection to skip golang builds and tests on docs changes.
This should speed up docs only PRs by 10x and more and save tons of build minutes and thus energy - save the planet ;)
Features used a combination of:
- Terramate Change Detection: e.g. `terramate run --changed`
- Terramate Orchestration: e.g. `terramate run --tags golang`
- Terramate Execute anything: e.g. `terramate run make test`
- leading to `terramate run --changed --tags golang -- make whatever-you-need`
We install Terramate in the CI/CD using `asdf` but will provide a GHA soon.
=> feat: We use terramate to orchestrate terramate builds

docs/cmdline/trigger.md
Previously we didn't have any documentation for the `trigger` command.
This PR adds a new documentation page for the `trigger` command.
=> Add documentation for the trigger command

docs/cmdline/cloud-login.md
Previously we didn't have any documentation for the `cloud login` command.
This PR adds a new page to the documentation explaining the `cloud login` command.
=> Add documentation for the terramate cloud login command

docs/cmdline/run-graph.md
Previously we didn't have any documentation for the `run-graph`.
This PR adds a new documentation page for the `run-graph` command.
=> Add documentation for the run-graph command

docs/cmdline/vendor-download.md
Previously we didn't have any documentation for the `vendor download` command.
Adds a new page to the documentation explaining the `vendor download` command.
=> Add documentation for the vendor download command

docs/cmdline/globals.md
Previously we didn't have any documentation for the `globals` command.
This PR adds a new page to the documentation covering the `globals` command.
=> Add documentation for the globals command

docs/cmdline/eval.md
Previously we didn't have any documentation for the `eval` command.
This PR adds a new page to the documentation to explain the `eval` command.
=> Add documentation for the eval command

docs/cmdline/get-config-value.md
Previously we didn't have documentation for the `get-config-value` command.
This PR adds a dedicated documentation page for the `get-config-value`.
=> Add documentation for terramate get-config-value

docs/cmdline/run-env.md
Previously we didn't have any documentation for the `run env` command.
This PR adds a new documentation for the `run env` command.
=> Add documentationt or the run-env command

docs/configuration/index.md
The current example of import and glob imports is missleading and not clearly separated.
This splits up the example into two different examples which should be more clear to the audience.
=> Split import and glob import into two different examples

docs/.vitepress/config.ts, docs/cmdline/version.md, docs/guides/index.md, docs/introduction.md
Previously we had all guides listed in the sidebar of the documentation. This was quite overwhelming for our users.
This PR adds all guides and examples as well as community examples to a dedicated page `/guides` in the documentation.
=> Move guides and example to dedicated page instead of listing everything in the sidebar

cmd/terramate/e2etests/cmd/test/test.go, cmd/terramate/e2etests/run_unix_test.go, docs/cmdline/run.md, docs/configuration/project-config.md, go.mod, go.sum, makefiles/windows.mk, run/env.go, run/exec.go, run/lookpath_unix.go, run/lookpath_windows.go, terramate.tm.hcl, test/os.go, test/sandbox/sandbox.go
When executing the commands provided to `terramate run`, the actual path of the program was being resolved using Terramate's own `PATH` environment variable instead of the stack's environment (that could be changed using `terramate.config.run.env.PATH` configuration.
The fix ensures that the program to be invoked is resolved using the stack's environment.
=> fix: use stack environ for the cmd lookpath

cmd/terramate/cli/cloud.go, cmd/terramate/cli/github/client.go
Now it generates the warnings below:
```
2023-08-07T18:50:21+01:00 WRN The HEAD commit cannot be found in the remote. Did you forget to push? gh-repository=terramate-io/terramate head-commit=0ceebdaee20e56ff118a7a7077a910c1609cded0 normalized-repo=github.com/terramate-io/terramate
```
```
2023-08-07T18:54:54+01:00 WRN no pull request associated with HEAD commit gh-repository=terramate-io/terramate head-commit=12738926e2381bc243ae59d01fc07460c3c821ba normalized-repo=github.com/terramate-io/terramate
```
```
2023-08-07T18:58:32+01:00 WRN The GITHUB_TOKEN environment variable needs to be exported for private repositories. gh-repository=mineiros-io/iac-gc
```
```
2023-08-07T18:58:32+01:00 WRN The provided GitHub token does not have permission to read this repository or it does not exists. …
```
=> chore: warn if pull request cannot be associated with the deployment

cmd/terramate/cli/cloud.go
Always add the GHA attempt number to the `deploymentURL` .
=> chore: add attempt number to the deploymentURL

makefiles/common.mk
At the time that we migrated the repository this name could not be updated because the `benchcheck` command compares different revisions and we were in the middle of the transition. Keeping the old name worked fine because Github redirects requests to the new name when the repo is transferred or renamed.
=> chore: fix repository of the make/bench

CHANGELOG.md, cmd/terramate/cli/cli.go
When we run `terramate create --all-terraform`, we do not fill the `name` and
`description` fields. This is different behaviour than `terramate create
/path/to/stack`, which will use `stack` as value for both name and description.
When running `terramate create --all-terraform`, created stacks now have the
same derived names and descriptions as stacks created without the
`--all-terraform` flag.
=> Fix(create/all-terraform): Add in Name/Description in new stacks.

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/cli/cloud.go, cmd/terramate/e2etests/cmd/test/test.go, cmd/terramate/e2etests/run_cloud_test.go, cmd/terramate/e2etests/run_eval_test.go, cmd/terramate/e2etests/run_test.go, cmd/terramate/e2etests/runner_test.go, cmd/terramate/e2etests/safeguard_test.go, docs/cmdline/run.md, run/exec.go, stdlib/funcs.go
Introduces the `terramate run --eval` flag.
When set, all components of the command (name and arguments) can be evaluated from HCL strings.
Examples:
Evaluating stack metadata:
```bash
$ terramate run --eval -- echo '${terramate.stack.path.absolute}'
/stacks/a
/stacks/b
```
Evaluating globals:
```bash
$ cat globals.tm
globals {
cmd = "terraform"
arg = "apply"
}
$ terramate run --eval -- '${global.cmd}' '${global.arg}'
```
Don't forget to use single quotes or escape the `$`, otherwise your shell will interpret the dollar sign before Terramate can do it.
=> feat: add run --eval for evaluating cmd args

cloud/testserver/handlers.go, cmd/terramate/cli/cloud.go
The issue was introduced in v0.4.1 by commit 403e2e4e3abd8fd416516fa8035bae331ab07e69.
=> fix(cloud): deployment commit_sha is not sent anymore.

cloud/types.go, cmd/terramate/cli/cloud.go
The `commit_sha` was missing in the `deployment_commit_*` set of metadata.
Added the field.
=> chore(cloud): send commit_sha in the metadata

.github/workflows/benchmark.yml, cmd/terramate/main.go
When the event is of type `pull_request`, the `GITHUB_SHA` environment
variable contains the sha of the merge branch created under the hood.
The merge commit is not reachable in the project's git tree.
It was changed to use `${{ github.event.pull_request.head.sha }}` which
points to the head of the PR at the time that the event triggered.
Note: when re-running the event, the same payload is used then the same
HEAD commit is used even if PR HEAD moved.
=> fix(gha,benchmark): GITHUB_SHA isn't the sha that triggered pr event.

CHANGELOG.md, cloud/cloud.go, cloud/cloud_test.go, cloud/stack/status.go, cloud/testserver/handlers.go, cloud/types.go, cmd/terramate/cli/cli.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/cloud_sync_deployment.go, cmd/terramate/cli/cloud_sync_drift.go, cmd/terramate/cli/project.go, cmd/terramate/cli/run.go, cmd/terramate/e2etests/cmd/test/test.go, cmd/terramate/e2etests/exp_trigger_cloud_test.go, cmd/terramate/e2etests/list_cloud_test.go, cmd/terramate/e2etests/run_cloud_deployment_test.go, cmd/terramate/e2etests/run_cloud_drift_test.go, cmd/terramate/e2etests/run_signal_test.go, cmd/terramate/e2etests/runner_test.go, test/cloud/client.go
Introduce the `--cloud-sync-drift-status` flag for syncing drifts to the Terramate Cloud.
Usage:
```
$ terramate run --cloud-sync-drift-status -- terraform plan --detailed-exit-code
```
Below exit-code interpretation table:
| exit code | drift_status |
| ------------- | ------------- |
| 0  | ok |
| 1  | failed |
| 2  | drifted |
| n  | failed |
If for any reason the command is not invoked, or the stack execution is canceled by the user (CTRL-C), then no drift status is synced.
=> feat: syncing drifts with Terramate Cloud

cloud/testserver/handlers.go, cloud/types.go, cmd/terramate/cli/cli.go, cmd/terramate/cli/clitest/doc.go, cmd/terramate/cli/clitest/messages.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/cloud_credential_github.go, cmd/terramate/cli/cloud_credential_google.go, cmd/terramate/cli/cloud_sync_deployment.go, cmd/terramate/cli/cloud_sync_drift.go, cmd/terramate/cli/run.go, cmd/terramate/e2etests/run_cloud_deployment_test.go, cmd/terramate/e2etests/run_cloud_drift_test.go, cmd/terramate/e2etests/run_cloud_uimode_test.go, cmd/terramate/e2etests/runner_test.go
The Human x Automation UI modes were introduced for different error handling depending on where is the execution.
=> chore(tmc): introduce uimode in the cli for enhanced cloud fail cases.

docs/.vitepress/config.ts, docs/change-detection/index.md
- chore: Fix .vitepress/config.ts link in docs
- chore: Fix change-detection link in docs
closes #1140 
closes #1138 
This is needed as we can not yet run external PRs due to missing credentials for integration tests.
=> chore: fix links in docs

cmd/terramate/cli/clitest/messages.go, cmd/terramate/cli/cloud.go, cmd/terramate/e2etests/run_cloud_uimode_test.go
Now only active organizations are considered when selecting the default one.
=> chore(tmc): improve organization selection.

cloud/types.go, cmd/terramate/cli/cli.go, cmd/terramate/cli/clitest/messages.go, cmd/terramate/cli/cloud_sync_drift.go, cmd/terramate/cli/run.go, cmd/terramate/e2etests/cmd/test/helper.go, cmd/terramate/e2etests/cmd/test/main.go, cmd/terramate/e2etests/cmd/test/terraform.go, cmd/terramate/e2etests/main_test.go, cmd/terramate/e2etests/run_cloud_deployment_test.go, cmd/terramate/e2etests/run_cloud_drift_test.go, cmd/terramate/e2etests/run_unix_test.go, hcl/fmt/fmt_test.go, test/fs.go, test/fs_unix.go, test/fs_windows.go, test/sandbox/sandbox.go
This new flag must be used with `--cloud-sync-drift-status` to enable the sending of the rendered plan output to the Terramate Cloud.
=> feat(tmc): add --cloud-sync-terraform-plan-file option.

cmd/terramate/cli/run.go
When the project uses a `terramate.config` block to declare the project and it's not a git repository, the cloud sync features panic because `git` metadata is required.
Added a fatal error in case git is not setup and a cloud sync flag is provided.
=> fix(tmc): panic when cloud features are used without a repository

cmd/terramate/main.go
Removes a temporary comment accidentally merged.
=> chore: remove temporary comment

CHANGELOG.md, cmd/terramate/cli/cloud.go, cmd/terramate/e2etests/run_cloud_config_test.go, docs/configuration/project-config.md, hcl/hcl.go, hcl/hcl_test.go, test/hcl.go
When being member of multiple cloud organizations, the user had to set the environment variable TM_CLOUD_ORGANIZATION to the name of a specific one when syncing cloud data.
In many cases it would be more convenient to set this automatically per project via configuration.
A new config setting has been added to the terramate config block. Usage example:
```
terramate {
config {
cloud {
organization = "my-org-name"
}
}
}
```
TM_CLOUD_ORGANIZATION still works as before and overrides the config value if set.
=> feat: add config setting for cloud organization

cmd/terramate/e2etests/create_test.go, containers/test/Dockerfile, makefiles/common.mk
On Macos and Windows, running the tests is slower by a factor of 3-4 when compared to Linux, which has a negative impact on the development workflow on these systems.
When running the tests in a Docker container on the other hand, the performance is comparable to native Linux.
A Dockerfile and make target are added to run the tests with Docker build. Usage:
`make docker/test`
Currently, only the e2etests are executed, because when running terramate as root within the container, some filesystem related tests break. The one e2etest that breaks this way has been adapted
=> chore: add make target to run tests within docker

CHANGELOG.md, cloud/cloud.go, cloud/log_syncer.go, cloud/log_syncer_test.go, cloud/types.go, cmd/terramate/cli/run.go
Terramate Cloud supports visualizing the deployment logs in real-time.
A log syncer was created that proxies stdout/stderr writes using an in-memory pipe. The syncer creates 3 goroutines (1 for stdout, 1 for stderr and 1 for synchronizing logs) that *MUST* be shutdown/terminated after execution of each stack.
The syncer supports a customizable `batchSize` and `maxLineSize` but the requirement of the latter will be fixed in a separate PR.
=> feat(tmc): send logs of the user-supplied command to Terramate Cloud.

cloud/log_syncer.go, cloud/log_syncer_test.go
When providing an stdout/stderr containing an empty line, the log syncer crashes:
```
panic: runtime error: index out of range [-1]
goroutine 213 [running]:
github.com/terramate-io/terramate/cloud.dropCRLN(...)
/vagrant/terramate/cloud/log_syncer.go:192
github.com/terramate-io/terramate/cloud.(*LogSyncer).NewBuffer.func1()
/vagrant/terramate/cloud/log_syncer.go:103 +0x6fd
created by github.com/terramate-io/terramate/cloud.(*LogSyncer).NewBuffer
/vagrant/terramate/cloud/log_syncer.go:80 +0x2a5
FAIL    github.com/terramate-io/terramate/cloud 0.055s
FAIL
```
A bounds check is added before removing the CRLN from the line.
=> fix(tmc): panic due to index out of range in logsyncer

cloud/types.go, cmd/terramate/cli/cloud_sync_deployment.go, cmd/terramate/cli/cloud_sync_drift.go, cmd/terramate/e2etests/run_cloud_drift_test.go, cmd/terramate/e2etests/run_cloud_signal_test.go
To link back to stack changes in a Git repository from Terramate Cloud, the default branch must be known. Currently, the backend just assumes "main".
* A new attribute `default_branch` has been added to the Stack structure. The client always sets this field.
* Tests have been updated accordingly to include the DefaultBranch when comparing results.
* A new test has been added for a default branch that is not "main".
=> feat(tmc): add default branch to synced stack data

cmd/terramate/e2etests/run_cloud_deployment_test.go, cmd/terramate/e2etests/run_test.go, cmd/terramate/e2etests/safeguard_test.go, cmd/terramate/e2etests/version_check_test.go
The Windows tests depended upon the installation of cygwin tools like `cat`, `true`, etc.
Now a brand new Windows box can run Terramate tests.
All occurrences of `cat`, `true`, etc, were replaced by `[testHelperBin, <cmd>]`.
=> chore(tests): fix windows tests depending on unix tools.

.github/workflows/ci.yml, cmd/terramate/cli/cloud_credential_github.go, cmd/terramate/cli/cloud_credential_google.go
These messages can be enabled with `terramate -v ...` and they will help us troubleshoot issues related to token refreshing.
=> chore(tmc): add verbose messages when refreshing tokens.

cmd/terramate/e2etests/main_test.go, containers/test/Dockerfile, makefiles/common.mk
The changes below were implemented:
- `make docker/test` -> `make test/docker`.
Reasoning: All test commands begin with `test`.
- Run `make test` in the container build instead of `go test ... cmd/terramate/e2etests`.
Reasoning: Convenience, so we can use a single command to check if everything works.
- Make rules sorted alphabetically.
Then it's easier to spot the rules when running just `make` or `make help`.
- In the e2e tests, builds terramate and helper with -buildvcs=off
Reasoning: In order to embed git meta information, Go needs a configured `git` client and file permissions must be correct. The VCS embedding is not needed in the e2e binaries, then disabling it is easier than making it work in the docker env.
=> chore: improve running tests in docker.

cloud/types.go, cmd/terramate/cli/cloud.go, git/git.go, git/git_test.go
The deployment metadata currently only queries the GitHub API. This change adds commit metadata for non-GitHub users as well.
The deployment metadata is extended with attributes for commit author, email, time, title and description. These attributes are queried from git directly, so they are always set. GitHub-specific metadata is still set as before.
For now, there are no e2etests, they will be added in a later PR.
=> feat(tmc): add git commit info to deployment metadata

cloud/types.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/cloud_sync_drift.go, cmd/terramate/cli/run.go, cmd/terramate/e2etests/run_cloud_drift_test.go, cmd/terramate/e2etests/run_cloud_signal_test.go
Users would like to know how when and for how long the command associated with a drifted stack ran.
* Two optional attributes StartedAt and FinishedAt have been added to synced drift data. They are set whenever there was an attempt to run the command, but may be omitted in error cases where no run was attempted yet.
=> feat(tmc): sync drift run duration

.github/workflows/ci.yml
As we have `fail-fast` disabled we are keeping runners busy even when required jobs already failed. This creates a huge queue of PR builds waiting for available runners if multiple people contribute to the same repository.
=> chore: enable GHA fail-fast.

.github/workflows/ci.yml
Reasoning: it's a very slow job that runs in each branch push but unlikely to fail if `make build` works. Still useful to keep so we can receive alerts if it fails but it never did.
=> chore: make release-dry-run job optional.

cmd/terramate/e2etests/runner_test.go, cmd/terramate/e2etests/runner_unix_test.go, cmd/terramate/e2etests/runner_windows_test.go
Some testing helper methods are unused because signal tests are skipped in OSX.
=> chore: fix linting issues in OSX.

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/exp_clone_test.go, docs/cmdline/clone.md, stack/clone.go, stack/clone_test.go, test/os.go, test/sandbox/sandbox.go
The experimental clone command did not work correctly with nested stacks. Before, it just treated them as normal files so the cloned directory would contain duplicated stack ids.
* `clone` now detects nested stacks and updates their stack ids if required.
* An flag `--skip-child-stacks` has been added to `clone` to ignore nested stacks. Files/directories within the parent stack that are _not_ nested stacks will still be cloned recursively.
* Since nested stacks are considered, clone can also be called on directories that are not stacks. 
* Output messages have been adapted to the new semantics.
* Docs have been updated.
Internal changes:
* `sandbox.AssertTree` helper has been added. It supports specs similar to `BuildTree` to assert that certain files or directories are present. This is …
=> feat: add clone support for child stacks

cloud/types.go, cmd/terramate/cli/cloud.go
Add 2 additional metadata when synchronising deployments or drifts with the _Terramate Cloud_.
- `metadata.github_actions_workflow_name`
- `metadata.github_actions_workflow_ref`
=> chore(tmc): send workflow name and ref in the metadata

cmd/terramate/cli/run.go
The `--cloud-sync-terraform-plan-file` can only be used with `--cloud-sync-drift-status` (for now).
Added a guard against use of the flag without drift sync status flag.
=> fix: ensure --cloud-sync-terraform-plan-file require drift flag.

cmd/terramate/e2etests/generate_test.go, docs/getting-started/index.md, generate/report.go, generate/report_test.go
It's a typo because the object it follows is plural.
Closes #1218 
We cannot yet run external PRs due to missing credentials for integration tests.
Thanks @grggls for the contribution.
=> chore: replace "means" with "mean" in the generate output.

docs/stacks/index.md
When users read the documentation and stumble across the exposed properties of a stack, it's not clear that this defaults to auto-generated UUIDs v4.
Add this to the documentation and reference the commands also that use UUID generation.
=> Add UUID behaviour to the stacks properties documentation

.github/workflows/ci.yml
This feature was enabled to speed up the workflow but it actually made it slower.
Let's rollback to the default workflow.
Removed the `merge_group` option from the ci.yml file.
=> chore(gha): remove merge_group feature.

docs/code-generation/generate-file.md
The link is malformed:
Fixed the markdown.
=> chore(docs): fix links in generate docs

CHANGELOG.md, hcl/hcl.go, hcl/hcl_test.go
The parsing errors of stack fields were not providing the error line and number.
Added the file ranges in the case of errors for fields of type `set`.
=> fix: missing file ranges in stack config parsing.

docs/orchestration/index.md
Fix typo in the `orchestration` documentation
=> Fix documentation typo

cloud/cloud.go, cmd/terramate/cli/cloud.go
The `limit` query parameter is deprecated.
Changed to use `page` and `per_page` query parameters.
=> fix(tmc): limit query parameter was deprecated

CHANGELOG.md, hcl/hcl.go, hcl/hcl_test.go
Add the `terramate.config.experiments` config for enabling experimental features.
**No experimental feature is introduced with this change**.
Only the parser is changed now. Upcoming features can look into the AST for deciding when to enable the features.
=> feat: add terramate.config.experiments feature switch.

cloud/cloud.go, cloud/cloud_test.go, cmd/terramate/e2etests/run_cloud_config_test.go, cmd/terramate/e2etests/run_cloud_uimode_test.go
With this change, the client is able to receive responses from the
cloud that contain optional parameters like `charset` in the
`Content-Type` header value.
Accepting optional parameters using `mime` package from standard library.
Change all test servers to return an optional parameter to mimic real behaviour.
=> feat(cloud): Give support to optional parameters in Content Type from tmc

docs/functions/index.md, docs/functions/terramate-builtin/tm_hcl_expression.md, docs/functions/terramate-builtin/tm_ternary.md, docs/functions/terramate-builtin/tm_vendor.md, docs/functions/terramate-builtin/tm_version_match.md
Previously, some of the links in the sidebar of our documentation were broken.
This PR corrects the links by adding the missing directory to the URLs.
=> Fix links in sidebar to built in functions

.gitignore, cloud/testserver/cloudstore/store.go, cloud/testserver/cmd/testserver/main.go, cmd/terramate/e2etests/cloud/interop/interoperability_test.go, cmd/terramate/e2etests/cloud/interop/main_test.go, cmd/terramate/e2etests/cloud/interop/testdata/interop-stacks/basic-drift/main.tf, cmd/terramate/e2etests/cloud/interop/testdata/interop-stacks/basic-drift/stack.tm.hcl, cmd/terramate/e2etests/cloud/interop/testdata/interop-stacks/empty/stack.tm.hcl, cmd/terramate/e2etests/internal/runner/runner.go
It provides a way of doing e2e tests of the CLI against real backends.
Usage:
````
$ TMC_API_URL=http://0.0.0.0:8000 go test -tags interop ./cmd/terramate/e2etests/cloud/interop -count=1 -v
toolsetPath: /var/folders/bs/t0s9dnm124v1k8g_f38kpzk00000gn/T/cmd-terramate-test-35195610
=== RUN   TestInteropSyncDeployment
--- PASS: TestInteropSyncDeployment (5.96s)
=== RUN   TestInteropDrift
--- PASS: TestInteropDrift (7.62s)
PASS
ok      github.com/terramate-io/terramate/cmd/terramate/e2etests/cloud/interop  16.125s
```
=> chore(tests): add support for backend interoperability tests.

config/assert.go, config/eval.go, config/script.go, config/script_test.go, hcl/hcl_script.go
The attributes of a script block need to be evaluated at runtime in order to resolve any variables/globals/functions etc.
* Added an `EvalScript` function that evaluates a script based on the provided context
* Added tests for validating types + evaluating functions/globals
=> feat(scripts): evaluate script blocks

CHANGELOG.md, cloud/cloud.go, cloud/stack/status.go, cloud/stack/status_test.go, cloud/testserver/cloudstore/store.go, cloud/testserver/stacks.go, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/cloud/exp_trigger_cloud_test.go, cmd/terramate/e2etests/cloud/list_cloud_test.go
It adds more status filters for the `--experimental-status` flag of both `terramate list` and `terramate experimental trigger`.
=> feat(tmc): add support for additional stack statuses.

cloud/testserver/cloudstore/store.go, cloud/testserver/drifts.go, cmd/terramate/e2etests/cloud/run_cloud_uimode_test.go
The cloudstore.Data was reused between testcases and then it hit some cases not implemented in the testserver (handling drifts in stacks still pending).
The `tc.cloudData` was serialized and then loaded again in each subtest.
=> chore(tests): fix flaky e2e test.

docs/.vitepress/config.ts
Currently users that are looking at the documentation website have no chance to navigate to our cloud offering.
This adds a direct link to terramate.io/ to the top navigation
=> Add link to Terramate Cloud to Top Navigation in docs

docs/cli/cmdline/run.md
The current example is misleading and invalid, abusing tags as labels.
Fixes the example on how to filter for specific tags when using `terramate run`
=> Fix confusing tags filter example from terramate run command

config/config.go, fs/fs.go, hcl/fmt/fmt.go, makefiles/common.mk, stack/manager.go
- Use `f.ReadDir(-1)` for listing all the files with `e.IsDir()` populated in a single syscall.
- do not sort the files
=> chore: optimize listing of Terramate files and directories.

stdlib/funcs_bench_test.go
Adds benchmark for the current implementation of `tm_ternary()`.
It needs to be introduced in separate PR so we can use [benchcheck](https://pkg.go.dev/github.com/madlambda/benchcheck) to compare the performance of `main` versus other branches.
none
- An upcoming PR will improve `tm_ternary()` performance by indirectly disabling type checking.
```
no
```
=> chore(perf): add benchmark for tm_ternary().

.github/workflows/benchmark.yml, makefiles/common.mk, stdlib/ternary.go
It optimises the `tm_ternary()` funcall by declaring the function return type as a static `cty.DynamicPseudoType`. This is safe because Terramate doesn't do any schema validation using Hashicorp evaluator.
Benchmark result (extracted from the comment below):
```
metric: time/op
TmTernary-4: old 3.48µs ± 1%: new 2.59µs ± 1%: delta: -25.33%
metric: alloc/op
TmTernary-4: old 1.61kB ± 0%: new 1.11kB ± 0%: delta: -30.85%
metric: allocs/op
TmTernary-4: old 40.0 ± 0%: new 26.0 ± 0%: delta: -35.00%
```
- The `make bench/check` target was changed to support configuring the `old` ref.
- The benchmark.yml workflow was changed to use the github base ref so we can compare benchmark between PRs as well.
```
no
```
=> chore(perf): optimises tm_ternary by disabling type checking.

stdlib/funcs_bench_test.go
Adds benchmark for the `tm_try()` function. This is needed by #1279 
```
no
```
=> chore(perf): add benchmark to the tm_try() funcall.

stdlib/funcs.go, stdlib/try.go
It optimises the `tm_try()` funcall by declaring the function return type as a static cty.DynamicPseudoType. This is safe because Terramate doesn't do any schema validation using Hashicorp evaluator.
This change alone gives ~0.5s performance improvement when running `generate` in our internal framework project.
Depends on #1280 
```
➜  iac-gcloud git:(main) ✗ /usr/bin/time -h ~/src/terramate/bin/terramate generate
Nothing to do, generated code is up to date
6.73s real		11.81s user		0.43s sys
➜  iac-gcloud git:(main) ✗ /usr/bin/time -h ~/src/terramate/bin/terramate generate
Nothing to do, generated code is up to date
6.72s real		11.84s user		0.43s sys
➜  iac-gcloud git:(main) ✗ /usr/bin/time -h ~/src/terramate/bin/terramate generate
Nothing to do, generated code is up to date
6.73s real …
```
=> chore(perf): disable type check for tm_try function.

stdlib/funcs_bench_test.go
It adds benchmarks to the `tm_alltrue()` and `tm_anytrue()` functions.
They are needed for the upcoming PRs optimizing these two functions.
```
no
```
=>  chore(perf): add benchmark for tm_alltrue and tm_anytrue.

docs/.vitepress/config.ts, docs/cli/editor-plugins/index.md
This PR adds a new section to the public documentation: 'Editor Plugins'. This section makes it easy for documentation readers to discover the {vscode,vim}-terramate extensions.
none
* I kept the documentation text short intentionally so that users are encouraged to navigate to the respective plugin README to find installation instructions / features etc.  
Yes, the [user-facing documentation](https://terramate.io/docs/cli) will be updated.
=> docs: add a new section for editor plugins

hcl/hcl.go, hcl/hcl_script.go, hcl/hcl_script_test.go
When multiple `script` blocks are declared with the same set of labels in the same directory, no error is shown. Just the first script found is used, and the others are ignored.
```
no, because scripts have not been released yet.
```
=> fix: fail if scripts are redeclared.

hcl/hcl.go
The error for duplicated set(string) entries was malformed:
```
✗ ./bin/terramate list
2023-12-13T13:29:02Z ERR terramate schema error: duplicated entry "scripts" in the index %!d(string=experiments) of field %!q(MISSING) of type set(string) file=/Users/tiagodemoura/src/terramate/terramate.tm:23,19-41
20
```
```
no, because script feature is not released yet.
```
=> fix(parser): malformed error message.

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/cli/script_info.go, cmd/terramate/cli/script_list.go, cmd/terramate/cli/script_tree.go, cmd/terramate/e2etests/core/script_info_test.go, cmd/terramate/e2etests/core/script_list_test.go, go.mod, go.sum, hcl/hcl_script.go, project/project.go
Three new experimental commands are added, related to the new scripts feature. For now, they are intended for debugging as they allow inspecting the script hierarchy.
Shows a list of all available scripts in the current directory. If there are multiple definitions, it uses the most parent definition, or the first sibling in case all definitions are on the same level.
Usage:
`terramate experimental script list`
Output:
```
deploy
some description
Defined at /
(+1 more)
stagify
do something
Defined at /stacks/stage
validate
some description
Defined at /
(+1 more)
```
Shows information about _a specific script_. For each definition, it lists the jobs and affected stacks.
Usage: 
`terramate experimental script info -- validate`
Output:
```
Definition: /scripts.tm.hcl:11,1-24,2
Description: …
```
=> chore(scripts): add debug commands for scripts

cmd/terramate/e2etests/core/script_info_test.go, project/project.go
The `HasDirPrefix` function used for scripts matching doesn't handle checking for the `/` prefix properly. This PR fixes it and adds a test case for it.
```
no
```
=> fix(scripts): dir prefix check works with root dir

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/cli/run_script.go, cmd/terramate/e2etests/core/run_script_test.go, cmd/terramate/e2etests/internal/runner/runner.go
In order to execute commands specified in `script` blocks, a new subcommand `run-script` is needed.
```
terramate experimental run-script myscript1
```
```
terramate experimental run-script --dry-run myscript1
```
```
terramate experimental run-script --changed myscript1
```
```
terramate experimental run-script --no-recursive myscript1
```
```
terramate experimental run-script --tags=sometag myscript1
```
```
terramate experimental run-script --no-tags=sometag myscript1
```
none
* ~the scriptsMatcher/search functionality was cherrypicked from https://github.com/terramate-io/terramate/pull/1275 (I will rebase onto that PR's branch once its ready)~
* I used plain strings instead of the `hclwrite.BlockBuilder` because I couldnt find a way to use variable interpolation in test strings (e.g. …
=> Add run-script subcommand

config/script.go, config/script_test.go
The `experimental run-script` gives the panic below if a job definition has an empty commands list:
```
$ terramate experimental script run a b
Found a b defined at /cmd/cmd.tm:1,1-6,2 having 1 job(s)
/cmd/terramate/e2etests/cloud/interop/testdata/interop-stacks/basic-drift (job:0.0)>
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/terramate-io/terramate/cmd/terramate/cli.makeCommand({0x1017aa8c0?, 0x1?, 0x14000156888?}, {0x1400026cfc0?, 0x14000021080?}, {0x14000388000?, 0x14000156888?, 0x1010412ec?}, {0x1012c2558?, 0x1400018a008?}, ...)
/Users/tiagodemoura/src/terramate/cmd/terramate/cli/run_script.go:128 +0x230
github.com/terramate-io/terramate/cmd/terramate/cli.(*cli).executeCommand(0x1400034bed0?, {0x1017aa8c0?, 0x1017aa8c0?, 0x0?}, …
```
=> fix: job command or commands items cannot be empty

docs/cli/installation.md
Fix the "downloads page" link but as the page does not exist the text have been adapted.
The problem was introduced by https://github.com/terramate-io/terramate/commit/0a111169d405edc37febf49528add8ac7b3f386b
```
yes, fix a link in the documentation.
```
=> docs: fix "download page" link.

cmd/terramate/cli/cli.go
This is making first time use error message more actionable.
run `terramate create` outside a Terramate Project.
```
$ terramate create out-side-of-project
Error: Terramate was unable to detect a project root.
Please ensure you run Terramate inside a Git repository or create a new one here by calling 'git init'.
Using Terramate together with Git is the recommended way.
Alternatively you can create a Terramate config to make the current directory the project root.
Please see https://terramate.io/docs/cli/configuration/project-setup for details.
```
instead of
```
2023-12-13T15:28:13+01:00 FTL Project root not found. If you invoke Terramate inside a Git repository, Terramate will automatically assume the top level of your repository as the project root. If you use Terramate in a directory …
```
=> chore: Replace the most annoying frist-time user error message

cloud/cloud.go, cloud/testserver/cloudstore/store.go, cloud/testserver/deployments.go, cloud/testserver/drifts.go, cloud/testserver/stacks.go, cloud/types.go, cmd/terramate/cli/cloud.go, strconv/doc.go, strconv/format.go, test/cloud/client.go
Some TMC endpoints have fields declared as `int64` integers (at least in theory because JSON can only store a maximum 2^53 integer value without loss) but CLI was unmarshaling into `int` (32 bits wide depending on the arch). The real motivation for this change is sticking to a size and using it for all ID-like fields. The new Pagination feature also has new fields defined as `int64`.
This is not a real problem at the moment but strictly following the OpenAPI spec is a good practice and some payloads are defined as `int64`. 
Additionally, by using int64 we are more future-proof in the case IDs are changed to not be serial anymore (unlikely, but who knows).
The #1304 had those changes because implementing pagination in the testserver led to the case of computing if a provided `stack_id` was …
=> chore: consistently uses int64 for TMC ids.

CHANGELOG.md, generate/generate.go, generate/generate_hcl_test.go, generate/generate_list_test.go, generate/generate_test.go, test/sandbox/sandbox.go
The `generator` was ignoring dot dirs/files while scanning the project for the detection of existing/changed/deleted files.
The issue existed since `v0.1.36` version, introduced in PR [#624](https://github.com/terramate-io/terramate/commit/51221de238bdd06668421f9d5427351d9724ff4a#diff-39a24c8d3907e38beb5e39b5f0a40df7aa73c38449615f140ec3fca502900e86R297).
Fixes #1260 
```
yes, it fixes a generate bug where dot files were always showing as "created" even if already in the disk.
```
=> fix(generate): dotfiles must not be ignored while detecting existing files.

cmd/terramate/cli/cloud.go, cmd/terramate/e2etests/cloud/run_cloud_deployment_test.go
A _Terramate Cloud_ organization name is case-insensitive.
```
no
```
=> chore(tmc): case-insensitive organization name.

docs/cli/cmdline/script/info.md, docs/cli/cmdline/script/list.md, docs/cli/cmdline/script/run.md, docs/cli/cmdline/script/tree.md
Explains in the docs that you must enable a config option to use the scripts features
```
no
```
=> docs: add explanation of how to enable experimental scripts feature

CHANGELOG.md, generate/generate.go, generate/generate_hcl_test.go, generate/generate_list_test.go, generate/generate_test.go, test/sandbox/sandbox.go
This reverts commit 394378ca5f17c2efb67bfcac83054a80abc705b0.
It introduces issues with Terraform modules downloaded that contain generated files.
```
no
```
=> chore: revert "fix(generate): dotfiles must not be ignored."

cmd/terramate/cli/cli.go
Only shows top-level commands in the `--help`. 
none
```
yes but it's just a cosmetic change.
```
=> chore: hide subcommands from --help.

docs/cli/code-generation/generate-hcl.md, generate/generate_hcl_test.go, generate/genhcl/genhcl.go, go.mod, go.sum, hcl/hcl.go, hcl/hcl_test.go, test/hclwrite/hclutils/utils.go
A new `stack_filter` block type is supported in `generate_hcl` blocks. This allows for improved path-based conditional generation. It can significantly improve performance when using path-based rules with lots of stacks.
```
A new block type is added to the configuration schema.
```
=> feat(generate): add stack_filter block

printer/doc.go, printer/printer.go, printer/printer_test.go
This PR adds a new abstraction for printing errors, warnings, and information that is more human readable than the existing logging statements. 
* Create a new package "printer"
* Add type Printer + convenience methods to print Errors, Warnings, Success, Information etc. in a consistent style
A [subsequent PR](https://github.com/terramate-io/terramate/pull/1323) uses the `printer` package to improve error messages emitted by `terramate run`.
no
=> chore: Add package for printing errors, warnings etc

printer/printer.go
The default printers can be used by other packages without haaving to
manage printer instances e.g.:
```
printer.StdErr.Errorln("")
printer.StdErr.Successln("")
```
This approach is similar to the standard library `log` package where
a default logger instance is pre-initialized.
See https://github.com/golang/go/blob/master/src/log/log.go
no
=> chore: Create default printers

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/core/exp_eval_test.go
The output of `eval`, `partial-eval` and `get-config-value` was being interpreted as Go's printf formatter.
Fixes #1327 
There are more places with incorrect usage of the function `MsgStdOut()` but they are harmless and will be fixed in a separate PR.
```
yes but in the output of the experimental commands (eval, partial-eval and get-config-value).
```
=> fix: experimental eval output interpreted as fmt.

cloud/types.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/github/types.go
The Terramate Cloud frontend needs the labels (if available) of the PR in each deployment.
Still no tests for GH integration.
```
no
```
=> feat(cloud): send labels in the deployment creation.

cmd/terramate/cli/github/types.go
The `encoding/json` uses a case insensitive matcher if an explicit `json:` tag is not used.
```
no
```
=> chore: add missing json tag to github.Commit.Commit field.

cmd/terramate/cli/cli.go, cmd/terramate/cli/run.go, cmd/terramate/e2etests/cloud/run_cloud_config_test.go, cmd/terramate/e2etests/cloud/run_cloud_deployment_test.go, cmd/terramate/e2etests/cloud/run_cloud_drift_test.go, cmd/terramate/e2etests/cloud/run_cloud_uimode_test.go, cmd/terramate/e2etests/core/exp_trigger_test.go, cmd/terramate/e2etests/core/general_test.go, cmd/terramate/e2etests/core/run_eval_test.go, cmd/terramate/e2etests/core/run_test.go, cmd/terramate/e2etests/core/run_unix_test.go, cmd/terramate/e2etests/core/safeguard_test.go, cmd/terramate/e2etests/core/version_check_test.go, printer/printer.go, run/order.go, stack/manager.go
This PR improves the output of `terramate run` using the `printer` package.
Main changes:
* Print error messages of run command using the printer package
* Print `terramate: Entering stack in stackpath` in run command
* not printed when `--quiet` is set
* Print `terramate: Executing command "echo hi"` in run command
* not printed when `--quiet` is set
* Improve dry-run output (remove old dry-run output completely)
* Improve warnings in run/run-order DAG processing
Depends on https://github.com/terramate-io/terramate/pull/1317
---
----
Yes, the output of the following commands has been improved:
* `terramate run somecmd`
* `terramate run --dry-run somecmd`
=> chore: Improve output of terramate run

cloud/types.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/github/client.go, cmd/terramate/cli/github/types.go, cmd/terramate/e2etests/cloud/interop/interoperability_test.go
The Terramate Cloud frontend needs the list of reviewers of each deployment.
Unfortunately no tests were added because it requires a GH API fake server.
```
no
```
=> feat(cloud): send reviewers in deployment creation.

CHANGELOG.md
- The `script` command was promoted out of the `experimental` sub-command and this change wasn't included in the CHANGELOG.
- The `stack_filter` block was not included in the CHANGELOG.
none
```
no
```
=> chore: fix CHANGELOG for next stable release.

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/core/debug_show_generate_test.go, cmd/terramate/e2etests/core/debug_show_globals_test.go, cmd/terramate/e2etests/core/debug_show_metadata_test.go, cmd/terramate/e2etests/core/imports_test.go, cmd/terramate/e2etests/core/run_test.go, cmd/terramate/e2etests/core/safeguard_test.go, cmd/terramate/e2etests/core/version_check_test.go, cmd/terramate/e2etests/internal/runner/runner.go, docs/cli/cmdline/globals.md, docs/cli/cmdline/metadata.md, docs/cli/cmdline/run-env.md, docs/cli/cmdline/run-graph.md, docs/cli/getting-started/index.md
The following commands are being promoted out of experimental:
* `experimental metadata` -> `debug show metadata`
* `experimental globals` -> `debug show globals`
* `experimental generate debug` -> `debug show generate-origins`
* `experimental run-env` -> `debug show runtime-env`
* `experimental run-graph` -> `debug render run-graph`
```
Yes, users must switch to the new command path for the above mentioned commands.
```
=> feat: promote experimental commands

docs/cli/code-generation/generate-hcl.md
Run `terramate fmt` in all examples in the generate-hcl docs
=> docs: correct formatting in generate-hcl docs

docs/.vitepress/config.ts, docs/cli/code-generation/generate-hcl.md
Correct generate-hcl docs to talk about partial evaluation instead of partial code generation (which doesn't exist)
=> Correct generate-hcl docs

cmd/terramate/cli/cli.go, cmd/terramate/cli/run_script.go, cmd/terramate/cli/script_info.go, cmd/terramate/e2etests/core/run_script_test.go, cmd/terramate/e2etests/core/script_info_test.go, config/config.go
If `scripts` is not enabled we must give a good error message explaining how to enable them.
```
no other than better error.
```
=> fix: script commands abort if not enabled

git/git.go, git/git_test.go, git/options.go
When creating the git wrapper, a couple of commands need to be executed to check if the wrapper is properly working in the given working directory. But in an upcoming PR, the git wrapper will be reused across different packages but in some cases a slightly different instance of the wrapper is needed. This refactor makes it possible to clone a wrapper with different options.
Example:
```go
gw1, _ := git.WithConfig(config)
gw2 := gw1.With().WorkingDir(otherDir).Wrapper()
```
The `gw1` and `gw2` are different pointers but the `gw1` config is copied and customized to a different working directory in the `gw2`. So after the call, `gw2` and `gw1` can be used independently.
```
```
=> chore: refactor git wrapper for cloning.

cmd/terramate/cli/cli.go, cmd/terramate/cli/project.go, cmd/terramate/e2etests/core/list_git_test.go, stack/manager.go, stack/manager_test.go
The Terramate change detector does not load user's global config and then is unable to ignore files configured in the `core.excludeFiles` option.
This fixes a reported bug where the user had a global `.gitignore` configuration but Terramate kept complaining of untracked files in the repository.
Fixes an issue reported by a customer but not tracked in GitHub.
- Depends on #1358
- I removed the @snakster implementation for retrieving global config (the inner vs outer wrappers) because they are not needed anymore.
- Now Terramate uses a single git wrapper with the exception that module change detector needs a different Workdir but that's the only different option.
```
no
```
=> fix: change detector cannot read user's git config.

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/core/safeguard_test.go, cmd/terramate/e2etests/core/version_check_test.go, cmd/terramate/e2etests/internal/runner/runner.go, docs/cli/cmdline/run-graph.md
The `run-graph` command needs to be improved to support the following feature:
* A reverse option to render the graph in reverse order (or reverse the direction of the arrows)
```
Yes, the `run-graph` command is being moved to `experimental`.
```
=> fix: move run-graph back to experimental

docs/cli/cmdline/eval.md
The `experimental eval` does not support FS related functions and this was undocumented until now.
Fixes #1365 
```
no
```
=> docs: document functions not available in the eval.

cmd/terramate/cli/run_script.go, config/script.go, config/script_test.go
This PR adds support for an optional options object at the end of the command list. This is part of supporting cloud deployment sync for scripts.
* The options don't do anything yet, this will be done in a future PR. They are just parsed and validated for now.
```
no
```
=> chore(scripts): add support for command options

generate/generate_hcl_test.go, generate/genhcl/genhcl.go, hcl/hcl.go
After some investigation it seems there is a bug in the glob library we use with certain pattern combinations:
```
g := glob.MustCompile("{**/project-factory/*/custom-roles/*,**/projects/*/landing-zone/custom-roles/*", '/')
const p = "stacks/project-factory/factory-1/custom-roles/role-1"
g.Match(p) // false, should be true
```
This PR adds a workaround by matching each pattern individually. It also escapes reserved special characters in patterns.
```
no
```
=> fix: multiple stack_filter patterns did not match in some cases

cloud/cloud.go
This PR redacts the Authorization header from API debugging output (when `TMC_API_DEBUG=1` is set) to prevent leaking credentials.
```
No. This is a change to the API debugging output only.
```
=> fix: redact authorization header in API debug output

CHANGELOG.md, generate/generate_stack_file_test.go, generate/genfile/genfile.go, generate/genhcl/genhcl.go, hcl/hcl.go, hcl/hcl_test.go
This PR allows the `stack_filter` block that was added in #1307 for `generate_hcl` to be used with `generate_file` as well.
It's only supported with `context = stack`.
```
A new block type is added to the configuration schema.
```
=> feat(generate): allow stack_filter for generate_file

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/cloud/exp_trigger_cloud_test.go, cmd/terramate/e2etests/cloud/interop/interoperability_test.go, cmd/terramate/e2etests/cloud/list_cloud_test.go, cmd/terramate/e2etests/cloud/run_cloud_uimode_test.go, docs/cli/cmdline/cloud-drift-show.md, docs/cli/cmdline/cloud-info.md, docs/cli/cmdline/cloud-login.md, docs/cli/cmdline/list.md, docs/cli/cmdline/trigger.md
- feat: promote experimental cloud commands
- feat: promote exp trigger status to --cloud-status
- feat: promote list status to --cloud-status
* I created one PR for all the changes to avoid the extra work of reviewing/merging multiple PRs.
* I tested that each commit is functional using this command:
- git rebase --exec "make test" main
```
Yes, it moves some commands and flags out of experimental. The docs have been
updated to reflect this. For details of each change, see the commit messages.
```
=> feat: promote experimental cloud commands and flags

docs/cli/orchestration/scripts.md
Just fixing some minor typos in the scripts documentation
=> Fix typos in scripts documentation

CHANGELOG.md, cloud/testserver/cloudstore/store.go, cloud/types.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/cloud_sync_deployment.go, cmd/terramate/cli/cloud_sync_drift.go, cmd/terramate/cli/run.go, cmd/terramate/cli/script_run.go, cmd/terramate/e2etests/cloud/run_cloud_deployment_test.go, cmd/terramate/e2etests/cloud/run_cloud_drift_test.go, cmd/terramate/e2etests/core/run_script_test.go, config/script.go, config/script_test.go, docs/cli/orchestration/scripts.md
This PR implements cloud deployment syncing similar to `terramate run --cloud-sync-deployment`, but for individual script commands.
* The `ExecContext` was extended and has also been renamed in the process. It was used in many places and the variables had a different name each time, i.e. `run, runContext, stackContext, stacks, runStacks`. Refactored this so its always `run`/`runs`.
* The output of `script run` was changed so that code between `run` and `script run` could be re-used more easily.
```
- Support for optional script command options have been added, which allow syncing deployment info to Terramate Cloud.
- The output formatting of terramate script run has been changed slightly.
```
=> feat(scripts): support for deployment cloud sync

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/cli/clitest/messages.go, cmd/terramate/e2etests/core/run_test.go, cmd/terramate/e2etests/core/safeguard_test.go, docs/cli/configuration/index.md, docs/cli/orchestration/safeguards.md, hcl/hcl.go, hcl/hcl_test.go, safeguard/doc.go, safeguard/safeguard.go
Introduces the flag `--disable-safeguards=<list of options>` and `terramate.config.disable_safeguards` configuration option. The options are:
| keyword            | meaning     |
| ------------------ | ----------- |
| git-untracked      | Disables the check for untracked files       |
| git-uncommitted    | Disables the check for uncommitted files     |
| git-out-of-sync    | Disables the check for git remote out of sync |
| outdated-code      | Disables the check for outdated code          |
Additionally, the following group keywords are supported:
| keyword            | meaning     |
| ------------------ | ----------- |
| git                | Disables all git related checks |
| all                | Disables all checks |
| none               | Re-enables all checks (if disabled by the …
=> feat: introduce --disable-safeguards=<options>

cmd/terramate/cli/cli.go
Fix help text to show possible values for `--disable-safeguards` flag.
=> fix: show possible options for --disable-safeguards in help

docs/cli/getting-started/index.md
Adds a missing code example to the getting started section.
=> Add missing null provider code example to getting started guide

cmd/terramate/cli/run.go, cmd/terramate/e2etests/cloud/run_cloud_deployment_test.go
This PR adds support for using the `terramate run` options  `--cloud-sync-deployment` and `--cloud-sync-terraform-plan-file` in combination. It will attach information from a given Terraform planfile to the cloud deployment status.
Note that the plan must exist before the run is executed.
* The core of this functionality had already been implemented in #1355, because scripts is using the same code path.
* This is not tested via test server yet, because it wasn't clear to me which endpoint to use to query the result. This will be done in a later PR, together with adding tests for the scripts' variant of this feature.
```
It allows a new combination of flags that was previously not supported.
```
=> chore(cloud): add support attaching planfiles to synced deployments

CHANGELOG.md, cmd/terramate/cli/script_run.go, cmd/terramate/e2etests/cloud/run_cloud_deployment_test.go, cmd/terramate/e2etests/core/run_test.go
Fixes `script run` to respect the stack ordering defined in the stack configuration.
Fixes an issue reported in discord.
```
fixes a major issue
```
=> fix: stack ordering not respected in script run.

CHANGELOG.md, config/script.go, config/script_test.go
The script block evaluator is not handling lists but just tuples.
Example below shows the problem:
```
script "cmd" {
description = "aaa"
job {
command = true ? tm_concat(["echo"], ["something"]) : []
}
}
```
It fails with error below:
```
test:1,1-4,15: invalid type for script.command: command must be a list but got list of string
```
```
```
=> fix(script): command and commands disallow list types.

cmd/terramate/cli/cli.go, cmd/terramate/cli/run.go, cmd/terramate/cli/script_run.go, run/order.go
The list of stacks that needs to be ordered for `script run` execution uses different data types than for `run`, which makes it difficult to re-use. This PR makes the sorting function more flexible so it can be used with both data types.
* The interface of the sort function changes from returning the sorted list as a new list, to sorting in-place. However, even before the passed list was modified with `sort.Sort()`, so this is at least obvious now.
```
no
```
=> chore: refactor run.Sort stack ordering

cmd/terramate/cli/cli.go, docs/cli/cmdline/index.md
Deprecates the flags `--disable-checkpoint` and `--disable-checkpoint-signature`.
none
```
no
```
=> refactor: deprecate flags --disable-checkpoint*

cloud/cloud.go
The `Request.Clone()` function is misleading, it does not create a copy of the original request's body, resulting in dumprequest+printf draining the original request's body.
See https://github.com/golang/go/issues/36095
```
No.
```
=> fix: use req.GetBody when dumping req

.github/workflows/ci.yml, .github/workflows/release-dryrun.yml, hack/version-check, makefiles/unix.mk
This PR skips testing when there are no code changes. This should should speed up the following PR types:
* the PRs where only the markdown files in root are changed (e.g. CHANGELOG.md, README.md etc)
* The PRs where only `VERSION` is changed (e.g. https://github.com/terramate-io/terramate/pull/1407)
Changes in this PR:
* Ignore markdown files and `VERSION` in the ci job
* Move release-dryrun job to release-dryrun.yml
* Run release-dryrun.yml only when `VERSION` is changing.
```
No
```
=> chore: ignore some paths in ci checks

CHANGELOG.md, docs/cli/stacks/manage.md
- docs: rename cloud-status flag
- docs: add --detailed-exit-code to changelog (it was missing)
```
No.
```
=> docs: rename cloud-status flag

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/core/fmt_test.go, cmd/terramate/e2etests/internal/runner/runner.go, hcl/fmt/fmt.go, hcl/fmt/fmt_test.go
Introduces the ability to format individual files or `stdin` with the `terramate fmt` command.
Example:
Individual files:
```
$ terramate fmt terramate.tm stacks/my-stack/stack.tm
```
Stdin:
```
$ terramate fmt -
format this input ^D
$ echo $?
1
```
Format current directory (old behavior):
```
$ terramate fmt
```
Fixes #1226 
```
yes, new arguments list for `fmt`
```
=> feat: fmt of individual files and stdin.

CHANGELOG.md, ls/ls.go, ls/ls_test.go
When an error happens while looking for the root config, the language server panics with the stack trace below:
```
2024-02-10T14:38:52Z DBG handling request. action=server.Handler() method=textDocument/didOpen params={"textDocument":{"languageId":"terramate","text":"terramate {\n    config {\n        git {\n            default_branch = \"trunk\"\n        }\n    }\n}\n","uri":"file:///Users/tiagodemoura/src/vscode-terramate/testFixture/invalid/multiple-tm-config-git/tm2.tm","version":1}} workspace=/Users/tiagodemoura/src/vscode-terramate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1012a3d04]
goroutine 8 [running]:
github.com/terramate-io/terramate/config.(*Root).Tree(...) …
```
=> fix(ls): panic when failing to load root config.

run/order.go, run/order_test.go
I noticed that the change to the `run.Sort()` of script commands I made in #1413 does not use stable sorting, which as far as I understand, could lead to script commands being executed in the wrong order. However, I was not able to reproduce this with a test case. I still think it's a good idea to use stable sort here.
```
no
```
=> fix: ensure order of script commands is preserved after sorting

cloud/cloud.go, cloud/log_syncer.go, cloud/log_syncer_test.go, cloud/testserver/cloudstore/store.go, cloud/testserver/stacks.go, cloud/types.go, cmd/terramate/cli/run.go
* Rename `DeploymentLog` to `CommandLog`
* Rename `DeploymentLogs` to `CommandLogs`
* Rename `SyncDeploymentLogs` to `SyncCommandLogs`
This refactoring was done to re-use the log syncer for preview runs.
```
No.
```
=> chore: refactor DeploymentLog{s} to CommandLog{s}

cloud/cloud.go, cloud/cloud_preview.go, cloud/cloud_preview_test.go, cloud/preview/preview.go, cloud/preview/preview_test.go, cloud/types.go, cloud/types_preview.go, cmd/terramate/cli/clitest/messages.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/cloud_sync_drift.go, cmd/terramate/cli/cloud_sync_terraform_plan.go, cmd/terramate/cli/github/event.go, cmd/terramate/cli/github/event_test.go, cmd/terramate/cli/run.go, cmd/terramate/e2etests/cloud/interop/interoperability_test.go, cmd/terramate/e2etests/cloud/interop/testdata/interop-stacks/basic-terraform/main.tf, cmd/terramate/e2etests/cloud/interop/testdata/interop-stacks/basic-terraform/stack.tm.hcl
Submit per stack preview progress (status updates + changeset) to TMC
* As the commands are running, their respective status changes are submitted to TMC
* If a command has a changeset, the changset is submitted to TMC
* The preview status for a stack is determined by the exit code of the preview command and whether the terraform plan had changes
* Abort preview when env var `GITHUB_EVENT_PATH` is missing
* The `GITHUB_EVENT_PATH` environment variable is used to determine the `updated_at` field of the pull request. If the variable is missing, the preview should be aborted. However the run command should still be executed (wtih cloud features disabled).
Depends on https://github.com/terramate-io/terramate/pull/1436
* The fake http transport was enhanced to support different behaviour for …
=> feat: submit stack preview progress to TMC

CHANGELOG.md, cloud/cloud.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/run.go
Submit logs generated as part of a preview run to TMC.
Depends on https://github.com/terramate-io/terramate/pull/1443
The implementation re-uses the already existing DeploymentLogLines type to submit logs to TMC.
```
Yes the logs of a preview run are submitted to TMC.
```
=> feat: submit preview logs to TMC

cmd/terramate/cli/github/event.go, cmd/terramate/cli/run.go
This should fix the panic in the interop tests.
```
No.
```
=> fix: handle github event parsing gracefully

docs/cli/code-generation/functions/tm_can.md, docs/cli/code-generation/functions/tm_cidrsubnet.md, docs/cli/code-generation/functions/tm_coalescelist.md, docs/cli/code-generation/functions/tm_csvdecode.md, docs/cli/code-generation/functions/tm_filemd5.md, docs/cli/code-generation/functions/tm_filesha1.md, docs/cli/code-generation/functions/tm_filesha256.md, docs/cli/code-generation/functions/tm_filesha512.md, docs/cli/code-generation/functions/tm_format.md, docs/cli/code-generation/functions/tm_formatdate.md, docs/cli/code-generation/functions/tm_indent.md, docs/cli/code-generation/functions/tm_jsonencode.md, docs/cli/code-generation/functions/tm_matchkeys.md, docs/cli/code-generation/functions/tm_one.md, docs/cli/code-generation/functions/tm_parseint.md, docs/cli/code-generation/functions/tm_range.md, docs/cli/code-generation/functions/tm_regex.md, docs/cli/code-generation/functions/tm_regexall.md, docs/cli/code-generation/functions/tm_rsadecrypt.md, docs/cli/code-generation/functions/tm_setsubtract.md, docs/cli/code-generation/functions/tm_ternary.md, docs/cli/code-generation/functions/tm_textdecodebase64.md, docs/cli/code-generation/functions/tm_timeadd.md, docs/cli/code-generation/functions/tm_timestamp.md, docs/cli/code-generation/functions/tm_try.md, docs/cli/code-generation/functions/tm_urlencode.md, docs/cli/code-generation/functions/tm_yamldecode.md, docs/cli/code-generation/functions/tm_yamlencode.md
This PR addresses typos in the functions documentation section at Terramate docs ([link](https://terramate.io/docs/cli/code-generation/functions)). It mostly deals with the missing `tm_` prefix, but also some examples are mistyped.
yes, on the docs website
=> docs: fix documentation typos in tm_* functions

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/core/create_all_terraform_test.go, cmd/terramate/e2etests/core/create_all_terragrunt_test.go, cmd/terramate/e2etests/core/create_test.go, docs/cli/cmdline/create.md
Introduces the `terramate create --all-terragrunt` command for initializing Terramate stacks from Terragrunt modules.
no
Depends on #1434 
```
yes, add a new flag.
```
=> feat: add terramate create --all-terragrunt.

CHANGELOG.md, cmd/terramate/cli/script_info.go, cmd/terramate/cli/script_list.go, cmd/terramate/cli/script_tree.go, cmd/terramate/e2etests/core/script_list_test.go, config/script.go, config/script_test.go, docs/cli/orchestration/scripts.md, hcl/hcl_script.go
Add an optional `script.name` attribute. This is purely a cosmetic change.
Now the commands `terramate script info`, `terramate script list` and `terramate script tree` show the name if available. Example below:
none
```
yes, a new script.name attr added.
```
=> feat: add script.name attribute.

cmd/terramate/cli/cloud.go, cmd/terramate/cli/github/event.go, cmd/terramate/cli/github/event_test.go, cmd/terramate/cli/run.go
Read PR information from the GHA pull_request event when available, otherwise
fall back to the Github API.
The fallback only happens when building the ReviewRequest object in
detectCloudMetadata().
There is no fallback for `preview.updated_at`.
```
No.
```
=> fix: use PR info from event when available, otherwise API

CHANGELOG.md, cloud/cloud.go, cloud/cloud_test.go, cmd/terramate/cli/cli.go
The filtering of stacks by repo is implemented client side instead of using the API filter.
This will make the `--cloud-status` flag faster and less brittle (atm it fails in the case other repositories are returning non-conformant `drift_status`).
none
This PR targets `v0.5.0` but I will make another PR backporting it to `v0.4.6`.
```
no
```
=> fix(cloud): use repository filter in stacks listing.

CHANGELOG.md, cloud/cloud.go, cloud/cloud_test.go, cmd/terramate/cli/cli.go
Backports #1476 to `v0.4.6`.
none
Change cherry-picked from #1476 
```
fix a bug
```
=> fix(cloud): use repository filter in stacks listing (backports to v0.4.6)

cmd/terramate/cli/cloud.go, cmd/terramate/cli/run.go
* Use debug logs for printing stack preview status update messages.
* Use debug logs when a PR cannot be fetched
* Print the `Entering stack` messages before executing cloud sync logic.
```
No.
```
=> chore: log debug messages when creating preview

cmd/terramate/cli/cloud.go
Fix an issue in preview status that is not set to `failed` if the plan is not generated.
none
```
no because previews are not released
```
=> fix(prefix): set preview status failed when plan fails.

cloud/cloud.go, cmd/terramate/cli/cloud.go
When using `--cloud-sync-deployment` and `--cloud-status` the latter flag reset the `c.cloud` field and then losing the computed deployment UUID.
none
```
no because --cloud-status with run is not released.
But v0.5.0 release candidates are unable to create deployments with `--cloud-status` flag set.
```
=> fix(tmc): --cloud-status feature overwrite deployment UUID.

cloud/testserver/deployments.go, cloud/testserver/drifts.go, cloud/testserver/metadata.go, cloud/types.go, cmd/terramate/cli/cloud.go, cmd/terramate/e2etests/cloud/run_cloud_config_test.go, cmd/terramate/e2etests/cloud/run_cloud_deployment_test.go, cmd/terramate/e2etests/cloud/run_cloud_drift_test.go, cmd/terramate/e2etests/cloud/run_cloud_signal_test.go, cmd/terramate/e2etests/cloud/run_cloud_uimode_test.go
The `metadata` is optional but we were lacking tests for their collection in Terramate.
This improves the situation by checking for at least the `git` metadata in the testserver.
Note: this does not change Terramate behavior, just tests.
none
In order to enable the metadata collection we need to set a remote git URL but it cannot be a `github.com` url because if so it will try to collect Github metadata and fail.
```
no
```
=> chore: add basic tests for metadata.

cmd/terramate/cli/github/event.go, cmd/terramate/cli/github/event_test.go
Fix failing test below:
```
--- FAIL: TestGetEventPR (0.00s)
--- FAIL: TestGetEventPR/non_existent_path (0.00s)
equal.go:123: wanted[open /tmp/does-not-exist: no such file or directory] but got[open /tmp/does-not-exist: The system cannot find the path specified.]
FAIL
```
It can be seen here (if still available): https://github.com/terramate-io/terramate/actions/runs/8072983613/job/22055794565?pr=1490
none
```
no
```
=> chore: fix github event tests for Windows.

cloud/cloud.go, cloud/types.go, cmd/terramate/cli/cli.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/github/event_test.go, cmd/terramate/cli/github/testdata/event_pull_request.json, cmd/terramate/cli/run.go
When using `--cloud-sync-preview` this will write the preview URL in a file named `preview_url.txt` at the project root.
no
```
no
```
=> feat: provides the preview url at /preview_url.txt

cloud/types.go
The `draft` field must not have an `omitempty` JSON tag because we need to explicitly tell the backend when the draft status changed.
no
```
no
```
=> fix(preview): draft field not sent when false.

docs/.vitepress/config.ts
Shows the correct commands in the sidebar of the documentation website. Experimental commands are excluded. I also removed a dead link "run-order" and created a redirect for to redirect the dead link to the list page.
=> Fix commands in sidebar

docs/cli/cmdline/get-config-value.md
Fixes wrong reference of the `get-config-value` command in the CLI docs
=> Fix get-config-value command usage example

docs/cli/cmdline/generate.md
Refines the `terramate generate` command documentation to include `[options]` in the usage section.
Yes, it updates the documentation of the `terramate generate` command and its options.
=> docs: refine terramate generate command usage

docs/cli/cmdline/eval.md
Refines the `terramate eval` command documentation 
Yes, it updates the documentation to clarify the usage of the `terramate eval` command
=> docs: refine terramate eval command usage

docs/cli/cmdline/clone.md
This PR refines the documentation for the `terramate clone` command, ensuring the usage section reflect required and optional command components, enhancing usability and adherence to Terramate documentation standards.
Yes, it updates the documentation to provide clearer guidance on using the `terramate clone` command, including adjustments to the usage syntax .
=> docs: refine terramate clone command usage

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/cli/run.go
Add `-cloud-sync-layer` to `terramate run`. This would allow users to create
previews for a specific terraform workspace e.g. `staging`, `prod` etc.
```
Yes, a new flag --cloud-sync-layer has been added to terramate run.
```
=> feat: add --cloud-sync-layer to terramate run

CHANGELOG.md, hcl/ast/expr.go, hcl/ast/expression_test.go
The old escaping logic did multiple passes on the input data, each modifying the input, which led to the issue of re-rendering of escape sequences.
Fixes #1449 
```
yes
```
=> fix: heredoc escape symbols not properly handled.

CHANGELOG.md, cloud/preview/preview.go, cmd/terramate/cli/cli.go, cmd/terramate/cli/run.go, cmd/terramate/cli/script_run.go, cmd/terramate/e2etests/core/run_script_test.go, config/script.go, config/script_test.go
Add `cloud_sync_preview` option to script block.
Depends on https://github.com/terramate-io/terramate/pull/1493
```
Yes, users will be able to use the `cloud_sync_preview` option in the script block to store previews in TMC.
```
=> feat(scripts): add cloud_sync_preview + cloud_sync_layer

docs/.vitepress/config.ts, docs/cli/orchestration/scripts.md
Renames "Terramate Scripts" to "Workflows" in sidebar.
Terramate Scripts is the feature but that doesn't ring a bell when a user reads this. Instead, workflows is a commonly known name. Hence we rename this to "Configure Worklows with Terramate Scripts"
=> Rename scripts to workflows in documentation

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/cli/run.go, cmd/terramate/cli/script_run.go, cmd/terramate/e2etests/cloud/run_cloud_deployment_test.go, cmd/terramate/e2etests/cloud/run_cloud_drift_test.go, cmd/terramate/e2etests/cloud/run_cloud_signal_test.go, cmd/terramate/e2etests/cloud/run_script_cloud_deployment_test.go, cmd/terramate/e2etests/cloud/run_script_cloud_drift_test.go, cmd/terramate/e2etests/core/run_parallel_test.go
This PR adds support for supplying a parameter to the short form of the `--parallel`flag, i.e. `-j N`.
It also removes the default value, so the long version always needs a value.
```
no
```
=> chore: support -j N syntax for parallel flag and remove default value

docs/cli/cmdline/list.md
This PR refines the `terramate list` command documentation for better clarity and adherence to the Terramate Documentation Guide, specifically updating the usage section and examples.
Yes, it updates the documentation to enhance user understanding and application of the `terramate list` command.
=> docs: refine terramate list command usage and examples

docs/cli/cmdline/fmt.md
Refines the `terramate fmt` command documentation. This includes updating usage instructions, clarifying deprecated options, and enhancing the description of command options.
Yes, it updates the documentation to provide clearer guidance on the `terramate fmt` command, its options, and usage.
=> docs: refine terramate fmt command documentation

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/core/create_all_terragrunt_test.go, docs/cli/cmdline/create.md, tg/tg_library_sanity_test.go, tg/tg_module.go, tg/tg_module_test.go
Add detection for Terragrunt dependencies and automatically populates the `stack.after` of created stacks using `terramate create --all-terragrunt`.
none
```
yes
```
=> feat: add ordering support for --all-terragrunt.

cloud/types.go, cmd/terramate/cli/cloud_sync_deployment.go, cmd/terramate/cli/cloud_sync_drift.go, cmd/terramate/cli/run.go, cmd/terramate/e2etests/cloud/run_cloud_drift_test.go
This would allow users to sync stack logs for stacks having uppercase (or mixed case) stack ids.
```
Yes, this would allow users to sync stacks with uppercase (or mixed case) stack
ids to Terramate Cloud.
```
=> fix: use lower case stack.id for lookup

cmd/terramate/cli/cloud_sync_drift.go
Increases the `terraform show` timeout to `60s`.
none
```
no
```
=> chore: increase terraform show timeout.

CHANGELOG.md, cmd/terramate/cli/cloud.go, cmd/terramate/cli/run.go, cmd/terramate/cli/script_run.go
Fix a similar issue as of #1551 but this time in the map of `metaID -> previewIDs`.
none
```
no
```
=> fix: lookup of previewIDs by case-insensitive stack IDs.

cmd/terramate/cli/cloud.go
Improve the warning message in the case Terramate fails to generate the ASCII or JSON plan details.
none
```
no
```
=> chore: improve warn message in case changeset fails.

cloud/testserver/cloudstore/store.go, cloud/testserver/cloudstore/store_test.go, cloud/testserver/previews.go, cmd/terramate/e2etests/cloud/run_cloud_sync_preview_test.go
Makes use of `mu.Lock()` in the `AppendPreviewLogs()` because `sp.Logs` is being mutated.
As the stack previews need to be updated in the handlers, then it was changed to store a list of pointers so the brittle code below is avoided:
```
for spIndex, sp := range p.StackPreviews {
for _, sp := range p.StackPreviews { // THIS CREATES A COPY OF SP
if sp.ID == stackPreviewID {
sp.Logs = append(sp.Logs, logs...)
p.StackPreviews[spIndex] = sp // THIS UPDATES WITH THE NEW COPY
return nil
}
}
}
```
Another example is changes like:
```
org.Previews[i].StackPreviews[spIndex].Status = preview.StackStatus(status)
```
If the value must be mutated by several entities, then better be a pointer protected by mutex than values copied over and also protected by mutex.
Targets #1533 
none
@wmalik if you …
=> tests: fix race condition by acquiring wrong lock.

docs/cli/cmdline/run.md
Fixing typos on documentation, `parallel` instead of `prallel`.
```
no
```
=> docs: fix typo on parallel examples

CHANGELOG.md, cloud/cloud.go, cloud/testserver/stacks.go, cmd/terramate/e2etests/cloud/interop/interoperability_test.go, cmd/terramate/e2etests/cloud/run_cloud_deployment_test.go, cmd/terramate/e2etests/cloud/run_cloud_drift_test.go
The `terramate cloud drift show` command does not work with stacks containing uppercase in the `stack.id`.
none
```
```
=> fix(cloud): cloud drift show doesn't work with uppercase stack ids.

cmd/terramate/cli/cloud.go, cmd/terramate/e2etests/cloud/run_script_cloud_sync_preview_test.go
Fix missing plan file details in TMC when using previews via scripts.
```
Bug fix for TMC users.
```
=> fix(scripts): use correct value for plan file path in previews

CHANGELOG.md, cmd/terramate/cli/script_info.go, cmd/terramate/cli/script_list.go, cmd/terramate/cli/script_tree.go, config/script.go, config/script_test.go, hcl/hcl_script.go, hcl/hcl_script_test.go, test/hcl.go
Now it's possible to give a meaningful name and description to each `script.job` block.
none
```
yes, a new feature.
```
=> feat: add script.job.name and script.job.description.

cmd/terramate/e2etests/cloud/interop/interoperability_test.go
This PR backports the fix for interop tests in 0.4.x.
```
No.
```
=> fix: use --quiet flag in interop tests

CHANGELOG.md, docs/cli/code-generation/index.md, generate/generate.go, generate/generate_test.go
Disallow code generation inside dot directories.
Note: this is a breaking change.
Examples below will not work anymore:
```hcl
generate_hcl ".terraform/myfile.tf" {
content {}
}
generate_hcl "somedir/other/.dotdir/myfile.tf" {
content {}
}
generate_hcl "somedir/other/.dotdir/test/myfile.tf" {
content {}
}
```
In the cases above, note that part of the file path contains a "dot directory".
Relates to #1260 
I split the PR for fixing the dotfile bug because the disallowing dotdirs is related but not actual part of the bugfix, then by having this separate is easier if a rollback is needed.
Note: this is a breaking change.
```
yes, this is a breaking change.
```
=> refactor!: disallow code generation inside dotdirs.

CHANGELOG.md, cmd/terramate/cli/project.go, hcl/hcl.go, hcl/hcl_test.go
Removes the configuration `terramate.config.git.default_branch_base_ref`.
```
yes, it's a breaking change.
```
=> refactor!: remove terramate.config.git.default_branch_base_ref attr.

CHANGELOG.md, generate/generate.go, generate/generate_hcl_test.go, generate/generate_list_test.go, generate/generate_test.go
Fix a bug where dot files were not detected when already present in the filesystem and them re-generation occurs.
Fixes #1260 
```
```
=> fix(generate): generate cleanup deletes dotfiles.

CHANGELOG.md, stack/manager.go, stack/manager_test.go
Enable the detection of changes in dotfiles.
*Note: this is a breaking change*
@soerenmartius @mariux It looks like we never documented that dotfiles were ignored in the change detection. Should we explicit document this now or is it clear that they are treated the same as any other file? See [here](https://terramate.io/docs/cli/change-detection/integrations/git)
none
```
yes
```
=> feat!: enable dotfile change detection.

CHANGELOG.md, cmd/terramate/cli/cli.go, stack/clone.go, stack/clone_test.go
Fix the cloning of stacks that contains imports.
Fixes #1390 
```
yes, bug is fixed.
```
=> fix: clone stacks with imports.

docs/cli/orchestration/scripts.md
Document the `cloud_sync_preview` option for synchronizing previews to Terramate Cloud.
none
```
no
```
=> docs: cloud_sync_previen option in script commands. 

docs/cli/code-generation/index.md, docs/cli/stacks/nesting.md
Correcting a spelling mistake in the docs.
=> doc: correcting typo

cmd/terramate/e2etests/cloud/run_cloud_signal_test.go, cmd/terramate/e2etests/internal/runner/runner_signal_fixture.go, cmd/terramate/e2etests/internal/runner/runner_unix.go
Undo #1490 because it results in spurious test failures. Indicates that we have problem with Signal handling on MacOS, must be investigated further and fixed before we can re-enable. 
```
no
```
=> chore: undo re-enable signal tests for MacOS

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/cli/cloud_sync_terraform_plan.go, cmd/terramate/cli/run.go, cmd/terramate/cli/script_run.go, cmd/terramate/e2etests/core/run_test.go, config/script.go, config/script_test.go, docs/cli/cmdline/run.md, docs/cli/orchestration/scripts.md, docs/cloud/deployments/synchronization-with-scripts.md, docs/cloud/drifts/synchronization-with-scripts.md, docs/cloud/previews/synchronization-with-scripts.md
This PR adds a new option flag `--terragrunt` to `terramate run` and the equivalent `terragrunt = true` script command option. This instructs the CLI to use the `terragrunt show` when generating a plan file instead of `terraform show`. In the future this flag may enable other terragrunt-specific behaviour that should be used when using terramate to invoke terragrunt.
* There are no elaborate tests for this yet, just tests to ensure that the option flag is parsed.
```
Yes, it adds a new flag and script option.
```
=> feat: add --terragrunt option for run and scripts

CHANGELOG.md, cloud/preview/preview.go, cmd/terramate/cli/cli.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/run.go, cmd/terramate/cli/script_run.go, cmd/terramate/e2etests/cloud/cloud_status_test.go, cmd/terramate/e2etests/cloud/exp_trigger_cloud_test.go, cmd/terramate/e2etests/cloud/interop/interoperability_test.go, cmd/terramate/e2etests/cloud/run_cloud_config_test.go, cmd/terramate/e2etests/cloud/run_cloud_deployment_test.go, cmd/terramate/e2etests/cloud/run_cloud_drift_test.go, cmd/terramate/e2etests/cloud/run_cloud_signal_test.go, cmd/terramate/e2etests/cloud/run_cloud_sync_preview_test.go, cmd/terramate/e2etests/cloud/run_cloud_uimode_test.go, cmd/terramate/e2etests/cloud/run_script_cloud_deployment_test.go, cmd/terramate/e2etests/cloud/run_script_cloud_drift_test.go, cmd/terramate/e2etests/cloud/run_script_cloud_sync_preview_test.go, cmd/terramate/e2etests/cmd/helper/main.go, cmd/terramate/e2etests/internal/runner/runner_signal_fixture.go, config/script.go, config/script_test.go, makefiles/common.mk
This PR renames all `--cloud-*` flags to `--*` to make the options more accessible. The old flags are still supported as aliases, but not shown in help or error messages.
Same goes for script command options, where `cloud_*` command option prefix is dropped.
```
Yes. Flags are renamed and promoted, but the old ones are still supported.
```
=> refactor: remove cloud flag prefix

CHANGELOG.md, cmd/terramate/e2etests/core/generate_test.go, config/config.go, generate/generate.go, generate/generate_hcl_test.go, generate/generate_stack_file_test.go, generate/genfile/genfile.go, generate/genhcl/genhcl.go, hcl/hcl.go, hcl/hcl_test.go
Introduces the `inherit` attribute to both `generate_hcl` and `generate_file` to control when the blocks should be inherited in child stacks.
none
```
yes
```
=> feat: add generate_*.inherit attribute.

.github/workflows/ci.yml
We never had an issue with incompatible macos version then this PR disables the old one for improving CI feedback/performance.
none
```
no
```
=> chore: disable macos-12 in the CI.

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/core/create_test.go, config/stack.go, hcl/printer.go, stack/create.go
Add support for `--watch` in the `terramate create`.
When provided the user can populate the `stack.watch` attribute of the created stack.
none
```
yes, add a new feature.
```
=> feat: add terramate create --watch=<opt1,...>

CHANGELOG.md, ls/ls.go, ls/ls_test.go, test/ls/fixture.go
When the user creates a new directory (not inside a repository) and starts writing Terramate files, the language server panics while detecting the project `rootdir` and loading the experiments.
none
```
yes, fixes a bug
```
=> fix(ls): panic when workspace is not detected as Terramate project.

CHANGELOG.md, stack/manager.go
Terragrunt integration seems stable then this PR removes the need for adding it to `experiments` config.
none
```
no
```
=> refactor: promote Terragrunt integration to stable.

CHANGELOG.md, cmd/terramate/e2etests/cloud/run_script_cloud_deployment_test.go, cmd/terramate/e2etests/cloud/run_script_cloud_drift_test.go, cmd/terramate/e2etests/cloud/run_script_cloud_sync_preview_test.go, config/script.go, config/script_test.go
In the previous release, the flags `--cloud-sync-terraform-plan-file` and `--cloud-sync-layer` were shorted to `--terraform-plan-file` and `--layer`, but the script option for both still had the `sync_` prefix. This PR shortens them further to `terraform_plan_file` and `layer`, so everything is aligned. As before, the old names are still supported.
```
Two script options are renamed, old names (including the `sync_*` ones) are still supported.
```
=> fix: naming of cloud script options

CHANGELOG.md, generate/generate_hcl_test.go, hcl/hcl.go
Fixes a problem that generate blocks with `inherit=false` are not generated if the blocks are imported and inherited in child stacks.
Thanks @ckd
Reported on discord: https://discord.com/channels/1088753599951151154/1229901710319685692/1230006750325768192
```
```
=> fix: generate inherit=false not working when imported.

.github/workflows/ci.yml
Fixes the version of Terraform used in CI tests.
The ubuntu runners were upgrade to use `Terraform v1.8.0` and the Plan JSON output has an additional field that breaks our expected case. We will relax the plan file comparator later in a separate PR.
none
```
no
```
=> tests: uses a fixed version of Terraform in tests.

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/core/fmt_test.go
Fix a bug that `fmt --detailed-exit-code` exits before actual saving the files.
Fixes #1649 
```
```
=> fix: fmt --detailed-exit-code not saving the files.

hcl/hcl_stack_test.go, hcl/hcl_test.go, test/hcl.go
While adding tests for a new feature, once again I realised some fields were not being matched in the asserts. This improves the situation by doing a `cmp.Diff()` in the entire config AST.
Luckily all tests were okay, just minor differences between `nil` and empty slice.
none
I caught the issue while adding tests for the `terramate.config.change_detection.terragrunt` block. I did this in a separate PR to create awareness of the problem.
```
no
```
=> test: improve HCL config asserts.

CHANGELOG.md, cmd/terramate/cli/cli.go, config/config.go, config/stack.go, generate/generate.go, globals/globals_test.go, hcl/hcl.go, hcl/hcl_test.go, stack/manager.go, stack/manager_test.go, stack/stack.go, stack/stack_test.go, test/sandbox/sandbox.go
Introduces the `terramate.config.change_detection.terragrunt.enabled` attribute supporting the options below:
- `auto`: detects if Terragrunt modules are present and enables automatically.
- `off`: turn off the integration.
- `force`: do Terragrunt change detection even if no Terragrunt module is detected.
Relates to #1656 
Additional changes were required because the `config.Root` was not a singleton.
```
yes, adds a new feature.
```
=> feat: add terramate.config.change_detection.terragrunt option.

CHANGELOG.md, cmd/terramate/e2etests/core/list_test.go, hcl/hcl.go, hcl/hcl_import_test.go, hcl/hcl_test.go
Fix incorrect warnings emitted by the parser when `terramate.config.run.env` is declared in child directories.
none
```
```
=> fix: incorrect warnings emitted by the parser.

.github/workflows/release.yml
This PR installes the goreleaser pro binary in the release action
=> ci: install goreleaser-pro in the release action

.github/workflows/release.yml
Released failed with:
```
⨯ release failed after 0s                  error=git is in a dirty state
Please check in your pipeline what can be changing the following files:
M README.md
?? LICENSE.md
?? completions/
?? goreleaser.tar.gz
?? manpages/
````
none
```
no
```
=> fix: goreleaser should be extracted outside repo dir.

CHANGELOG.md, cmd/terramate/cli/cloud.go
This PR fixes a bug in handling paginated responses from the Github API that can be triggered while fetching metadata for PR reviews and GHA checks.
We have no automated tests for this, so I only verified doing a manual test.
Setup:
```
$ export GITHUB_EVENT_PATH=${terramate_repo}/cmd/terramate/e2etests/cloud/interop/testdata/event_pull_request.json
$ cd ${terramate_repo}/cmd/terramate/e2etests/cloud/interop/testdata/interop-stacks/basic-drift
$ CI=true GITHUB_ACTIONS=1 terramate run --sync-drift-status --terraform-plan-file="out.tfplan" -- terraform plan --detailed-exitcode -out=out.tfplan
```
Before, error:
```
WRN failed to retrieve PR reviews error="context deadline exceeded" github_repository=terramate-io/terramate head_commit=daaf4f0505b853071a09b9f72daec559919730ed …
```
=> fix: broken pagination in Github API calls

CHANGELOG.md, cmd/terramate/cli/cloud.go
Backport #1702 to `v0.6.x`.
none
```
yes, fixes a bug
```
=> Backport to v0.6.x: fix: unchecked nil dereference in metadata

CHANGELOG.md, hcl/eval/eval.go, run/env_test.go
Fixes a bug in the processing of Go's environ, which has the form `NAME=VALUE` but the value can also contain equal signs.
Fixes #1710 
```
```
=> fix: run.env not including complete env var.

CHANGELOG.md, generate/genhcl/dynamic_test.go, generate/genhcl/genhcl.go, generate/genhcl/genhcl_test.go
Allow map type in the `tm_dynamic.attributes`.
none
```
yes, fixes a usage limitation.
```
=> fix: allow map type in tm_dynamic.attributes.

cmd/terramate/cli/cli.go, cmd/terramate/e2etests/core/exp_eval_test.go, generate/genhcl/dynamic_test.go, generate/genhcl/genhcl.go, generate/genhcl/genhcl_test.go, generate/genhcl/partial_eval_test.go, hcl/ast/value.go, hcl/eval/eval.go, hcl/eval/partial_eval.go, hcl/eval/partial_eval_bench_test.go, hcl/eval/partial_eval_test.go, hcl/eval/partial_fuzz_test.go, hcl/hcl.go, stdlib/ternary.go
Enhances the #1714 by adding tracking of unknown functions and a reducer for simplifying the partial evaluated expressions into literals when no unknowns are present. This is a separate PR only for easy the review, it should be merged into #1714.
=> chore: reducer for final partial evaluated code and unknown function tracker.

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/e2etests/core/exp_eval_test.go, cmd/terramate/e2etests/core/generate_test.go, generate/genhcl/dynamic_test.go, generate/genhcl/genhcl.go, generate/genhcl/genhcl_test.go, generate/genhcl/partial_eval_test.go, hcl/ast/expr.go, hcl/ast/value.go, hcl/eval/eval.go, hcl/eval/partial_eval.go, hcl/eval/partial_eval_bench_test.go, hcl/eval/partial_eval_test.go, hcl/eval/partial_fuzz_test.go, hcl/hcl.go, stdlib/ternary.go
This change makes it possible to use Terramate variables in `[for k, v in collection : ... if cond]` and `{for k, v in collection : ... if cond}` when `collection` and `cond` *does not* depend on unknowns. In other words, the cases below are now possible:
```
globals {
numbers = [1, 2, 3]
strings = ["terramate", "is", "fun"]
partials_config = {
aws = "aws.vpc.id", 
azre = "azure.thing"
}
}
generate_hcl "example.tf" {
content {
square_numbers = [for n in global.numbers : n*n]
upper_strings  = [for s in global.strings : tm_upper(s)]
config = {for k, v in global.partials_config : k => tm_hcl_expression(v)}
}
}
```
which generates the file `example.tf` below:
```
cat example.tf
// TERRAMATE: GENERATED AUTOMATICALLY DO NOT EDIT
config = {
aws  = aws.vpc.id
azre = azure.thing
}
square_numbers = …
```
=> feat: for-expr with variables in generate_hcl.content

cmd/terramate/cli/cloud.go, cmd/terramate/cli/run.go, cmd/terramate/e2etests/cloud/run_cloud_sync_preview_test.go, cmd/terramate/e2etests/cloud/run_script_cloud_sync_preview_test.go
Improves the error messages when synchronizing commands and GITHUB_TOKEN is not exported.
Before it gave the error below:
```
2024-02-23T17:03:03Z WRN failed to retrieve commit information from GitHub API error="GET https://api.github.com/repos/terramate-io/terramate-quickstart-aws/commits/d74239b4e91562a2c12994cbd6de9b86680b1378: 404 Not Found []" github_repository=terramate-io/terramate-quickstart-aws head_commit=d74239b4e91562a2c12994cbd6de9b86680b1378 normalized_repository=github.com/terramate-io/terramate-quickstart-aws
2024-02-23T17:03:03Z WRN failed to retrieve pull requests associated with HEAD error="GET https://api.github.com/repos/terramate-io/terramate-quickstart-aws/commits/d74239b4e91562a2c12994cbd6de9b86680b1378/pulls?per_page=1: 404 Not Found []" …
```
=> chore: improve warn messages in case GITHUB_TOKEN is not exported.

CHANGELOG.md, cmd/terramate/cli/run.go, cmd/terramate/e2etests/cloud/run_cloud_deployment_test.go, cmd/terramate/e2etests/cloud/run_script_cloud_deployment_test.go
Currently, even if `--parallel=<n>` is provided, all stacks have its status changed to `running` right away, even if they are still queued to be executed.
none
```
yes, improves cloud experience.
```
=> fix: only set status=running before executing the command.

CHANGELOG.md, cmd/terramate/e2etests/core/script_run_test.go, config/script.go, config/script_lets_test.go, config/script_test.go, hcl/eval/eval.go, hcl/eval/partial_eval.go, hcl/hcl.go, hcl/hcl_script.go, hcl/hcl_script_test.go, hcl/hcl_test.go, test/hclwrite/hclutils/utils.go
Add support for `lets` variables in the `script` block.
The block work in the same way as the `lets` block in the `generate_*` blocks.
Multiple blocks are merged into the same. See example below:
```
script "deploy" {
lets {
name = "script name"
cmd = ["echo", "hello ${let.project}"]
}
lets {
project = "my project"
}
job {
command = let.cmd
}
}
```
The script above works and it's the same as if all lets variables were defined in the same block.
Fixes #1382 
```
yes, new feature
```
=> feat: introduce script.lets.

CHANGELOG.md, cmd/terramate/cli/cli.go, e2etests/cloud/exp_trigger_cloud_test.go
The `-C` is not being respected by the `terramate experimental trigger --status` command.
none
```
```
=> fix: experimental trigger must respect working directory.

CHANGELOG.md, cmd/terramate/cli/cli.go, e2etests/core/exp_trigger_test.go, e2etests/internal/runner/runner.go, stack/manager.go, stack/trigger/trigger.go, stack/trigger/trigger_test.go
Introduce the `ignore-change` trigger. This kind of trigger can be used when a set of changes would trigger stacks when should not, then the user can now force them to not trigger as changed in the same PR.
Usage example:
```
$ terramate list --changed
my-stack
$ terramate experimental trigger --ignore-change my-stack
Created trigger for stack "/my-stack"
$ terramate list --changed
$ 
```
As you can see, after the trigger file is created with `--ignore-change` the stack is not listed as changed anymore. The same is true for the other features supporting `--changed`.
Fixes none
```
yes, adds a new feature.
```
=> feat: add triggers of type ignore-change.

CHANGELOG.md, cmd/terramate/cli/cli.go, e2etests/core/exp_trigger_test.go
When using the `terramate experimental trigger` providing a non-existent stack path, the error message complains about symlinks not being supported when in fact the error should be "stack not found".
none
```
yes, fixes a bug
```
=> fix: trigger with misleading error message when stack is not found.

stack/trigger/trigger.go, stack/trigger/trigger_test.go
When using `trigger --ignore-change` the filename has the pattern `changed-.*` instead of `ignore-change-.*`.
None
```
yes but no changelog entry is needed because this is unreleased.
```
=> fix: trigger type not used in the filename.

CHANGELOG.md, cmd/terramate/cli/cli.go, e2etests/core/exp_trigger_test.go, e2etests/internal/runner/runner.go
Add a `--recursive` flag to `terramate experimental trigger` for triggering all stacks of a given base path.
none
```
yes, adds a new feature.
```
=> feat: add trigger --recursive flag.

CHANGELOG.md, config/filter/filter.go, config/filter/filter_test.go
This PR fixes a crash due to a missing bounds check when parsing a tag list that contains a trailing comma.
```
no
```
=> fix: crash when tag list contains trailing comma

cmd/terramate/cli/cli.go, config/config.go, e2etests/core/general_test.go, hcl/hcl.go
A legacy code for detecting misconfiguration causes a rescan of the configuration tree while discovering the rootdir.
none
```
no
```
=> perf: avoid rescan of configuration.

CHANGELOG.md, cloud/cloud.go, cloud/cloud_test.go, cloud/deployment/status.go, cloud/deployment/status_test.go, cloud/drift/status.go, cloud/drift/status_test.go, cloud/stack/status.go, cloud/testserver/stacks.go, cloud/types.go, cmd/terramate/cli/cli.go, cmd/terramate/cli/run.go, cmd/terramate/cli/script_info.go, cmd/terramate/cli/script_run.go, e2etests/cloud/cloud_status_test.go, e2etests/cloud/exp_trigger_cloud_test.go
Introduce `terramate [list,run] --[deployment,drift]-status=<status>` flags.
none
```
yes, adds a new feature.
```
=> feat: terramate list --deployment-status=<status> and --drift-status=<status>

.golangci.yml
The default 5 minutes linting timeout is not enough anymore for Terramate. We are having sporadic Ci runs failing on main.
none
```
no
```
=> chore: increase linting timeout.

cloud/types.go, cmd/terramate/cli/cloud_sync_terraform_plan.go, e2etests/cloud/run_cloud_drift_test.go, e2etests/cloud/run_script_cloud_drift_test.go
This PR sends the serial from the Terraform tfstate alongside the changeset details. This allows TMC to potentially discard data from older plans that would otherwise replace newer data.
```
no
```
=> feat(cloud): sync plan serial with changeset data

CHANGELOG.md, cmd/terramate/cli/script_run.go
When using `terramate script` there's a missing check for `GITLAB_CI` which prevents previews from being created.
You can circumvent the issue for now if you export `GITHUB_ACTIONS=1` in the Gitlab pipeline.
none
```
yes
```
=> fix(gitlab): missing GITLAB_CI check in scripts.

CHANGELOG.md, cmd/terramate/cli/cloud.go
The commit SHA used in the ReviewRequest payload must come from the Gitlab API.
none
```
yes, fixes the deployment review request in TMC sync.
```
=> fix(gitlab): commit SHA must come from the GitLab API.

cmd/terramate/cli/cloud.go, cmd/terramate/cli/run.go
The `pushed_at` information cannot be obtained in drifts or deployments.
none
```
no
```
=> fix(gitlab): only set rr.pushed_at in previews.

generate/generate.go, generate/generate_sharing_test.go, generate/sharing/sharing_backend.go
Fixes the deletion of orphaned files configured by input/output blocks.
Depends on #1812 
none
Depends #1812 
```
no, the feature is not released.
```
=> fix(generate): deletion of orphaned sharing files.

makefiles/unix.mk, makefiles/windows.mk
The e2e `outputs-sharing` tests are slower due to the amount of commands executed by terramate in involved stacks, which made tests around 30% slower in my laptop.
=> chore: increase go test timeout.

CHANGELOG.md, cmd/terramate/cli/run.go, e2etests/core/run_parallel_test.go
At the moment, we can't run pipelines from fork contributions, then we need to cherry-pick the commits in a separate PR, to run CI and merge the contribution. The original authorship is kept.
none
This apply the contribution from #1830 and add a CHANGELOG entry.
```
yes, fixes a deadlock in the orchestration.
```
=> fix: release locking resource when continuing through run loop

cmd/terramate/cli/run.go, e2etests/core/run_parallel_test.go
Note: this is just a quick fix and a refactor in this code path is being worked on.
This fixes a missing `releaseResource()` that led to a deadlock in the case that user-supplied command does not exist. The fix also release the resource in all other code paths that abort the execution, for correctness purposes, but AFAICS they are optional.
Relates to #1828
A refactor in the outputs-sharing handling is being designed.
```
yes, fixes a --parallel bug.
```
=> fix(parallel): deadlock in case command does not exist.

CHANGELOG.md, cmd/terramate/cli/run.go, e2etests/core/run_parallel_test.go
=> Backport: fix: release locking resource when continuing through run loop

cmd/terramate/cli/run.go, e2etests/core/run_parallel_test.go
Backport #1832 to v0.9.x
Note: The PR was adjusted because "sharing-outputs" experiment is only in v0.10.x
=> Backport: fix(parallel): deadlock in case command does not exist

cmd/terramate/cli/run.go, e2etests/core/run_sharing_test.go, e2etests/internal/runner/runner.go
If a stack orchestration fails for any reason and `--continue-on-error` is provided, then the current stack execution must abort and continue on the next stack.
none
```
yes, fixes an issue introduced by outputs-sharing (unreleased).
```
=> fix: --continue-on-error must always continue on next stack.

CHANGELOG.md, cmd/terramate/cli/cloud_sync_deployment.go, cmd/terramate/cli/cloud_sync_drift.go, cmd/terramate/cli/run.go, cmd/terramate/cli/script_run.go, config/sharing_backend.go, config/sharing_backend_test.go, e2etests/cloud/run_cloud_deployment_test.go, e2etests/cloud/run_script_cloud_deployment_test.go, e2etests/cloud/run_script_cloud_drift_test.go, e2etests/cloud/run_script_cloud_preview_test.go
It fixes the `outputs-sharing` experiment not synchronizing failure cases to Terramate Cloud.
none
```
yes, fixes a bug in v0.10.1
```
=> fix(tmc): outputs sharing failure cases not synced to TMC.

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/cli/script_run.go, config/assert_test.go, config/script_lets_test.go, config/script_test.go, config/sharing_backend_test.go, generate/generate.go, globals/stack.go, go.mod, go.sum, hcl/eval/eval_test.go, hcl/eval/partial_eval_bench_test.go, hcl/eval/partial_eval_test.go, hcl/hcl.go, run/env.go, stack/eval.go, stdlib/funcs.go, stdlib/funcs_bench_test.go, stdlib/funcs_test.go, stdlib/toml.go, stdlib/toml_test.go, stdlib/try_test.go
Add `tm_tomlencode()` and `tm_tomldecode` functions.
Closes #1804 
```
yes, add a new feature.
```
=> feat: add toml encoder/decoder functions

CHANGELOG.md, e2etests/cmd/helper/main.go, git/url.go, git/url_test.go
Fix the git URI normalization in the case that URI path component begin with a number. Eg.: `git@github.com:123me/project.git`
The number was misinterpreted as a port number.
none
```
```
=> fix: git URI normalization failed for projects with leading number.

CHANGELOG.md, go.mod
The `go install` stopped working because of an incorrect `replace` directive left in `go.mod`.
none
```
yes, fixes installation.
```
=> fix: install is broken because of replace directive.

CHANGELOG.md, cmd/terramate/cli/run.go, e2etests/cloud/run_cloud_deployment_test.go, generate/generate_sharing_test.go, generate/sharing/sharing_backend.go
Change default sharing backend type to be `any` instead of `string`.
Closes #1861 
```
yes, add support for any input type.
```
=> feat: make inputs of type 'any' by default.

e2etests/core/generate_test.go, e2etests/core/safeguard_test.go, generate/generate.go, generate/outdated_detection_test.go
Fix the safeguard not triggering for `generate_file.context == root` case.
none
```
```
=> fix: generate_file.context=root not handled in the safeguards.

e2etests/core/run_test.go, run/order.go
In case a stack contains invalid paths in `after/before/wants/wanted_by` the offended stack should be in the warning output.
none
```
yes but just enhances the output.
```
=> chore: improve warning message to contain offended stack.

.github/workflows/ci-sync-deployment.yml, .github/workflows/ci-sync-preview.yml, e2etests/cloud/stack.tm.hcl, e2etests/cmd/helper/stack.tm.hcl, e2etests/core/stack.tm.hcl, e2etests/internal/runner/stack.tm.hcl, generate_preview.tm
This change ensures e2e tests run whenever a Go package changes.
none
```
no
```
=> chore: run e2e tests whenever a Go package changes.

generate/generate.go
Small optimization to avoid re-sorting of outdated files.
none
```
no
```
=> chore: optimize DetectOutdated by avoiding re-sorting.

.github/workflows/benchmark.yml
Only run benchmarks if the modified files are Go files and benchmark test files.
In other words, do not run if just tests (not bench) were modified.
Reason: lots and lots of CI minutes being wasted.
none
```
no
```
=> test: only run benchmarks on changed implementation Go files.

CHANGELOG.md, config/config.go, generate/generate.go, generate/generate_list_test.go, generate/outdated_detection_test.go, test/sandbox/sandbox.go
The outdated safeguard handling logic is descending into stack subdirs even when its parent stack was already handled.
Issue reported in Discord.
```
```
=> fix: outdated safeguard descending into stack child dirs.

hcl/hcl.go
This removes the log lines below:
```
➜  terramate git:(i4k-generate-log-disabling) ✗ ./bin/terramate generate --log-level=debug
2024-09-27T09:33:04+01:00 DBG Get git version. action=Version() workingDir=/Users/tiagodemoura/src/terramate
2024-09-27T09:33:05+01:00 DBG Parsing stack cfg. action=parseTerramateSchema() dir=/Users/tiagodemoura/src/terramate
2024-09-27T09:33:05+01:00 DBG Get stack attributes. action=parseStack()
2024-09-27T09:33:05+01:00 DBG Parsing stack cfg. action=parseTerramateSchema() dir=/Users/tiagodemoura/src/terramate/globals
2024-09-27T09:33:05+01:00 DBG Get stack attributes. action=parseStack()
2024-09-27T09:33:05+01:00 DBG Parsing stack cfg. action=parseTerramateSchema() dir=/Users/tiagodemoura/src/terramate/cmd/terramate-ls
2024-09-27T09:33:05+01:00 DBG Get stack …
```
=> chore: remove useless logs.

CHANGELOG.md, cmd/terramate/cli/cli.go, e2etests/core/create_test.go, stack/create.go
Implements `terramate create --wants ...` and `terramate create --wanted-by ...`.
The flag works the same as `--after`, `--before`, etc, it creates the stack with the given values in the `stack.wants` and `stack.wanted_by` respectively.
none
```
yes, add new feature.
```
=> feat: add create --wants and --wanted-by flags.

CHANGELOG.md, config/config.go, config/stack.go, e2etests/core/debug_show_metadata_test.go
The runtime variable `terramate.stack.path.basename` gives the value `\` for a stack at repository root on Windows. Terramate shall never return a Windows based path.
none
Note: Windows CI is broken for quite some time 😞 
```
yes, fixes an issue.
```
=> fix: root stack has terramate.stack.path.basename=\ on Windows.

config/config.go, fs/fs.go, fs/fs_bench_test.go, hcl/fmt/fmt.go, hcl/hcl.go, stack/manager.go
Reuse the discovered file paths from the configuration loader.
none
```
no, just improves performance.
```
=> chore: reduce the fs syscalls by using file paths from tree.

CHANGELOG.md, benchmarks/changed/changed_bench_test.go, cmd/terramate/cli/cli.go, cmd/terramate/cli/run.go, config/config.go, e2etests/core/change_detection_test.go, e2etests/core/run_test.go, git/git.go, git/git_test.go, hcl/hcl.go, hcl/hcl_test.go, stack/manager.go, stack/manager_test.go
**This is a breaking change**
This change considers untracked and uncommitted files in the change detection.
It means `terramate list --changed` will show stacks changed by uncommitted or untracked files in the index. The `terramate run` safeguards will continue to kick in but the user can disable the `git` safeguards and in this case commands can run in dirty stacks.
Closes #1398 
```
yes, it's a breaking change that needs documentation!
```
=> feat: consider untracked/uncommitted in the change detector.

CHANGELOG.md, e2etests/core/change_detection_test.go, stack/manager.go
The **ignore triggers** do not ignore stack changes if they were marked by Terraform or Terragrunt module changes.
none
```
yes, fixes a trigger bug.
```
=> fix: trigger --ignore-change don't ignore stacks changed due to TF module changes

cmd/terramate/cli/cli.go
This flag was planned to be added to `experimental trigger` but later realized as not needed but I forgot to rollback. This is not released, just introduced in #1904 and does not need a changelog update.
none
```
no
```
=> fix: remove unneeded flag added to trigger command.

.github/workflows/ci-experimental.yml
Fixes two issues in Windows CI:
1. `core.crlf` was set after project was already cloned, then files were being converted.
2. `core.crlf` must be set to `input` to keep original EOL (we don't want conversions).
none
```
no
```
=> ci: use core.autocrlf=input to avoid LF conversions on Windows checkout.

e2etests/cloud/run_script_cloud_preview_test.go
The script preview tests were embedding a host path in the command string but Windows paths need backlash escaping for Windows. Instead of escaping, the fix is to just use "terraform" and rely on the %Path% environment having the Terraform installation directory prepended.
none
```
no
```
=> test: fix preview tests on Windows.

CHANGELOG.md, config/tag/tag.go, e2etests/cloud/cloud_status_test.go, e2etests/cloud/interop/testdata/interop-stacks/basic-drift/stack.tm.hcl, e2etests/cloud/interop/testdata/interop-stacks/empty/stack.tm.hcl, e2etests/core/run_test.go, stack.tm.hcl
Relax the tag parser to allow dots.
A tag must:
- start with an alphabetical lowercase character: `a-z`
- contain any alphanumerical (`0-9a-z`), `-`, `.` or `_` in the middle. **<- CHANGED**
- and end with an alphanumerical: `0-9a-z`
none
```
yes, add a feature.
```
=> feat: allow dots in tags.

CHANGELOG.md, config/sharing_backend.go, config/sharing_backend_test.go, generate/generate_sharing_test.go, generate/sharing/sharing_backend.go
Backport of https://github.com/terramate-io/terramate/pull/1926 to `v0.10.x` branch.
none
```
yes, change the behavior.
```
=> refactor(sharing_outputs): no default value for the sensitive fields.

.github/workflows/ci-sync-deployment.yml
Fix CI to run deployments on backporting branches as well. This fixes the issue of PRs left open in TMC.
none
```
no
```
=> ci: improve CI to deploy also backporting branches.

.github/workflows/ci-sync-deployment.yml
Terramate CI rollout releases in `main` and `vX.Y.x` branches. The PR #1933 works for previews but broke the TMC deployment because push events has no `github.base_ref` variable.
The solution is to compare against first parent commit (the default in Terramate but not in branches other than main);
none
```
no
```
=> ci: fix change detection in push event.

.github/workflows/ci-sync-deployment.yml
Fix a missing case, sorry about that. This is a continuation of #1938 
none
```
no
```
=> ci: fix another case in push event.

generate/genhcl/genhcl.go, hcl/ast/expr_clone.go, hcl/eval/partial_eval.go, mapexpr/map.go, stdlib/ternary.go
The in-place AST modifications were a nice optimization when generation was serial but with the introduction of #1937 it's racy.
none
```
no
```
=> chore: avoid in-place modifications of AST nodes in the partial evaluation

.github/workflows/benchmark.yml, .github/workflows/ci-experimental.yml, .github/workflows/ci-sync-deployment.yml, .github/workflows/ci-sync-preview.yml, .github/workflows/interop-tests.yml, .github/workflows/release.yml, makefiles/common.mk
For security reasons we should pin the github action versions.
A `make pin-gha` command is added to automate this.
none
```
no
```
=> chore: pin github actions.

CHANGELOG.md, config/stack.go, e2etests/core/debug_show_metadata_test.go, e2etests/core/run_sharing_test.go
Implements `terramate.stack.parent.id` metadata for stacks that has parent stacks.
none
```
yes, add a new feature
```
=> feat: add terramate.stack.parent.id.

CHANGELOG.md, config/config.go, config/config_test.go, constants.go, e2etests/core/fmt_test.go, e2etests/core/generate_test.go, generate/generate.go, generate/generate_hcl_test.go, generate/generate_list_test.go, generate/generate_test.go, generate/genhcl/genhcl_test.go, generate/genhcl/partial_eval_test.go, generate/outdated_detection_test.go, globals/globals_test.go, hcl/fmt/fmt.go, hcl/fmt/fmt_test.go, test/sandbox/sandbox.go
Fixes the `terramate fmt` command not respecting the `.tmskip`.
Fixes #1952 
```
```
=> fix: fmt not respecting .tmskip file.

cmd/terramate/cli/cli.go, e2etests/core/change_detection_test.go, project/project.go, stack/manager.go, test/sandbox/sandbox.go
While fixing #1971 another problem was identified that prevented the fix.
The `project.PrjAbsPath()` function had many misuses that worked by luck in many cases but the other fix depends on this one.
none
```
no
```
=> chore: refactor project paths in change detection.

CHANGELOG.md, stack/manager_test.go, test/git.go, tg/tg_module.go, tg/tg_module_test.go
Fix the Terragrunt change detection for the case the `terraform.source` references a local directory.
Fixes #1959 
```
```
=> fix: change detection of Terragrunt module source.

go.mod, go.sum
Address a go-gh security issue.
Cherry pick https://github.com/terramate-io/terramate/pull/1978
because forked contributions cannot run in our CI
=> chore(deps): bump github.com/cli/go-gh/v2 from 2.1.0 to 2.11.1

CHANGELOG.md, cmd/terramate/cli/cli.go, e2etests/core/create_all_terragrunt_test.go
When Terragrunt modules are nested, Terramate generates stacks with `after` references to parent stacks, then creates a cycle because child stacks have an implicit dependency on parent stacks.
Closes #1774 
```
```
=> fix: create --all-terragrunt creates Terragrunt stacks with cycles.

CHANGELOG.md, cmd/terramate/cli/cli.go, cmd/terramate/cli/cliconfig/cliconfig.go, cmd/terramate/cli/cliconfig/cliconfig_test.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/script_run.go, cmd/terramate/cli/telemetry/_test_mock.tf, cmd/terramate/cli/telemetry/endpoint.go, cmd/terramate/cli/telemetry/endpoint_localhost.go, cmd/terramate/cli/telemetry/record.go, cmd/terramate/cli/telemetry/record_test.go, cmd/terramate/cli/telemetry/stack.tm.hcl, cmd/terramate/cli/telemetry/telemetry.go, cmd/terramate/cli/telemetry/telemetry_test.go, generate/generate.go, generate/genfile/genfile.go, generate/genhcl/genhcl.go, hcl/hcl.go, hcl/hcl_test.go
This PR adds telemetry to collect metrics about which commands are used most actively. We already have some general insights from the checkpoint API, but this gives more detailed data.
Documentation will be updated accordingly.
```
- telemetry options have been added
```
=> feat: add telemetry

CHANGELOG.md, cmd/terramate/cli/cli.go, e2etests/core/create_all_terragrunt_test.go, project/project.go, tg/tg_module.go
Fix panic in the case of a Terragrunt module references a dependency outside of the Terramate project.
This changed adds a warning for such cases because this is not supported in Terramate at the moment.
Fixes #1979 
```
yes, fixes a panic in the Terragrunt integration.
```
=> fix: warn if Terragrunt dependency is outside project.

CHANGELOG.md, go.mod, stack/manager_test.go, tg/funcs.go, tg/tg_module.go, tg/tg_module_test.go
Track usage of `file()` in Terragrunt modules to enhance change detection and mark stacks as changed whenever dependent files change.
Fixes #1967
```
yes, add a new feature
```
=> feat: track file() usage in Terragrunt change detection.

CHANGELOG.md, cmd/terramate/cli/cli.go, e2etests/core/create_all_terragrunt_test.go
Add `terramate create --all-terragrunt --tags a,b,c`.
Fixes #1966 
```
yes, add --tags to `create --all-terragrunt`.
```
=> fix: add terramate create --all-terragrunt --tags a,b,c

cmd/terramate/cli/cli.go
This fixes a missing send in one code path.
```
no
```
=> fix: missing send for create all metrics

CHANGELOG.md, tg/tg_module.go, tg/tg_module_test.go
Due to an incorrect assumption in the Terragrunt module detection, the dependency paths were wrong.
Thanks @LittleWat for the bug report and for providing a reproducible repository.
Fixes #1979 
```
yes, fixes a bug in the Terragrunt module detection.
```
=> fix: incorrect detected paths in Terragrunt modules.

CHANGELOG.md
The backported releases were missing in the CHANGELOG.
I will adjust the release process so this won't happen again.
none
```
no
```
=> chore: fix changelog missing backporting releases.

CHANGELOG.md, stack/manager.go, stack/manager_test.go
Fix a panic in the case a Terraform module has module calls with source outside of the project root directory.
Fixes #2012 
```
yes, fixes a panic.
```
=> fix: panic if Terraform module references path outside repository.

cloud/types.go, cmd/terramate/cli/bitbucket/bitbucket.go, cmd/terramate/cli/cloud.go
Additionally sync the PR author UUID in the TMC `review_request.author.id` field.
none
```
no
```
=> chore(bitbucket): send rr.author.id with PR author UUID.

cmd/terramate/cli/cloud.go
Sync the reviewer id in the `rr.reviewers[i].id`.
none
```
no, it's part of the unreleased bitbucket support.
```
=> chore: sync bitbucket reviewer ID.

CHANGELOG.md, cmd/terramate/cli/run.go, e2etests/core/run_env_test.go, run/env.go, run/lookpath_unix.go, run/lookpath_windows.go
Newer versions of Terragrunt transform the user-supplied command output and redirect stdout/stderr and this does not work well with Terramate, which always respects the user command stdout/stderr.
This change exports `TERRAGRUNT_FORWARD_TF_STDOUT=true` and `TERRAGRUNT_LOG_FORMAT=bare` in order to force Terragrunt to keep old behavior.
none
```
yes fixes an issue found at a customer.
```
=> fix(terragrunt): make Terragrunt keep command output as is.

CHANGELOG.md, cmd/terramate/cli/cloud_sync_terraform_plan.go
Fix Terramate Cloud plan creation command not using environ defined in `terramate.config.run.env`. This can lead to a version mismatch between the user-supplied run command and the one used for creating the plan details.
none
```
fix TMC plan creation.
```
=> fix: tmc plan creation command not using `terramate.config.run.env`.

cmd/terramate/cli/cloud_sync_terraform_plan.go, cmd/terramate/cli/run.go, e2etests/cloud/run_cloud_deployment_test.go, e2etests/cmd/helper/main.go, e2etests/cmd/helper/terragrunt.go, e2etests/core/run_env_test.go, e2etests/internal/runner/setup.go, fs/copy.go
As discussed, it's better if we export the `TERRAGRUNT_FORWARD_TF_STDOUT` and `TERRAGRUNT_LOG_FORMAT` only during the changeset details.
no
```
not released yet
```
=> fix(terragrunt,tmc): only export TG envs during changeset creation.

cloud/cloud.go, cmd/terramate/cli/tmcloud/auth/oidc_audience_terramate.go, cmd/terramate/cli/tmcloud/cloud.go
This is required for an upcoming change in the CLI configuration for setting the Terramate Cloud region.
none
```
no
```
=> chore: add support for region in the TMC sdk.

cloud/cloud_preview.go, cloud/cloud_preview_test.go, cmd/terramate/cli/run.go
The CLI configuration has attributes for configuring the Terramate Cloud client SDKs then it makes sense to reuse code by importing the cloud package in the config (to avoid duplicating the types).
At the moment, it's the other way around and `config.Stack` is used in the cloud package but this is wrong because the cloud types are owned by the Terramate Cloud backend team and we already have a `cloud.Stack` type that comply with the openapi spec.
none
```
no
```
=> chore: avoid config package dependency in the cloud sdk package.

cloud/cloud.go, cmd/terramate/cli/cli.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/run.go, cmd/terramate/cli/tmcloud/auth/cloud_credential_github_oidc.go, cmd/terramate/cli/tmcloud/auth/cloud_credential_gitlab_oidc.go, cmd/terramate/cli/tmcloud/auth/cloud_credential_google.go, cmd/terramate/cli/tmcloud/cloud.go, e2etests/cloud/run_cloud_uimode_test.go, hcl/hcl.go, hcl/hcl_test.go, terramate.tm
Terramate Cloud is now live in multiple regions and this configuration allows for users choosing which region best suits their needs.
Example:
```hcl
terramate {
config {
cloud {
location = "us"
}
}
}
```
The available options are just `"eu"` and `"us"` at the moment.
none
Note: tests are still WIP.
```
yes, includes a new configuration option.
```
=> feat: add`terramate.config.cloud.location` for setting the cloud location.

cmd/terramate/cli/cli.go, cmd/terramate/cli/clitest/messages.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/run.go, cmd/terramate/cli/tmcloud/auth/cloud_credential_google.go, e2etests/cloud/run_cloud_uimode_test.go
When the user uses `terramate cloud login` but still haven't signup in Terramate, we were giving an error message saying he needs authenticate in the CLI when actually the correct message is that he needs to visit the cloud website and signup.
none
```
yes, fixes an issue
```
=> fix: misleading error message when TMC onboarding is incomplete.

e2etests/cloud/main_test.go, e2etests/core/main_test.go, makefiles/unix.mk
Multiple invocations of `make test` that fails lead to filling the /tmp directory with generated test files.
none
```
no
```
=> chore: improve tests not cleaning up test files.

CHANGELOG.md, cmd/terramate/cli/tmcloud/auth/cloud_credential_google.go
When using `terramate cloud login --github` the CLI is giving an incorrect error telling the user that email is not verified. The problem is because it's checking the `email_verified` field from the response of the `signInWithIDP` Firebase endpoint and the field relates to the federated `email_verified` state but this is not important for Terramate Cloud. The JWT `email_verified` claim that should be used instead.
Fixes an issue reported by a customer.
```
yes
```
=> fix(tmc): github login should check "email_verified" from JWT.

CHANGELOG.md, cloud/cloud.go, cloud/types.go, cmd/terramate/cli/cli.go, cmd/terramate/cli/cloud.go, cmd/terramate/cli/tmcloud/auth/cloud_credential_github.go, cmd/terramate/cli/tmcloud/auth/cloud_credential_google.go, cmd/terramate/cli/tmcloud/auth/cloud_credential_sso.go, e2etests/cloud/run_cloud_uimode_test.go
Implements `terramate cloud login --sso` for Single-Sign-On login.
none
```
yes, adds a new flag to `terramate cloud login`
```
=> feat: add support for SingleSignOn login.

cmd/terramate/cli/tmcloud/auth/cloud_credential_google.go, e2etests/cloud/run_cloud_uimode_test.go
`cloud info` showing all orgs instead of active ones.
none
```
no because it's not released yet.
```
=> fix: cloud info shows all orgs instead of active ones.

e2etests/core/cli_args_test.go, ui/tui/cli.go, ui/tui/cli_handler.go, ui/tui/cli_options.go, ui/tui/cli_spec.go
This fix an edge case when a `root-only-flag` (eg.: --version) is used with
a subcommand (eg.: `list`).
The invocation below:
```
terramate --version list
```
must fail.
Additionally, it fixes the "terramate" name in the *Usage* line that was not lowercase.
none
```
no because affected code is not released
```
=> fix: non-subcmd commands when used with root-flag-only-commands.

ui/tui/cli.go, ui/tui/cli_handler.go, ui/tui/cli_options.go, ui/tui/cli_spec.go
This is needed for creating alternative CLI flag handlers.
none
```
no
```
=> refactor: export DefaultRootFlagHandlers() to be reused.

e2etests/cloud/interop/interoperability_test.go
The commands in interop tests were invoked like `-- /tmp/cmd-tmpdir-..../terraform plan`
but the internal changeset detail extraction command is invoked as "terraform show ...".
So the problem was that `PATH` did not contain the `terraform` binary anywhere and then the details were not synced. 
none
```
no
```
=> test: fix interop test to use Terraform from PATH env.

config/config.go, config/config_test.go, hcl/hcl.go, hcl/hcl_test.go, stack/clone.go, test/stack.go, ui/tui/cli.go
This change is required for upcoming performance optimizations in the Terragrunt module detection.
none
Main goal of this change is making the *Root available during the loadTree() tree walking for allowing a context and pool of workers for the Terragrunt async loading.
```
no
```
=> refactor: improve configuration loading.

config/config.go, tg/tg_module.go, tg/tg_module_test.go
When the project contains incomplete "terragrunt.hcl" files that are used by root modules, Terramate is issuing errors for the temporary parsers.
```
terramate run --changed -X -- echo ok
ERRO[0000] Error: Error in function call
ERRO[0000]   on /home/i4ki/src/terramate-terragrunt-infrastructure-live-example/terragrunt.hcl line 9, in locals: 
ERRO[0000]    9:   account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl")) 
ERRO[0000]                                              
ERRO[0000] Call to function "find_in_parent_folders" failed: ParentFileNotFoundError: Could not find a account.hcl
in any of the parent folders of
/home/i4ki/src/terramate-terragrunt-infrastructure-live-example/terragrunt.hcl. Cause: Traversed all the way to the root..
terramate: Entering stack in …
```
=> fix: terragrunt loader printing misleading error.

ui/tui/cli_spec.go
Trigger has been promoted to stable so the experimental version should be removed from the help listing.
```
No, just the help is affected.
```
=> chore: hide deprecated experimental trigger in help

CHANGELOG.md, e2etests/core/change_detection_test.go, stack/manager.go
This PR fixes a bug in the change detection that would mistakenly list a stack as changed in some circumstances.
The scenario is that if a stack named `foobar` references a Terraform module, then changes in that module will also flag a stack with a common name prefix as changed, i.e. a stack named `foo`.
```
No, it is a change in behaviour but does not break compatibility.
```
=> fix: module change detection for common name prefix

CHANGELOG.md, engine/cloud.go, engine/engine.go, ui/tui/cli_handler.go
Fix a crash in `terramate cloud login --sso` which happened to the lack of mandatory field initialization in the engine
=> Fix crash in terramate cloud login with SSO

CHANGELOG.md, stdlib/funcs.go, stdlib/funcs_join_list.go, stdlib/funcs_join_list_errors.go, stdlib/funcs_join_list_test.go
This PR introduces a new built-in Terramate function `tm_joinlist()` that joins nested lists of strings with a separator. This function enables users to efficiently convert hierarchical list structures into joined string paths, complementing functions like `tm_tree()` for code generation workflows.
Key features:
- Converts list of string lists into list of joined strings
- Supports any string separator (single character, multi-character, or empty)
- Returns deterministic, order-preserving output
- Handles both HCL list and tuple types seamlessly
- Comprehensive error handling with custom error types
Implementation details:
- Added tm_joinlist() function in stdlib/funcs_join_list.go
- Created custom error types in stdlib/funcs_join_list_errors.go for better error reporting
- Comprehensive …
=>  feat: Add tm_joinlist() function for joining nested lists of strings

.gitignore, CHANGELOG.md, stdlib/funcs.go, stdlib/funcs_unslug.go, stdlib/funcs_unslug_errors.go, stdlib/funcs_unslug_test.go
This PR introduces the `tm_unslug()` function, which provides the inverse operation of `tm_slug()` by mapping slugs back to their original human-readable strings using a caller-provided dictionary.
- **Polymorphic behavior**: Accepts both `string` and `list(string)` inputs, with output shape mirroring the input
- **Dictionary-based mapping**: Uses a provided list of unslugged canonical values to perform reliable reverse mapping
- **Smart normalization**: Handles trailing separators and collapsed internal separators for robust matching
- **Collision detection**: Raises a typed `UnslugErrorIndeterministic` error when a slug maps to multiple dictionary entries
- **Round-trip guarantee**: For all words in the dictionary: `tm_unslug(tm_slug(word), dictionary) == word`
- **Special character …
=> feat: add tm_unslug() function to reverse tm_slug() from a dictionary

commands/generate/generate.go, commands/stack/create/create.go, generate/generate.go, generate/generate_api.go, generate/generate_bench_test.go, generate/generate_hcl_test.go, generate/generate_test.go, generate/outdated_detection_test.go, generate/vendor_test.go, test/sandbox/sandbox.go
This PR continues from #2200  to move the main code generation function (`generate.Do`) to the `generate.API`.
Existing callers are modified. This means overrides of the API will automatically be used by `terramate generate` and `terramate create`. 
```
no
```
=> refactor: move generate.Do to generate.API

e2etests/cloud/run_cloud_drift_test.go, e2etests/core/list_git_test.go
Adds additional fields to ignore in the cloud drift test comparison:
- Ignores the `Complete` field in the `tfjson.Plan` struct
- Ignores the `SensitiveValues` field in the `tfjson.StateResource` struct
In newer versions of tofu and terraform, these fields are present but don't affect the actual test validation logic.
Fixes #
This change helps prevent flaky tests by ignoring non-essential fields during plan comparison.
No
=> chore: fix tests with newer terraform versions
